<h2>Impact (v0.64) - 'Impact (v0.64).ipynb'</h2>

<u><h4>Context</h4></u>

The aim of the 'Impact' notebooks are to explore economic impacts resulsting from the FEM outputs in the lead-up to Autumn 2026, taking foward outputs from the associated 'Trade' notebooks.

<u><h4>Version Documentation and Future Work</h4></u>

'v0.2' cleaned up the analysis code by introducing the cost intensity estimation functions that were previously in the 'inventories' notebooks. For example, the 'get_usd_per_tnm' function is included here and applied to voyages identified as relevant to each individual trade record. The NZF costs associated with each trade record are now evaluated like this. 'v0.3' introduced the exporter- and importer-side trade portfolios at an HS-digit 4 level of resolution. With this implemented, the matching algorithm is now be being evaluated using the cargo weight field rather than value, and the process will be being conducted at the HS-digit 4 level of resolution. Since we are now confident regarding the use of the Global Shipping Watch dataset for the purposes of matching HS codes with facilitating vessel types, we should then be in good shape to take the analysis forward using the results produced in this notebook. 'v0.3' also subsumed the 'inventories' notebooks. In 'v0.4' sought to include transport costs data from UNCTAD's Trade-and-Transport database. However, there are now concerns regarding this dataset as it is importer-side only, and therefore has odd looking exporter-side portfolios. Instead, it makes sense for us to utilise trade portfolios derived from UN Comtrade, where these are submitted with disaggregation by Transport Mode. Looking at the 16 countries of interest across African and Caribbean economies we're interested in the summer of 2026, 13 of these have a trade portfolio with MoT Breakdown available across at least one year within the last decade. Therefore this approach makes more sense, and 'v0.6' was amended to work with Comtrade import and export trade portfolios downloaded from the platform. 'v0.61' made use of the updated 'trade' notebooks that derive a new weight field using Value-to-Weight and Weight-to-Value ratios observed in the CEPII BACI datasets across 2017-23. In the case of Trinidad and Tobaogo, import volumes were around 65% higher under the WtV approach which corresponded to a 39% greater 2041 BAU impact from FEM costs, but this was slightly less for exports where the weighted WtV was 9% more but 2041 FEM costs under BAU were around 10% less. A new 'composite' weight field has been added in Trade (v0.61) which only introduces the VtW-derived values where 'netWgt' is observed to be zero, however this resulted in only a tiny increase in recorded weight of around 1% for Angola, whereas the full VtW-derived field was ~50% greater. 

'v0.62' makes use of a new 'transport cost' field derived using ad-valorem transport cost rates identified from UNCTAD's Trade-and-Transport database. With these, we can now introduce another results disaggregation that presents NZF costs relative to expected transport costs, which is then fully in-line with how impacts are expressed in UNCTAD's CIA Task 3 work. 'v0.63' includes an assessment of 'Cost Intensity' matching process (similar to CIF-FOB matching), plus metrics on 'fac_vessel_types' and 'average sea-distance' (introduced in Trade v0.63). 'v0.64' has been modified throughout to account for a new scenario, namely the 'Japan' proposal, plus to remove the 'Low-then-High' scenario. In terms of the Impact notebook, this remains the same as 'v0.63'.

In [1]:
# Import packages
import os
import ast
import base64
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 250)
pd.set_option('display.max_rows', 250)
pd.options.mode.chained_assignment = None
from IPython.display import HTML
import matplotlib.pyplot as plt
import matplotlib.style
plt.style.use('seaborn-v0_8')

def voyages_analysis(voys):
    # Define a function to analyses key statistics from a given set of voyages, 'voys'.
    print("Number of Voyages found: {0}".format(voys.shape[0]))
    print("Total size of the fleet: {0} vessels".format(len(voys.imo.unique())))
    print("{0} vessel types contained in the dataset: {1}".format(len(voys.vessel_type.unique()), voys.vessel_type.unique()))
    print("Total transport work capacity: {0} million deadweight-tonne nautical miles".format(np.round(voys.dwtnm.sum() / 1e6, 1)))
    print("Total cargo transported: {0} tonnes".format(np.round(voys.tonnes.sum(), 1)))
    print("Total transport work: {0} million tonne nautical miles".format(np.round(voys.tnm.sum() / 1e6, 1)))
    print("Average build year of the fleet: {0}".format(int(np.round(voys.year_of_built.mean(), 0))))
    print("Total Energy Demands: {0} EJ".format(np.round(voys.energy_tj.sum(), 1)))
    print("Total CO2 produced: {0} tonnes".format(np.round(voys.co2_t.sum(), 1)))

def get_usd_per_dwtnm(voys, field_name):
    # Derive the deadweight-average of the cost intensity (per unit of cargo-carrying capacity) for the field 'field_name' in an input selection of voyages, 'voys'.
    return (voys[field_name].values * voys.deadweight.values).sum() / voys.deadweight.sum()
    
def get_usd_per_tnm(voys, field_name):
    # Derive the deadweight-average of the cost intensity (per unit of cargo-carried) for the field 'field_name' in an input selection of voyages, 'voys'.
    return (voys[field_name].values / voys.class_util.values * voys.tonnes.values).sum() / voys.tonnes.sum()

def download_link(df, title = "Download CSV file", filename = "data.csv"):
    csv = df.to_csv()
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
    html = html.format(payload=payload,title=title,filename=filename)
    return HTML(html)

version = "v0.64"
input_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/"
voys_fem_dir = "/Users/apple/repos/datasets/ucl/fleet evolution model/2026 annex vi amendments (v0.2)/2. NZF Impact Costs for 2018 IMO IV Voyages/voys_fem_v0.2.csv"
output_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/impact/"
res_mlc = False

# 1. Set up the notebook

## 1.1 Let's set the country we're interested in and set up a results folder.

In [2]:
# Select one of our countries to work on...
iso_code = "328"
iso_country = "Guyana"
year = 2025
gdp = 27.1000e9

# Create output Journey directory folder if necessary
os.makedirs(output_dir+"{0}/".format(iso_country)) if not os.path.exists(output_dir+"{0}/".format(iso_country)) else "Output directory already exists."
os.makedirs(output_dir+"{0}/results/".format(iso_country)) if not os.path.exists(output_dir+"{0}/results/".format(iso_country)) else "Output results folder already exists."

## 1.2 Voyages with FEM Results

In [3]:
voys_fem_d = {
    "source_iso":str, "source_iso_code":str, "source_iso_3":str, "source_iso_2":str, 
    "dest_iso_code":str, "dest_iso_code":str, "dest_iso_3":str, "dest_iso_2":str, 
    "source_region_code":str, "source_sub_region_code":str, "dest_region_code":str, "dest_sub_region_code":str, 
    "source_ldc":str, "source_sids":str, "dest_ldc":str, "dest_sids":str
}

voys_fem = pd.read_csv(voys_fem_dir, dtype=voys_fem_d)
voys_fem["dwtnm"] = voys_fem.deadweight * voys_fem.dist_travelled_ais
voys_fem["tonnes"] = voys_fem.deadweight * voys_fem.class_util
voys_fem["tnm"] = voys_fem.tonnes * voys_fem.dist_travelled_ais
voys_fem.loc[voys_fem.source_country == "Namibia", "source_iso_2"] = "NA"
voys_fem.loc[voys_fem.dest_country == "Namibia", "dest_iso_2"] = "NA"

countries_set = pd.Series(list(set(list(voys_fem.source_country.unique()) + list(voys_fem.dest_country.unique())))).sort_values()
print("Number of countries present in dataset: {0}.".format(len(countries_set)))
print("Number of IMO numbers present in dataset: {0}.".format(len(voys_fem.imo.unique())))
print("Total CO2 contained within the dataset: {0} million tonnes.".format(np.round(voys_fem.co2_t.sum() / 1e6, 1)))
print("Vessel types present in dataset: \n\n{0}\n".format(pd.Series(voys_fem.vessel_type.unique()).sort_values().values))
#print("\nCountries in dataset: \n\n", countries_set.values, "\n")
voys_fem.head(2)

Number of countries present in dataset: 207.
Number of IMO numbers present in dataset: 26132.
Total CO2 contained within the dataset: 544.7 million tonnes.
Vessel types present in dataset:

['Bulk carrier' 'Chemical tanker' 'Container' 'General cargo'
 'Liquefied gas tanker' 'Oil tanker' 'Refrigerated bulk' 'Vehicle']

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,0,5034525,413781699,CNTAX,156,CHN,CN,China,Taixing,CNNKG,156,CHN,CN,China,Nanjing,2018-01-01 06:00:00,2018-01-01 19:00:00,13.0,1.0,14.0,62.568523,0.0,0.0,0.0,3.635661,0.338483,3.974144,0.0,0.0,0.0,0.0,0.0,0.0,0.155243,0.014453,11.655930,1.085176,12.741107,142,Asia,030,Eastern Asia,upp_mid_income,0,0,142,Asia,030,Eastern Asia,upp_mid_income,0,0,0.169696,Refrigerated bulk,3786.0,dwt,3881.0,NaN,NaN,NaN,NaN,2,2000-5999,1959.0,Panama,SSD,4,76.1,0.666667,0.03155,0.032676,0.032143,0.031676,0.031218,0.030769,0.03031,0.029878,0.029438,0.031576,0.052178,0.052414,0.05804,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.05942,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,242828.439338,7661.320668,7934.549945,7805.304846,7691.950531,7580.696290,7471.542086,7360.199865,7255.307537,7148.350725,7667.458038,12670.391275,12727.642802,14093.647297,14570.027623,14398.931835,14189.590704,14139.488873,14161.462401,7665.715352,8412.516422,8946.627490,10860.650719,12049.492896,13084.201484,14034.766615,14342.763237,14083.751009,7665.715352,7946.962662,8384.668998,9891.651071,11698.979626,13565.379532,13949.851660,14247.178318,14428.769963,7663.482493,7940.155892,8209.623358,9221.805242,9744.436151,10159.112402,10518.004352,10853.785659,11140.079340,7663.482493,8252.567981,8473.856677,8773.523328,9299.485535,9694.695953,9860.244395,9979.919640,10068.487874,2587.333335,161885.626306
1,1,5034525,413781699,CNNKG,156,CHN,CN,China,Nanjing,CNTOL,156,CHN,CN,China,Tongling,2018-01-01 20:00:00,2018-01-04 17:00:00,69.0,59.0,128.0,134.252308,0.0,0.0,0.0,21.355373,19.491146,40.846519,0.0,0.0,0.0,0.0,0.0,0.0,0.911874,0.832272,68.465325,62.488615,130.953940,142,Asia,030,Eastern Asia,upp_mid_income,0,0,142,Asia,030,Eastern Asia,upp_mid_income,0,0,1.744146,Refrigerated bulk,3786.0,dwt,3881.0,NaN,NaN,NaN,NaN,2,2000-5999,1959.0,Panama,SSD,4,76.1,0.666667,0.03155,0.032676,0.032143,0.031676,0.031218,0.030769,0.03031,0.029878,0.029438,0.031576,0.052178,0.052414,0.05804,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.05942,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,521033.206847,16438.776642,17025.040451,16747.721252,16504.498662,16265.782167,16031.571689,15792.666415,15567.600579,15338.105010,16451.945500,27186.661563,27309.505274,30240.519881,31262.681739,30895.564166,30446.384156,30338.881438,30386.029694,16448.206246,18050.605691,19196.639505,23303.529390,25854.409564,28074.567693,30114.180516,30775.044079,30219.285570,16448.206246,17051.674227,17990.853906,21224.361910,25102.318690,29107.023950,29931.979818,30569.949005,30959.587375,16443.415234,17037.069045,17615.261197,19787.084130,20908.485145,21798.249530,22568.318408,23288.799137,23903.095037,16443.415234,17707.406809,18182.222523,18825.212595,19953.761526,20801.758375,21156.973093,21413.758406,21603.797889,2587.333335,347355.471405

# 2. Let's consider Imports

## 2.1 Read-in Trade dataset

In [4]:
trade_im_d = {
    "reporterCode":"str", "partnerCode":"str", "partner2Code":"str", 
    "cmdCode":"str", "HS2":"str", "HS4":"str", "hs2":"str", "hs4":"str", "hs6":"str",
    "isic":"str", "sitc":"str", "gtap":"str", "cpc":"str"
}
if res_mlc == False:
    trade_im = pd.read_csv(input_dir+"trade/{0}/trade_im_dist_{1}.csv".format(iso_country, version), dtype=trade_im_d)
else:
    trade_im = pd.read_csv(input_dir+"trade/{0}/trade_im_mlc_{1}.csv".format(iso_country, version), dtype=trade_im_d)
trade_im['fac_vessel_types'] = [ast.literal_eval(x) for x in trade_im.fac_vessel_types.values]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(trade_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_im.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(trade_im.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(trade_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_im.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_im.sea_dist_nm.min(), 1),
    round(trade_im.sea_dist_nm.max(), 1),
    round(trade_im.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_im.vol_kg_vtw / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_im.cifvalue / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.cifvalue.sum() / 1000), 1)
))
trade_im.head(2)

Aggregate trade portfolio statistics for 'Guyana':

Number of trade records present in dataset: 21216
Number of partner countries present in dataset: 140
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$9565.0m
Total weight within the dataset: 8006.2 million kilograms

Distance to market: 250.4 nm (min) to 13532.2 nm (max), 5451.9 nm (observed mean)
Average distance to market (volume-weighted): 3647.7 nm
Average distance to market (value-weighted): 6975.3 nm

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_im_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm
0,0,328,Guyana,056,Belgium,000,World,Import,Sea,320820 | Paints and varnishes,320820,kg,60.0,60.0,1685.663,NaN,1685.663,Belgium | 320820 | Paints and varnishes,32,32 | Tanning or dyeing ex,Belgium | 32 | Tanning or dyeing ex,3208,"3208 | Paints, varnishes; (","Belgium | 3208 | Paints, varnishes; (",32,3208,320820,Paints & varnishes (incl. enamels & lacquers) ...,"Petroleum, Chemical and Non-Metallic Mineral P...",2422,"Manufacture of paints, varnishes and similar c...",53342,Paints & varnishes (including enamels & lacque...,33,"CRP - Chemical, rubber, plastic products",3511,Paints and varnishes (including enamels and la...,5.1813,0.1930,both,0.035594,325.332959,60.0,[Container],['Container'],6364.0,3954.405044,1286.498294
1,1,328,Guyana,056,Belgium,000,World,Import,Sea,"560750 | Twine, cordage, rope",560750,kg,1267.0,1267.0,4954.592,NaN,4954.592,"Belgium | 560750 | Twine, cordage, rope",56,"56 | Wadding, felt and no","Belgium | 56 | Wadding, felt and no",5607,"5607 | Twine, cordage, rope","Belgium | 5607 | Twine, cordage, rope",56,5607,560750,"Twine, cordage, ropes & cables of synthetic fi...",Textiles and Wearing Apparel,1723,"Manufacture of cordage, rope, twine and netting",65751,"Twine, cordage, ropes & cables, whether/not pl...",27,TEX - Textiles,2731,"Twine, cordage, rope and cables",3.9044,0.2561,both,0.255722,1268.871011,1267.0,[Container],['Container'],6364.0,3954.405044,5017.629927

## 2.2 Derive Internationally Arriving Voyages

In [5]:
# International Arrivals
int_arr_voys = voys_fem[(voys_fem.dest_country == iso_country) & (voys_fem.source_country != iso_country)].reset_index(drop=True)
int_arr_voys.to_csv(output_dir + "{0}/int_arr_voys_{1}.csv".format(iso_country, version), index=False)
int_dep_voys = voys_fem[(voys_fem.source_country == iso_country) & (voys_fem.dest_country != iso_country)].reset_index(drop=True)
int_dep_voys.to_csv(output_dir + "{0}/int_dep_voys_{1}.csv".format(iso_country, version), index=False)
voyages_analysis(int_arr_voys)
int_arr_voys.head(2)

Number of Voyages found: 488
Total size of the fleet: 168 vessels
5 vessel types contained in the dataset: ['General cargo' 'Refrigerated bulk' 'Bulk carrier' 'Container'
 'Chemical tanker']
Total transport work capacity: 6550.8 million deadweight-tonne nautical miles
Total cargo transported: 4597150.5 tonnes
Total transport work: 4071.9 million tonne nautical miles
Average build year of the fleet: 2009
Total Energy Demands: 804.7 EJ
Total CO2 produced: 61750.9 tonnes

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,17445,8121379,375401000,BBBGI,052,BRB,BB,Barbados,Bridgetown,GYGEO,328,GUY,GY,Guyana,Georgetown,2018-01-10 14:00:00,2018-01-19 12:00:00,214.0,5.0,219.0,499.821827,3.278513,0.000962,3.279475,11.5175,0.3125,11.8300,0.0,0.0,0.0,0.0,0.0,0.0,0.623593,0.013382,47.134393,1.004872,48.139265,019,Americas,419,Latin America and the Caribbean,high_income,0,1,019,Americas,419,Latin America and the Caribbean,high_income,0,1,0.636976,General cargo,3222.0,dwt,5350.0,146.0,NaN,NaN,NaN,2,5000-9999,1983.0,St Vincent & The Grenadines,MSD,1,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.02233,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.01858,0.018382,0.01842,0.013244,0.01391,0.014148,0.014473,0.01505,0.015474,0.015636,0.015745,0.015819,2.674047e+06,35417.606732,36262.514450,35862.849440,35512.323550,35168.291724,34830.753848,34486.449959,34162.091097,33831.348223,35413.531446,50785.246561,50061.090404,53627.261854,59376.902201,58790.941802,56969.631150,53756.811466,51765.873732,35411.989212,37636.566951,38569.465389,44272.705572,48753.521886,57373.641007,56347.124965,55309.199705,51941.983923,35411.989212,36212.775244,37467.909658,41880.257114,47095.597175,59712.731977,57752.178403,58224.701998,57623.379031,35414.682322,36235.668913,37023.804662,40071.710279,41201.066519,43978.954445,49684.431958,49154.357075,49254.947308,35414.682322,37195.012365,37833.039020,38702.164512,40245.322706,41378.241103,41811.823651,42103.639136,42299.614487,3422.558924,1.710670e+06
1,17447,8121379,375401000,BBBGI,052,BRB,BB,Barbados,Bridgetown,GYGEO,328,GUY,GY,Guyana,Georgetown,2018-03-01 02:00:00,2018-03-04 10:00:00,80.0,171.0,251.0,453.650274,2.978985,0.065630,3.044616,3.0718,11.7023,14.7741,0.0,0.0,0.0,0.0,0.0,0.0,0.250921,0.502327,19.124751,37.721947,56.846698,019,Americas,419,Latin America and the Caribbean,high_income,0,1,019,Americas,419,Latin America and the Caribbean,high_income,0,1,0.753248,General cargo,3222.0,dwt,5350.0,146.0,NaN,NaN,NaN,2,5000-9999,1983.0,St Vincent & The Grenadines,MSD,1,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.02233,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.01858,0.018382,0.01842,0.013244,0.01391,0.014148,0.014473,0.01505,0.015474,0.015636,0.015745,0.015819,2.427029e+06,32145.869056,32912.727559,32549.982013,32231.836311,31919.584777,31613.227308,31300.728844,31006.332964,30706.142801,32142.170229,46093.907425,45436.645935,48673.388647,53891.900081,53360.068374,51707.003158,48790.970980,46983.948158,32140.770461,34159.850554,35006.571543,40182.969077,44249.865397,52073.692190,51142.001619,50199.955767,47143.789990,32140.770461,32867.583063,34006.773151,38011.525494,42745.093179,54196.707238,52417.261808,52846.135552,52300.360409,32143.214792,32888.361906,33603.692808,36370.045024,37395.075825,39916.353511,45094.781698,44613.673025,44704.971133,32143.214792,33759.085024,34338.173314,35127.012449,36527.619826,37555.883726,37949.413642,38214.272373,38392.144300,3422.558924,1.552645e+06

## 2.3 Evaluate NZF Costs

In [6]:
years=["26", "29", "32", "35", "38", "41", "44", "47", "50"]
vess_types_not_found_in_inventories, vess_types_not_found_in_global_voys, hs_codes_not_mapped_to_HS, cost_int_match_desc, cost_int_match_desc_bool = [], [], [], [], False

for year in years:

    print("Processing game year 20{0}".format(year))

    # Setup columns for policy costs per bilateral goods trade.
    bau_usd, levy_usd, asis_usd, brazil_usd, liscr_usd, direct_usd = [], [], [], [], [], []
    
    for trade_idx, trade in trade_im.iterrows():

        # initiate selected voyages table as empty dataframe to begin
        int_arr_voys_vess = pd.DataFrame()

        # 3. If no facilitating vessel types were picked up for the HS code, take from full primary int. inv. voyages dataset, otherwise move on...
        if 'all' in trade.fac_vessel_types:
            hs_codes_not_mapped_to_HS.append(trade.HS4_desc)
            int_arr_voys_vess = int_arr_voys
            cost_int_match_desc.append("3. Primary Int. Inv. without Vess Type") if cost_int_match_desc_bool == False else None

        else:
            # 1. If possible, derive subset of voyages associated with the unique vessel type.
            int_arr_voys_vess = int_arr_voys[(int_arr_voys.vessel_type.isin(trade.fac_vessel_types))]    
            
            if int_arr_voys_vess.shape[0] > 0:
                cost_int_match_desc.append("1. Primary Int. Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                
            else:
                # 2. Finally, if no voyages are found as the vessel type doesn't appear in the country's shipping inventories, also take from full voyages dataset filtered for those vessel types instead.
                int_arr_voys_vess = voys_fem[(voys_fem.vessel_type.isin(trade.fac_vessel_types))]

                if int_arr_voys_vess.shape[0] > 0:
                    cost_int_match_desc.append("2. Global Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_inventories.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

                else:
                    # 4. Use full global voyage dataset as a back-up
                    int_arr_voys_vess = voys_fem
                    cost_int_match_desc.append("4. Global Inv. without Vess Type.") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_global_voys.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

        # Add cost intensities associated with the subset of voyages by vessel type, assuming 50% of NZF costs are borne by the importer.
        bau_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "bau35_usd_dwtnm_"+year))
        levy_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "levy35_usd_dwtnm_"+year))
        asis_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "asis35_usd_dwtnm_"+year))
        brazil_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "brazil35_usd_dwtnm_"+year))
        liscr_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "liscr35_usd_dwtnm_"+year))
        direct_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "direct35_usd_dwtnm_"+year))
    
    if cost_int_match_desc_bool == False:
        trade_im["cost_int_match_desc"] = cost_int_match_desc
    cost_int_match_desc_bool = True
    
    trade_im["bau_usd_"+year] = bau_usd
    trade_im["levy_usd_"+year] = levy_usd
    trade_im["asis_usd_"+year] = asis_usd
    trade_im["brazil_usd_"+year] = brazil_usd
    trade_im["liscr_usd_"+year] = liscr_usd
    trade_im["direct_usd_"+year] = direct_usd

print("Inventory voyages table used for the following vessel types: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_inventories).unique()))
print("Global voyages table used for the following vessel types found: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_global_voys).unique()))
print("Global voyages table used for the following commodities as no 'facilitating vessel types' were identified: \n\n{0}\n".format(pd.Series(hs_codes_not_mapped_to_HS).unique()))

print("\nNumber of trade records present in dataset: {0}".format(trade_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_im.partnerCode.unique())))
print("\nTotal value of trade: US${0}m".format(np.round(trade_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_im.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_im.sea_dist_nm.min(), 1),
    round(trade_im.sea_dist_nm.max(), 1),
    round(trade_im.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_im.vol_kg_vtw / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_im.cifvalue / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.cifvalue.sum() / 1000), 1)
))

print("\n\nTotal FEM costs in 2041...\n")
print("BAU: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.bau_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.bau_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Levy: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.levy_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.levy_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("'as-is': US${0}m ({1}% ad-val)".format(
    np.round(trade_im.asis_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.asis_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Brazil: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.brazil_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.brazil_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("LISCR: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.liscr_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.liscr_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Direct: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.direct_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.direct_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))

trade_im_agg = trade_im.groupby(["cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "cifvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_im_agg["vol_kg_vtw_pct"] = round(100 * trade_im_agg.vol_kg_vtw / trade_im_agg.vol_kg_vtw.sum(), 1)
trade_im_agg["cifvalue_pct"] = round(100 * trade_im_agg.cifvalue / trade_im_agg.cifvalue.sum(), 1)
print("Most prominent 'cost intensity match' types...\n\n{0}\n".format(
    trade_im_agg[["cost_int_match_desc", "vol_kg_vtw_pct", "cifvalue_pct"]].head(5)
))
trade_im_agg_2 = trade_im.groupby(["fac_vessel_types_str", "cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "cifvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_im_agg_2["vol_kg_vtw_pct"] = round(100 * trade_im_agg_2.vol_kg_vtw / trade_im_agg_2.vol_kg_vtw.sum(), 1)
trade_im_agg_2["cifvalue_pct"] = round(100 * trade_im_agg_2.cifvalue / trade_im_agg_2.cifvalue.sum(), 1)
print("Most prominent 'facilitating vessel types' and their 'cost intensity match' types...")
display(trade_im_agg_2[["fac_vessel_types_str", "cost_int_match_desc", "vol_kg_vtw_pct", "cifvalue_pct"]].head(5))

trade_im_na = trade_im[(trade_im[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (trade_im.fac_vessel_types.str.len() == 0)]
trade_im = trade_im[(~trade_im[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (~trade_im.fac_vessel_types.str.len() == 0)]
print("Rows with NA: ${0} ({1}%)\n".format(trade_im_na.primaryValue.sum(), round(100 * trade_im_na.primaryValue.sum() / trade_im.primaryValue.sum(), 1)))

trade_im.to_csv(output_dir + "{0}/impact_im_{1}.csv".format(iso_country, version), index=False)
trade_im.head(2)

Processing game year 2026
Processing game year 2029
Processing game year 2032
Processing game year 2035
Processing game year 2038
Processing game year 2041
Processing game year 2044
Processing game year 2047
Processing game year 2050
Inventory voyages table used for the following vessel types:

['Oil tanker' 'Liquefied gas tanker' 'Vehicle' 'Ro-Ro']

Global voyages table used for the following vessel types found:

['Other liquids tankers' 'Ro-Ro' 'Cruise']

Global voyages table used for the following commodities as no 'facilitating vessel types' were identified:

['2106 | Food preparations no' '6406 | Footwear; parts of f'
 '1905 | Bread, pastry, cakes' '2202 | Waters, including mi'
 '1704 | Sugar confectionery ' '2009 | Fruit or nut juices '
 '3307 | Perfumery, cosmetic ' '1509 | Olive oil and its fr'
 '4414 | Wooden frames; for p' '4419 | Tableware and kitche'
 '4420 | Wood marquetry and i' "4418 | Builders' joinery an"
 '4412 | Plywood, veneered pa' '6704 | Wigs, false beards, '
 '4401 | Fuel wood, in logs, ' '2403 | Manufactured tobacco'
 '5703 | Carpets and other te' '6907 | Ceramic flags and pa'
 "6202 | Coats; women's or gi" '2204 | Wine of fresh grapes'
 '4407 | Wood sawn or chipped' '4403 | Wood in the rough, w'
 '8903 | Yachts and other ves' '8514 | Industrial or labora'
 '7019 | Glass fibres (includ' '9702 | Engravings, prints a'
 '8548 | Electrical parts of ' '3822 | Reagents; diagnostic'
 '4011 | New pneumatic tyres,' '6201 | Overcoats, car-coats'
 '9701 | Paintings, drawings ' '8525 | Transmission apparat'
 '9703 | Sculptures and statu' '9027 | Instruments and appa'
 '9401 | Seats (not those of ' '8541 | Semiconductor device'
 '8716 | Trailers and semi-tr' '8528 | Monitors and project'
 '8539 | Lamps; electric fila' '8424 | Mechanical appliance'
 '8702 | Vehicles; public tra' '8419 | Machinery, plant (no'
 '8701 | Tractors; (other tha' '8432 | Agricultural, hortic'
 '8703 | Motor cars and other' '8462 | Machine-tools (inclu'
 '8711 | Motorcycles (includi' '8517 | Telephone sets, incl'
 '9006 | Cameras, photographi' '8456 | Machine-tools; for w'
 '8460 | Machine-tools; for d' '8459 | Machine-tools; (incl'
 '8519 | Sound recording or r' '8465 | Machine-tools; (incl' '8803 | nan'
 '7326 | Iron or steel; artic' '9405 | Luminaires and light'
 '6815 | Stone or other miner' '9620 | Monopods, bipods, tr'
 '2844 | Radioactive chemical' '7616 | Aluminium; articles '
 '9406 | Buildings; prefabric' '3926 | Articles of plastics'
 '2309 | Preparations of a ki' '4911 | Printed matter, n.e.'
 '8487 | Machinery parts; not' '2903 | Halogenated derivati'
 '1806 | Chocolate and other ' '4421 | Wooden articles n.e.'
 '0307 | Molluscs; whether in' '3824 | Prepared binders for'
 '8311 | Wires, rods, tubes, ' '3603 | Safety fuses; detona'
 '7508 | Nickel; articles the' '0910 | Ginger, saffron, tum'
 '4015 | Articles of apparel ' '4823 | Paper, paperboard, c'
 '9403 | Furniture and parts ' '7229 | Wire of other alloy '
 '1008 | Buckwheat, millet an' '3402 | Organic surface-acti'
 '8215 | Cutlery; spoons, for' '5911 | Textile products and'
 '7419 | Copper; articles the' '6310 | Rags; used or new, s'
 '2530 | Mineral substances n' '3105 | Fertilizers; mineral'
 '3006 | Pharmaceutical goods' '0403 | Yogurt; buttermilk, '
 '0303 | Fish; frozen, exclud' '6117 | Clothing accessories'
 '3103 | Fertilizers; mineral' '0210 | Meat and edible meat'
 '3812 | Prepared rubber acce' '3507 | Enzymes; prepared en'
 '3705 | Photographic plates ' '3707 | Chemical preparation'
 '6914 | Ceramic articles; n.' '6304 | Furnishing articles;'
 '2914 | Ketones and quinones' '2853 | Phosphides, chemical'
 '2904 | Sulphonated, nitrate' '6005 | Fabrics; warp knit ('
 '4905 | Maps and hydrographi' '9508 | Travelling circuses '
 '4504 | Agglomerated cork (w' '4602 | Basketwork, wickerwo'
 '9209 | Musical instrument p' '6217 | Clothing accessories'
 '0306 | Crustaceans; in shel' '1404 | Vegetable products n'
 '2939 | Alkaloids; natural o' '3004 | Medicaments; (not go'
 '3002 | Human blood; animal ' '3215 | Ink; printing, writi'
 '2621 | Slag and ash n.e.c. ' '3606 | Ferro-cerium and oth'
 '6603 | Trimmings, parts and' '5802 | Fabrics; terry towel'
 '6006 | Fabrics; knitted or ' '3907 | Polyacetals, other p'
 '3909 | Amino-resins, phenol' '1605 | Crustaceans, mollusc'
 '3808 | Insecticides, rodent' '4707 | Waste and scrap of p'
 '1214 | Swedes, mangolds, fo' '6812 | Fabricated asbestos '
 '0714 | Manioc, arrowroot, s' '0802 | Nuts (excluding coco'
 '2518 | Dolomite, whether or' '2922 | Oxygen-function amin'
 '8109 | Zirconium; articles ' '0308 | Aquatic invertebrate'
 '0604 | Foliage, branches an']


Number of trade records present in dataset: 21216
Number of partner countries present in dataset: 140

Total value of trade: US$9565.0m
Total weight within the dataset: 8006.2 million kilograms

Distance to market: 250.4 nm (min) to 13532.2 nm (max), 5451.9 nm (observed mean)
Average distance to market (volume-weighted): 3647.7 nm
Average distance to market (value-weighted): 6975.3 nm


Total FEM costs in 2041...

BAU: US$158.7m (1.7% ad-val)
Levy: US$326.4m (3.4% ad-val)
'as-is': US$311.5m (3.3% ad-val)
Brazil: US$318.2m (3.3% ad-val)
LISCR: US$222.1m (2.3% ad-val)
Direct: US$209.3m (2.2% ad-val)
Most prominent 'cost intensity match' types...

                      cost_int_match_desc  vol_kg_vtw_pct  cifvalue_pct
0     1. Primary Int. Inv. with Vess Type            75.0          79.2
1           2. Global Inv. with Vess Type            22.0          15.6
2  3. Primary Int. Inv. without Vess Type             3.0           5.2
3       4. Global Inv. without Vess Type.             0.0           0.0

Most prominent 'facilitating vessel types' and their 'cost intensity match' types...

,fac_vessel_types_str,cost_int_match_desc,vol_kg_vtw_pct,cifvalue_pct
0,['Container'],1. Primary Int. Inv. with Vess Type,43.6,33.2
1,['Oil tanker'],2. Global Inv. with Vess Type,20.9,11.1
2,"['Container', 'General cargo']",1. Primary Int. Inv. with Vess Type,9.8,1.3
3,['Chemical tanker'],1. Primary Int. Inv. with Vess Type,5.2,3.0
4,['Bulk carrier'],1. Primary Int. Inv. with Vess Type,4.1,1.3

Rows with NA: $0.0 (0.0%)

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_im_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,cost_int_match_desc,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50
0,0,328,Guyana,056,Belgium,000,World,Import,Sea,320820 | Paints and varnishes,320820,kg,60.0,60.0,1685.663,NaN,1685.663,Belgium | 320820 | Paints and varnishes,32,32 | Tanning or dyeing ex,Belgium | 32 | Tanning or dyeing ex,3208,"3208 | Paints, varnishes; (","Belgium | 3208 | Paints, varnishes; (",32,3208,320820,Paints & varnishes (incl. enamels & lacquers) ...,"Petroleum, Chemical and Non-Metallic Mineral P...",2422,"Manufacture of paints, varnishes and similar c...",53342,Paints & varnishes (including enamels & lacque...,33,"CRP - Chemical, rubber, plastic products",3511,Paints and varnishes (including enamels and la...,5.1813,0.1930,both,0.035594,325.332959,60.0,[Container],['Container'],6364.0,3954.405044,1286.498294,1. Primary Int. Inv. with Vess Type,6.724307,6.712566,6.713713,6.713713,6.718975,6.718975,7.033967,12.466396,7.758691,7.203223,7.222785,7.403686,6.887489,12.208926,8.166511,7.480402,7.308742,7.639755,6.759021,13.276379,10.126866,8.856600,8.194031,7.962888,6.632932,14.116045,11.615884,10.885069,8.772765,8.534223,6.509224,14.304634,13.666812,13.784320,9.510589,8.964926,6.383036,14.010618,13.426464,14.710664,10.881377,9.129239,6.264158,12.497811,13.026046,13.649937,10.232424,9.237106,6.142940,11.480307,11.670033,14.556860,12.026009,9.298275
1,1,328,Guyana,056,Belgium,000,World,Import,Sea,"560750 | Twine, cordage, rope",560750,kg,1267.0,1267.0,4954.592,NaN,4954.592,"Belgium | 560750 | Twine, cordage, rope",56,"56 | Wadding, felt and no","Belgium | 56 | Wadding, felt and no",5607,"5607 | Twine, cordage, rope","Belgium | 5607 | Twine, cordage, rope",56,5607,560750,"Twine, cordage, ropes & cables of synthetic fi...",Textiles and Wearing Apparel,1723,"Manufacture of cordage, rope, twine and netting",65751,"Twine, cordage, ropes & cables, whether/not pl...",27,TEX - Textiles,2731,"Twine, cordage, rope and cables",3.9044,0.2561,both,0.255722,1268.871011,1267.0,[Container],['Container'],6364.0,3954.405044,5017.629927,1. Primary Int. Inv. with Vess Type,26.226294,26.180503,26.184978,26.184978,26.205498,26.205498,27.434038,48.621722,30.260623,28.094172,28.170470,28.876023,26.862741,47.617531,31.851214,29.175236,28.505722,29.796748,26.361686,51.780837,39.497034,34.542712,31.958547,31.057036,25.869914,55.055720,45.304534,42.454194,34.215737,33.285370,25.387425,55.791260,53.303612,53.761921,37.093414,34.965209,24.895264,54.644530,52.366201,57.374868,42.439794,35.606067,24.431613,48.744246,50.804480,53.237793,39.908733,36.026771,23.958836,44.775756,45.515728,56.774996,46.904113,36.265343

## 2.4 Create Results Tables

### 2.4.1 Total Costs per Scenario

In [7]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        np.round(trade_im["bau_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["levy_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["asis_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["brazil_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["liscr_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["direct_usd_{0}".format(year)].sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% cif)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% fob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_fob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_im["bau_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["levy_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["asis_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["direct_usd_{0}".format(year)].sum() / gdp, 3),
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,BAU,1.696673e+08,1.666112e+08,1.639338e+08,1.613067e+08,1.587287e+08,1.561017e+08,1.536279e+08,1.511064e+08
1,Levy,2.826078e+08,2.758884e+08,3.001002e+08,3.230770e+08,3.263676e+08,3.158063e+08,2.864524e+08,2.665817e+08
2,'as-is',1.833088e+08,1.914961e+08,2.325632e+08,2.646781e+08,3.115131e+08,3.045391e+08,2.970871e+08,2.703937e+08
3,Brazil,1.720819e+08,1.786408e+08,2.083451e+08,2.500011e+08,3.181723e+08,3.288656e+08,3.140895e+08,3.256087e+08
4,LISCR,1.724395e+08,1.751926e+08,1.947577e+08,2.056466e+08,2.220599e+08,2.533841e+08,2.433391e+08,2.706683e+08
5,Direct,1.771072e+08,1.819343e+08,1.885952e+08,2.004219e+08,2.092830e+08,2.126239e+08,2.148103e+08,2.164278e+08

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0      BAU  1.77  1.74  1.71  1.69  1.66  1.63  1.61  1.58
1     Levy  2.95  2.88  3.14  3.38  3.41  3.30  2.99  2.79
2  'as-is'  1.92  2.00  2.43  2.77  3.26  3.18  3.11  2.83
3   Brazil  1.80  1.87  2.18  2.61  3.33  3.44  3.28  3.40
4    LISCR  1.80  1.83  2.04  2.15  2.32  2.65  2.54  2.83
5   Direct  1.85  1.90  1.97  2.10  2.19  2.22  2.25  2.26

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  0.626  0.615  0.605  0.595  0.586  0.576  0.567  0.558
1     Levy  1.043  1.018  1.107  1.192  1.204  1.165  1.057  0.984
2  'as-is'  0.676  0.707  0.858  0.977  1.149  1.124  1.096  0.998
3   Brazil  0.635  0.659  0.769  0.923  1.174  1.214  1.159  1.202
4    LISCR  0.636  0.646  0.719  0.759  0.819  0.935  0.898  0.999
5   Direct  0.654  0.671  0.696  0.740  0.772  0.785  0.793  0.799

### 2.4.2 Costs per Scenario relative to BAU

In [8]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        np.round((trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_usd_bau_{1}.csv".format(iso_country, version), index=False)
display(df)

print("\nTotal change in FEM costs by scenario (% bau)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        round((100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2)
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_bau_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% cif)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2)
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% fob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_fob_{1}.csv".format(iso_country, version), index=False)
    display(df)
    
print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3)
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,Levy,1.129405e+08,1.092772e+08,1.361664e+08,1.617703e+08,1.676389e+08,1.597046e+08,1.328245e+08,1.154753e+08
1,'as-is',1.364145e+07,2.488491e+07,6.862945e+07,1.033714e+08,1.527844e+08,1.484374e+08,1.434592e+08,1.192873e+08
2,Brazil,2.414545e+06,1.202960e+07,4.441131e+07,8.869444e+07,1.594436e+08,1.727640e+08,1.604616e+08,1.745023e+08
3,LISCR,2.772167e+06,8.581387e+06,3.082394e+07,4.433990e+07,6.333119e+07,9.728243e+07,8.971120e+07,1.195619e+08
4,Direct,7.439858e+06,1.532310e+07,2.466142e+07,3.911523e+07,5.055431e+07,5.652228e+07,6.118237e+07,6.532147e+07

Total change in FEM costs by scenario (% bau)...

  Scenario   2029   2032   2035    2038    2041    2044    2047    2050
0     Levy  66.57  65.59  83.06  100.29  105.61  102.31   86.46   76.42
1  'as-is'   4.38   9.20  15.04   24.25   31.85   36.21   39.83   43.23
2   Brazil   8.04  14.94  41.86   64.08   96.26   95.09   93.38   78.94
3    LISCR   1.42   7.22  27.09   54.98  100.45  110.67  104.45  115.48
4   Direct   1.63   5.15  18.80   27.49   39.90   62.32   58.40   79.12

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0     Levy  1.18  1.14  1.42  1.69  1.75  1.67  1.39  1.21
1  'as-is'  0.08  0.16  0.26  0.41  0.53  0.59  0.64  0.68
2   Brazil  0.14  0.26  0.72  1.08  1.60  1.55  1.50  1.25
3    LISCR  0.03  0.13  0.46  0.93  1.67  1.81  1.68  1.82
4   Direct  0.03  0.09  0.32  0.46  0.66  1.02  0.94  1.25

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  0.417  0.403  0.502  0.597  0.619  0.589  0.490  0.426
1  'as-is'  0.027  0.057  0.091  0.144  0.187  0.209  0.226  0.241
2   Brazil  0.050  0.092  0.253  0.381  0.564  0.548  0.529  0.440
3    LISCR  0.009  0.044  0.164  0.327  0.588  0.638  0.592  0.644
4   Direct  0.010  0.032  0.114  0.164  0.234  0.359  0.331  0.441

# 3. Let's consider Exports

## 3.1 Read-in Trade dataset

In [9]:
trade_ex_d = {
    "reporterCode":"str", "partnerCode":"str", "partner2Code":"str", 
    "cmdCode":"str", "HS2":"str", "HS4":"str", "hs2":"str", "hs4":"str", "hs6":"str",
    "isic":"str", "sitc":"str", "gtap":"str", "cpc":"str"
}
if res_mlc == False:
    trade_ex = pd.read_csv(input_dir+"trade/{0}/trade_ex_dist_{1}.csv".format(iso_country, version), dtype=trade_ex_d)
else:
    trade_ex = pd.read_csv(input_dir+"trade/{0}/trade_ex_mlc_{1}.csv".format(iso_country, version), dtype=trade_ex_d)
trade_ex['fac_vessel_types'] = [ast.literal_eval(x) for x in trade_ex.fac_vessel_types.values]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(trade_ex.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_ex.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(trade_ex.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(trade_ex.fobvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_ex.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_ex.sea_dist_nm.min(), 1),
    round(trade_ex.sea_dist_nm.max(), 1),
    round(trade_ex.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_ex.vol_kg_vtw / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_ex.fobvalue / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.fobvalue.sum() / 1000), 1)
))
trade_ex.head(2)

Aggregate trade portfolio statistics for 'Guyana':

Number of trade records present in dataset: 1967
Number of partner countries present in dataset: 78
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$17897.5m
Total weight within the dataset: 39456.1 million kilograms

Distance to market: 251.0 nm (min) to 13534.1 nm (max), 2733.5 nm (observed mean)
Average distance to market (volume-weighted): 4667.2 nm
Average distance to market (value-weighted): 4569.9 nm

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_ex_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm
0,0,328,Guyana,276,Germany,000,World,Domestic Export,Sea,442010 | Wood; statuettes and,442010,NaN,0.0,NaN,NaN,16.000,16.000,Germany | 442010 | Wood; statuettes and,44,44 | Wood and articles of,Germany | 44 | Wood and articles of,4420,4420 | Wood marquetry and i,Germany | 4420 | Wood marquetry and i,44,4420,442010,"Statuettes & other ornaments, of wood",Wood and Paper,2029,Manufacture of other products of wood; manufac...,63549,Wood marquetry & inlaid wood; caskets & cases ...,30,LUM - Wood products,31913,Wood marquetry and inlaid wood; cases for jewe...,6.5147,0.1535,both,NaN,2.456000,NaN,[all],['all'],6594.0,4097.320374,10.063019
1,1,328,Guyana,710,South Africa,000,World,Domestic Export,Sea,"401039 | Rubber; vulcanised,",401039,NaN,0.0,NaN,NaN,7.002,7.002,"South Africa | 401039 | Rubber; vulcanised,",40,40 | Rubber and articles,South Africa | 40 | Rubber and articles,4010,4010 | Conveyor or transmis,South Africa | 4010 | Conveyor or transmis,40,4010,401039,Transmission belts/belting (excl. of 4010.31-4...,"Petroleum, Chemical and Non-Metallic Mineral P...",2519,Manufacture of other rubber products,62921,Transmission belts/belting,33,"CRP - Chemical, rubber, plastic products",3624,"Conveyor or transmission belts or belting, of ...",7.9828,0.1253,both,NaN,0.877351,NaN,[Container],['Container'],10569.0,6567.270099,5.761798

## 3.2 Derive Internationally Departing Voyages

In [10]:
# International Departures
int_arr_voys = voys_fem[(voys_fem.dest_country == iso_country) & (voys_fem.source_country != iso_country)].reset_index(drop=True)
int_arr_voys.to_csv(output_dir + "{0}/int_arr_voys_{1}.csv".format(iso_country, version), index=False)
int_dep_voys = voys_fem[(voys_fem.source_country == iso_country) & (voys_fem.dest_country != iso_country)].reset_index(drop=True)
int_dep_voys.to_csv(output_dir + "{0}/int_dep_voys_{1}.csv".format(iso_country, version), index=False)
voyages_analysis(int_dep_voys)
int_dep_voys.head(2)

Number of Voyages found: 485
Total size of the fleet: 167 vessels
5 vessel types contained in the dataset: ['General cargo' 'Refrigerated bulk' 'Bulk carrier' 'Container'
 'Chemical tanker']
Total transport work capacity: 9980.9 million deadweight-tonne nautical miles
Total cargo transported: 4563395.4 tonnes
Total transport work: 6217.2 million tonne nautical miles
Average build year of the fleet: 2009
Total Energy Demands: 1189.2 EJ
Total CO2 produced: 91411.3 tonnes

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,17446,8121379,375401000,GYGEO,328,GUY,GY,Guyana,Georgetown,BBBGI,052,BRB,BB,Barbados,Bridgetown,2018-01-19 17:00:00,2018-02-26 06:00:00,901.0,68.0,969.0,599.566660,3.775032,0.225318,4.000350,71.1139,4.4284,75.5423,0.0,0.0,0.0,0.0,0.0,0.0,3.188320,0.198150,239.746613,14.899090,254.645703,019,Americas,419,Latin America and the Caribbean,high_income,0,1,019,Americas,419,Latin America and the Caribbean,high_income,0,1,3.386470,General cargo,3222.0,dwt,5350.0,146.0,NaN,NaN,NaN,2,5000-9999,1983.0,St Vincent & The Grenadines,MSD,1,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.02233,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.01858,0.018382,0.01842,0.013244,0.01391,0.014148,0.014473,0.01505,0.015474,0.015636,0.015745,0.015819,3.207682e+06,42485.571877,43499.090037,43019.667566,42599.190457,42186.503372,41781.606175,41368.592735,40979.504566,40582.758386,42480.683323,60919.989862,60051.320540,64329.159938,71226.202984,70523.307872,68338.535050,64484.562570,62096.311754,42478.833321,45147.349524,46266.417899,53107.801128,58482.812631,68823.169427,67591.801046,66346.746614,62307.566632,42478.833321,43439.424836,44945.034850,50237.913795,56494.031176,71629.051211,69277.248042,69844.068813,69122.745366,42482.063870,43466.887183,44412.303915,48068.451947,49423.183397,52755.428798,59599.495841,58963.638802,59084.302900,42482.063870,44617.67796,45383.029711,46425.598562,48276.710606,49635.715079,50155.823697,50505.874107,50740.958452,3422.558924,2.052052e+06
1,17448,8121379,375401000,GYGEO,328,GUY,GY,Guyana,Georgetown,BBBGI,052,BRB,BB,Barbados,Bridgetown,2018-03-11 13:00:00,2018-03-15 22:00:00,105.0,13.0,118.0,397.574666,3.978470,0.000412,3.978882,6.4855,1.0897,7.5752,0.0,0.0,0.0,0.0,0.0,0.0,0.436865,0.046547,33.181468,3.494862,36.676329,019,Americas,419,Latin America and the Caribbean,high_income,0,1,019,Americas,419,Latin America and the Caribbean,high_income,0,1,0.483412,General cargo,3222.0,dwt,5350.0,146.0,NaN,NaN,NaN,2,5000-9999,1983.0,St Vincent & The Grenadines,MSD,1,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.02233,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.01858,0.018382,0.01842,0.013244,0.01391,0.014148,0.014473,0.01505,0.015474,0.015636,0.015745,0.015819,2.127024e+06,28172.325405,28844.392701,28526.486051,28247.666267,27974.012075,27705.523384,27431.652785,27173.647113,26910.563389,28169.083789,40396.249886,39820.232341,42656.882013,47230.334422,46764.242312,45315.512116,42759.930021,41176.272883,28167.857046,29937.359103,30679.417101,35215.961298,38780.149479,45636.874800,44820.350290,43994.750515,41316.356702,28167.857046,28804.828506,29803.203563,33312.929369,37461.381816,47497.464434,45937.975854,46313.836611,45835.524611,28169.999234,28823.038881,29449.947891,31874.351931,32772.678905,34982.302022,39520.625865,39098.986927,39178.999696,28169.999234,29586.13211,30093.639426,30784.970333,32012.448947,32913.609378,33258.495149,33490.614751,33646.499970,3422.558924,1.360723e+06

## 3.3 Evaluate NZF Costs

In [11]:
years=["26", "29", "32", "35", "38", "41", "44", "47", "50"]
vess_types_not_found_in_inventories, vess_types_not_found_in_global_voys, hs_codes_not_mapped_to_HS, cost_int_match_desc, cost_int_match_desc_bool = [], [], [], [], False

for year in years:

    print("Processing game year 20{0}".format(year))

    # Setup columns for policy costs per bilateral goods trade.
    bau_usd, levy_usd, asis_usd, brazil_usd, liscr_usd, direct_usd = [], [], [], [], [], []
    
    for trade_idx, trade in trade_ex.iterrows():

        # initiate selected voyages table as empty dataframe to begin
        int_dep_voys_vess = pd.DataFrame()

        # 3. If no facilitating vessel types were picked up for the HS code, take from full primary int. inv. voyages dataset, otherwise move on...
        if 'all' in trade.fac_vessel_types:
            hs_codes_not_mapped_to_HS.append(trade.HS4_desc)
            int_dep_voys_vess = int_dep_voys
            cost_int_match_desc.append("3. Primary Int. Inv. without Vess Type") if cost_int_match_desc_bool == False else None

        else:
            # 1. If possible, derive subset of voyages associated with the unique vessel type.
            int_dep_voys_vess = int_dep_voys[(int_dep_voys.vessel_type.isin(trade.fac_vessel_types))]    
            
            if int_dep_voys_vess.shape[0] > 0:
                cost_int_match_desc.append("1. Primary Int. Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                
            else:
                # 2. Finally, if no voyages are found as the vessel type doesn't appear in the country's shipping inventories, also take from full voyages dataset filtered for those vessel types instead.
                int_dep_voys_vess = voys_fem[(voys_fem.vessel_type.isin(trade.fac_vessel_types))]
                
                if int_dep_voys_vess.shape[0] > 0:
                    cost_int_match_desc.append("2. Global Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_inventories.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

                else:
                    # 4. Use full global voyage dataset as a back-up
                    int_dep_voys_vess = voys_fem
                    cost_int_match_desc.append("4. Global Inv. without Vess Type.") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_global_voys.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]
    
        # Add cost intensities associated with the subset of voyages by vessel type, assuming 50% of NZF costs are borne by the exporter.
        bau_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "bau35_usd_dwtnm_"+year))
        levy_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "levy35_usd_dwtnm_"+year))
        asis_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "asis35_usd_dwtnm_"+year))
        brazil_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "brazil35_usd_dwtnm_"+year))
        liscr_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "liscr35_usd_dwtnm_"+year))
        direct_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "direct35_usd_dwtnm_"+year))

    if cost_int_match_desc_bool == False:
        trade_ex["cost_int_match_desc"] = cost_int_match_desc
    cost_int_match_desc_bool = True

    trade_ex["bau_usd_"+year] = bau_usd
    trade_ex["levy_usd_"+year] = levy_usd
    trade_ex["asis_usd_"+year] = asis_usd
    trade_ex["brazil_usd_"+year] = brazil_usd
    trade_ex["liscr_usd_"+year] = liscr_usd
    trade_ex["direct_usd_"+year] = direct_usd
    
print("Inventory voyages table used for the following vessel types: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_inventories).unique()))
print("Global voyages table used for the following vessel types found: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_global_voys).unique()))
print("Global voyages table used for the following commodities as no 'facilitating vessel types' were identified: \n\n{0}\n".format(pd.Series(hs_codes_not_mapped_to_HS).unique()))

print()
print("Number of trade records present in dataset: {0}".format(trade_ex.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_ex.partnerCode.unique())))
print("\nTotal value of trade: US${0}m".format(np.round(trade_ex.fobvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_ex.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_ex.sea_dist_nm.min(), 1),
    round(trade_ex.sea_dist_nm.max(), 1),
    round(trade_ex.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_ex.vol_kg_vtw / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_ex.fobvalue / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.fobvalue.sum() / 1000), 1)
))

print("\n\nTotal FEM costs in 2041...\n")
print("BAU: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.bau_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.bau_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Levy: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.levy_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.levy_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("'as-is': US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.asis_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.asis_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Brazil: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.brazil_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.brazil_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("LISCR: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.liscr_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.liscr_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Direct: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.direct_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.direct_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))

trade_ex_agg = trade_ex.groupby(["cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "fobvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_ex_agg["vol_kg_vtw_pct"] = round(100 * trade_ex_agg.vol_kg_vtw / trade_ex_agg.vol_kg_vtw.sum(), 1)
trade_ex_agg["fobvalue_pct"] = round(100 * trade_ex_agg.fobvalue / trade_ex_agg.fobvalue.sum(), 1)
print("Most prominent 'cost intensity match' types...\n\n{0}\n".format(
    trade_ex_agg[["cost_int_match_desc", "vol_kg_vtw_pct", "fobvalue_pct"]].head(5)
))
trade_ex_agg_2 = trade_ex.groupby(["fac_vessel_types_str", "cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "fobvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_ex_agg_2["vol_kg_vtw_pct"] = round(100 * trade_ex_agg_2.vol_kg_vtw / trade_ex_agg_2.vol_kg_vtw.sum(), 1)
trade_ex_agg_2["fobvalue_pct"] = round(100 * trade_ex_agg_2.fobvalue / trade_ex_agg_2.fobvalue.sum(), 1)
print("Most prominent 'facilitating vessel types' and their 'cost intensity match' types...")
display(trade_ex_agg_2[["fac_vessel_types_str", "cost_int_match_desc", "vol_kg_vtw_pct", "fobvalue_pct"]].head(5))

trade_ex_na = trade_ex[(trade_ex[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (trade_ex.fac_vessel_types.str.len() == 0)]
trade_ex = trade_ex[(~trade_ex[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (~trade_ex.fac_vessel_types.str.len() == 0)]
print("Rows with NA: ${0} ({1}%)\n".format(trade_ex_na.primaryValue.sum(), round(100 * trade_ex_na.primaryValue.sum() / trade_ex.primaryValue.sum(), 1)))

trade_ex.to_csv(output_dir + "{0}/impact_ex_{1}.csv".format(iso_country, version), index=False)
trade_ex.head(2)

Processing game year 2026
Processing game year 2029
Processing game year 2032
Processing game year 2035
Processing game year 2038
Processing game year 2041
Processing game year 2044
Processing game year 2047
Processing game year 2050
Inventory voyages table used for the following vessel types:

['Oil tanker']

Global voyages table used for the following vessel types found:

[]

Global voyages table used for the following commodities as no 'facilitating vessel types' were identified:

['4420 | Wood marquetry and i' '9508 | Travelling circuses '
 '2844 | Radioactive chemical' '1905 | Bread, pastry, cakes'
 '9405 | Luminaires and light' '9701 | Paintings, drawings '
 '9703 | Sculptures and statu' '5703 | Carpets and other te'
 '4412 | Plywood, veneered pa' '2202 | Waters, including mi'
 '6406 | Footwear; parts of f' '1704 | Sugar confectionery '
 '2009 | Fruit or nut juices ' '4419 | Tableware and kitche'
 "4418 | Builders' joinery an" '4414 | Wooden frames; for p'
 '6201 | Overcoats, car-coats' '4011 | New pneumatic tyres,'
 '4406 | Railway or tramway s' '9401 | Seats (not those of '
 '3824 | Prepared binders for' '3926 | Articles of plastics'
 '7616 | Aluminium; articles ' '0910 | Ginger, saffron, tum'
 '2106 | Food preparations no' '5911 | Textile products and'
 '7326 | Iron or steel; artic' '0306 | Crustaceans; in shel'
 '4911 | Printed matter, n.e.' '0604 | Foliage, branches an'
 '8215 | Cutlery; spoons, for' '4707 | Waste and scrap of p'
 '0714 | Manioc, arrowroot, s' '3402 | Organic surface-acti'
 '6310 | Rags; used or new, s' '0302 | Fish; fresh or chill'
 '8311 | Wires, rods, tubes, ' '0307 | Molluscs; whether in'
 '4823 | Paper, paperboard, c' '7019 | Glass fibres (includ'
 '3006 | Pharmaceutical goods' '6914 | Ceramic articles; n.'
 '9406 | Buildings; prefabric' '0303 | Fish; frozen, exclud'
 '0802 | Nuts (excluding coco' '6304 | Furnishing articles;'
 '9620 | Monopods, bipods, tr' '7419 | Copper; articles the'
 '4905 | Maps and hydrographi']


Number of trade records present in dataset: 1967
Number of partner countries present in dataset: 78

Total value of trade: US$17897.5m
Total weight within the dataset: 39456.1 million kilograms

Distance to market: 251.0 nm (min) to 13534.1 nm (max), 2733.5 nm (observed mean)
Average distance to market (volume-weighted): 4667.2 nm
Average distance to market (value-weighted): 4569.9 nm


Total FEM costs in 2041...

BAU: US$412.2m (2.3% ad-val)
Levy: US$894.9m (5.0% ad-val)
'as-is': US$824.5m (4.6% ad-val)
Brazil: US$850.5m (4.8% ad-val)
LISCR: US$566.5m (3.2% ad-val)
Direct: US$537.6m (3.0% ad-val)
Most prominent 'cost intensity match' types...

                      cost_int_match_desc  vol_kg_vtw_pct  fobvalue_pct
0           2. Global Inv. with Vess Type            90.5          96.5
1     1. Primary Int. Inv. with Vess Type             9.5           3.5
2  3. Primary Int. Inv. without Vess Type             0.0           0.0

Most prominent 'facilitating vessel types' and their 'cost intensity match' types...

,fac_vessel_types_str,cost_int_match_desc,vol_kg_vtw_pct,fobvalue_pct
0,['Oil tanker'],2. Global Inv. with Vess Type,90.5,96.5
1,['Bulk carrier'],1. Primary Int. Inv. with Vess Type,8.3,1.3
2,['Container'],1. Primary Int. Inv. with Vess Type,1.1,1.4
3,"['Container', 'Bulk carrier']",1. Primary Int. Inv. with Vess Type,0.1,0.1
4,['Chemical tanker'],1. Primary Int. Inv. with Vess Type,0.0,0.0

Rows with NA: $0.0 (0.0%)

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_ex_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,cost_int_match_desc,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50
0,0,328,Guyana,276,Germany,000,World,Domestic Export,Sea,442010 | Wood; statuettes and,442010,NaN,0.0,NaN,NaN,16.000,16.000,Germany | 442010 | Wood; statuettes and,44,44 | Wood and articles of,Germany | 44 | Wood and articles of,4420,4420 | Wood marquetry and i,Germany | 4420 | Wood marquetry and i,44,4420,442010,"Statuettes & other ornaments, of wood",Wood and Paper,2029,Manufacture of other products of wood; manufac...,63549,Wood marquetry & inlaid wood; caskets & cases ...,30,LUM - Wood products,31913,Wood marquetry and inlaid wood; cases for jewe...,6.5147,0.1535,both,NaN,2.456000,NaN,[all],['all'],6594.0,4097.320374,10.063019,3. Primary Int. Inv. without Vess Type,0.059715,0.059651,0.059656,0.059656,0.059685,0.059685,0.061783,0.097978,0.065826,0.062307,0.062367,0.064125,0.060805,0.095415,0.068340,0.064656,0.063564,0.065668,0.059947,0.103755,0.081719,0.074486,0.070181,0.067784,0.059105,0.112353,0.092148,0.087627,0.073468,0.071553,0.058279,0.113781,0.108901,0.111813,0.079310,0.074350,0.057436,0.109437,0.106177,0.113069,0.090453,0.075402,0.056642,0.100545,0.103946,0.110050,0.087695,0.076092,0.055833,0.094576,0.095625,0.112131,0.094025,0.076508
1,1,328,Guyana,710,South Africa,000,World,Domestic Export,Sea,"401039 | Rubber; vulcanised,",401039,NaN,0.0,NaN,NaN,7.002,7.002,"South Africa | 401039 | Rubber; vulcanised,",40,40 | Rubber and articles,South Africa | 40 | Rubber and articles,4010,4010 | Conveyor or transmis,South Africa | 4010 | Conveyor or transmis,40,4010,401039,Transmission belts/belting (excl. of 4010.31-4...,"Petroleum, Chemical and Non-Metallic Mineral P...",2519,Manufacture of other rubber products,62921,Transmission belts/belting,33,"CRP - Chemical, rubber, plastic products",3624,"Conveyor or transmission belts or belting, of ...",7.9828,0.1253,both,NaN,0.877351,NaN,[Container],['Container'],10569.0,6567.270099,5.761798,1. Primary Int. Inv. with Vess Type,0.030116,0.030063,0.030068,0.030068,0.030092,0.030092,0.031503,0.055833,0.034749,0.032261,0.032348,0.033159,0.030847,0.054680,0.036575,0.033502,0.032733,0.034216,0.030271,0.059460,0.045355,0.039666,0.036698,0.035663,0.029707,0.063221,0.052024,0.048751,0.039290,0.038222,0.029153,0.064066,0.061209,0.061735,0.042595,0.040151,0.028587,0.062749,0.060133,0.065884,0.048734,0.040887,0.028055,0.055974,0.058339,0.061134,0.045828,0.041370,0.027512,0.051416,0.052266,0.065195,0.053860,0.041644

## 3.4 Create Results Tables

### 3.4.1 Total Costs per Scenario

In [12]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        np.round(trade_ex["bau_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["levy_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["asis_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["brazil_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["liscr_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["direct_usd_{0}".format(year)].sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% cif)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
    display(df)

    
print("\nTotal FEM costs by scenario (% fob)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_fob_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / gdp, 3)
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,BAU,4.391316e+08,4.325271e+08,4.256489e+08,4.190244e+08,4.121705e+08,4.053788e+08,3.990821e+08,3.926615e+08
1,Levy,7.095059e+08,7.038487e+08,7.728527e+08,8.461434e+08,8.948866e+08,8.015609e+08,7.534241e+08,6.783854e+08
2,'as-is',4.663462e+08,4.962362e+08,5.845988e+08,6.811258e+08,8.245098e+08,7.841497e+08,7.567127e+08,6.893135e+08
3,Brazil,4.409887e+08,4.597491e+08,5.363130e+08,6.422086e+08,8.504845e+08,8.374206e+08,8.414575e+08,7.812870e+08
4,LISCR,4.425480e+08,4.527356e+08,5.032247e+08,5.245322e+08,5.665228e+08,6.706580e+08,6.688232e+08,6.775917e+08
5,Direct,4.559956e+08,4.687923e+08,4.851275e+08,5.141437e+08,5.376467e+08,5.459826e+08,5.509781e+08,5.542093e+08

Total FEM costs by scenario (% fob)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0      BAU  2.45  2.42  2.38  2.34  2.30  2.27  2.23  2.19
1     Levy  3.96  3.93  4.32  4.73  5.00  4.48  4.21  3.79
2  'as-is'  2.61  2.77  3.27  3.81  4.61  4.38  4.23  3.85
3   Brazil  2.46  2.57  3.00  3.59  4.75  4.68  4.70  4.37
4    LISCR  2.47  2.53  2.81  2.93  3.17  3.75  3.74  3.79
5   Direct  2.55  2.62  2.71  2.87  3.00  3.05  3.08  3.10

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  1.620  1.596  1.571  1.546  1.521  1.496  1.473  1.449
1     Levy  2.618  2.597  2.852  3.122  3.302  2.958  2.780  2.503
2  'as-is'  1.721  1.831  2.157  2.513  3.042  2.894  2.792  2.544
3   Brazil  1.627  1.696  1.979  2.370  3.138  3.090  3.105  2.883
4    LISCR  1.633  1.671  1.857  1.936  2.090  2.475  2.468  2.500
5   Direct  1.683  1.730  1.790  1.897  1.984  2.015  2.033  2.045

### 3.4.2 Costs per Scenario relative to BAU

In [13]:
print("\nTotal FEM costs by scenario (US$)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:

    d_temp = {"20{0}".format(year): [
        np.round((trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_usd_bau_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal change in FEM costs by scenario (% bau)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        round((100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_bau_{1}.csv".format(iso_country, version), index=False)
display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% cif)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_cif_{1}.csv".format(iso_country, version), index=False)
    display(df)


print("\nTotal FEM costs by scenario (% fob)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_fob_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,Levy,2.703743e+08,2.713216e+08,3.472038e+08,4.271191e+08,4.827161e+08,3.961821e+08,3.543420e+08,2.857239e+08
1,'as-is',2.721455e+07,6.370902e+07,1.589499e+08,2.621014e+08,4.123393e+08,3.787709e+08,3.576306e+08,2.966521e+08
2,Brazil,1.857064e+06,2.722195e+07,1.106641e+08,2.231843e+08,4.383140e+08,4.320418e+08,4.423753e+08,3.886255e+08
3,LISCR,3.416375e+06,2.020850e+07,7.757579e+07,1.055079e+08,1.543522e+08,2.652792e+08,2.697411e+08,2.849302e+08
4,Direct,1.686401e+07,3.626521e+07,5.947857e+07,9.511934e+07,1.254762e+08,1.406037e+08,1.518960e+08,1.615479e+08

Total change in FEM costs by scenario (% bau)...

  Scenario   2029   2032   2035    2038    2041    2044    2047   2050
0     Levy  61.57  62.73  81.57  101.93  117.12   97.73   88.79  72.77
1  'as-is'   6.20  14.73  37.34   62.55  100.04   93.44   89.61  75.55
2   Brazil   0.42   6.29  26.00   53.26  106.34  106.58  110.85  98.97
3    LISCR   0.78   4.67  18.23   25.18   37.45   65.44   67.59  72.56
4   Direct   3.84   8.38  13.97   22.70   30.44   34.68   38.06  41.14

Total FEM costs by scenario (% fob)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0     Levy  1.51  1.52  1.94  2.39  2.70  2.21  1.98  1.60
1  'as-is'  0.15  0.36  0.89  1.46  2.30  2.12  2.00  1.66
2   Brazil  0.01  0.15  0.62  1.25  2.45  2.41  2.47  2.17
3    LISCR  0.02  0.11  0.43  0.59  0.86  1.48  1.51  1.59
4   Direct  0.09  0.20  0.33  0.53  0.70  0.79  0.85  0.90

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  0.998  1.001  1.281  1.576  1.781  1.462  1.308  1.054
1  'as-is'  0.100  0.235  0.587  0.967  1.522  1.398  1.320  1.095
2   Brazil  0.007  0.100  0.408  0.824  1.617  1.594  1.632  1.434
3    LISCR  0.013  0.075  0.286  0.389  0.570  0.979  0.995  1.051
4   Direct  0.062  0.134  0.219  0.351  0.463  0.519  0.561  0.596