<h2>Impact (v0.64) - 'Impact (v0.64).ipynb'</h2>

<u><h4>Context</h4></u>

The aim of the 'Impact' notebooks are to explore economic impacts resulsting from the FEM outputs in the lead-up to Autumn 2026, taking foward outputs from the associated 'Trade' notebooks.

<u><h4>Version Documentation and Future Work</h4></u>

'v0.2' cleaned up the analysis code by introducing the cost intensity estimation functions that were previously in the 'inventories' notebooks. For example, the 'get_usd_per_tnm' function is included here and applied to voyages identified as relevant to each individual trade record. The NZF costs associated with each trade record are now evaluated like this. 'v0.3' introduced the exporter- and importer-side trade portfolios at an HS-digit 4 level of resolution. With this implemented, the matching algorithm is now be being evaluated using the cargo weight field rather than value, and the process will be being conducted at the HS-digit 4 level of resolution. Since we are now confident regarding the use of the Global Shipping Watch dataset for the purposes of matching HS codes with facilitating vessel types, we should then be in good shape to take the analysis forward using the results produced in this notebook. 'v0.3' also subsumed the 'inventories' notebooks. In 'v0.4' sought to include transport costs data from UNCTAD's Trade-and-Transport database. However, there are now concerns regarding this dataset as it is importer-side only, and therefore has odd looking exporter-side portfolios. Instead, it makes sense for us to utilise trade portfolios derived from UN Comtrade, where these are submitted with disaggregation by Transport Mode. Looking at the 16 countries of interest across African and Caribbean economies we're interested in the summer of 2026, 13 of these have a trade portfolio with MoT Breakdown available across at least one year within the last decade. Therefore this approach makes more sense, and 'v0.6' was amended to work with Comtrade import and export trade portfolios downloaded from the platform. 'v0.61' made use of the updated 'trade' notebooks that derive a new weight field using Value-to-Weight and Weight-to-Value ratios observed in the CEPII BACI datasets across 2017-23. In the case of Trinidad and Tobaogo, import volumes were around 65% higher under the WtV approach which corresponded to a 39% greater 2041 BAU impact from FEM costs, but this was slightly less for exports where the weighted WtV was 9% more but 2041 FEM costs under BAU were around 10% less. A new 'composite' weight field has been added in Trade (v0.61) which only introduces the VtW-derived values where 'netWgt' is observed to be zero, however this resulted in only a tiny increase in recorded weight of around 1% for Angola, whereas the full VtW-derived field was ~50% greater. 

'v0.62' makes use of a new 'transport cost' field derived using ad-valorem transport cost rates identified from UNCTAD's Trade-and-Transport database. With these, we can now introduce another results disaggregation that presents NZF costs relative to expected transport costs, which is then fully in-line with how impacts are expressed in UNCTAD's CIA Task 3 work. 'v0.63' includes an assessment of 'Cost Intensity' matching process (similar to CIF-FOB matching), plus metrics on 'fac_vessel_types' and 'average sea-distance' (introduced in Trade v0.63). 'v0.64' has been modified throughout to account for a new scenario, namely the 'Japan' proposal, plus to remove the 'Low-then-High' scenario. In terms of the Impact notebook, this remains the same as 'v0.63'.

In [1]:
# Import packages
import os
import ast
import base64
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 250)
pd.set_option('display.max_rows', 250)
pd.options.mode.chained_assignment = None
from IPython.display import HTML
import matplotlib.pyplot as plt
import matplotlib.style
plt.style.use('seaborn-v0_8')

def voyages_analysis(voys):
    # Define a function to analyses key statistics from a given set of voyages, 'voys'.
    print("Number of Voyages found: {0}".format(voys.shape[0]))
    print("Total size of the fleet: {0} vessels".format(len(voys.imo.unique())))
    print("{0} vessel types contained in the dataset: {1}".format(len(voys.vessel_type.unique()), voys.vessel_type.unique()))
    print("Total transport work capacity: {0} million deadweight-tonne nautical miles".format(np.round(voys.dwtnm.sum() / 1e6, 1)))
    print("Total cargo transported: {0} tonnes".format(np.round(voys.tonnes.sum(), 1)))
    print("Total transport work: {0} million tonne nautical miles".format(np.round(voys.tnm.sum() / 1e6, 1)))
    print("Average build year of the fleet: {0}".format(int(np.round(voys.year_of_built.mean(), 0))))
    print("Total Energy Demands: {0} EJ".format(np.round(voys.energy_tj.sum(), 1)))
    print("Total CO2 produced: {0} tonnes".format(np.round(voys.co2_t.sum(), 1)))

def get_usd_per_dwtnm(voys, field_name):
    # Derive the deadweight-average of the cost intensity (per unit of cargo-carrying capacity) for the field 'field_name' in an input selection of voyages, 'voys'.
    return (voys[field_name].values * voys.deadweight.values).sum() / voys.deadweight.sum()
    
def get_usd_per_tnm(voys, field_name):
    # Derive the deadweight-average of the cost intensity (per unit of cargo-carried) for the field 'field_name' in an input selection of voyages, 'voys'.
    return (voys[field_name].values / voys.class_util.values * voys.tonnes.values).sum() / voys.tonnes.sum()

def download_link(df, title = "Download CSV file", filename = "data.csv"):
    csv = df.to_csv()
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
    html = html.format(payload=payload,title=title,filename=filename)
    return HTML(html)

version = "v0.64"
input_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/"
voys_fem_dir = "/Users/apple/repos/datasets/ucl/fleet evolution model/2026 annex vi amendments (v0.2)/2. NZF Impact Costs for 2018 IMO IV Voyages/voys_fem_v0.2.csv"
output_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/impact/"
res_mlc = False

# 1. Set up the notebook

## 1.1 Let's set the country we're interested in and set up a results folder.

In [2]:
# Select one of our countries to work on...
iso_code = "360"
iso_country = "Indonesia"
year = 2025
import_portfolio = "h6_ag6_by_sea_M.csv" # Imports, '_M' | Foreign Imports, '_FM' | Re-Imports, '_RM'
export_portfolio = "h6_ag6_by_sea_X.csv" # Exports, '_X' | Domestic Exports, '_DX' | Re-exports, '_RX'
gdp = 1.450*1e12

# Create output Journey directory folder if necessary
os.makedirs(output_dir+"{0}/".format(iso_country)) if not os.path.exists(output_dir+"{0}/".format(iso_country)) else "Output directory already exists."
os.makedirs(output_dir+"{0}/results/".format(iso_country)) if not os.path.exists(output_dir+"{0}/results/".format(iso_country)) else "Output results folder already exists."

## 1.2 Voyages with FEM Results

In [3]:
voys_fem_d = {
    "source_iso":str, "source_iso_code":str, "source_iso_3":str, "source_iso_2":str, 
    "dest_iso_code":str, "dest_iso_code":str, "dest_iso_3":str, "dest_iso_2":str, 
    "source_region_code":str, "source_sub_region_code":str, "dest_region_code":str, "dest_sub_region_code":str, 
    "source_ldc":str, "source_sids":str, "dest_ldc":str, "dest_sids":str
}

voys_fem = pd.read_csv(voys_fem_dir, dtype=voys_fem_d)
voys_fem["dwtnm"] = voys_fem.deadweight * voys_fem.dist_travelled_ais
voys_fem["tonnes"] = voys_fem.deadweight * voys_fem.class_util
voys_fem["tnm"] = voys_fem.tonnes * voys_fem.dist_travelled_ais
voys_fem.loc[voys_fem.source_country == "Namibia", "source_iso_2"] = "NA"
voys_fem.loc[voys_fem.dest_country == "Namibia", "dest_iso_2"] = "NA"

countries_set = pd.Series(list(set(list(voys_fem.source_country.unique()) + list(voys_fem.dest_country.unique())))).sort_values()
print("Number of countries present in dataset: {0}.".format(len(countries_set)))
print("Number of IMO numbers present in dataset: {0}.".format(len(voys_fem.imo.unique())))
print("Total CO2 contained within the dataset: {0} million tonnes.".format(np.round(voys_fem.co2_t.sum() / 1e6, 1)))
print("Vessel types present in dataset: \n\n{0}\n".format(pd.Series(voys_fem.vessel_type.unique()).sort_values().values))
#print("\nCountries in dataset: \n\n", countries_set.values, "\n")
voys_fem.head(2)

Number of countries present in dataset: 207.
Number of IMO numbers present in dataset: 26132.
Total CO2 contained within the dataset: 544.7 million tonnes.
Vessel types present in dataset:

['Bulk carrier' 'Chemical tanker' 'Container' 'General cargo'
 'Liquefied gas tanker' 'Oil tanker' 'Refrigerated bulk' 'Vehicle']

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,0,5034525,413781699,CNTAX,156,CHN,CN,China,Taixing,CNNKG,156,CHN,CN,China,Nanjing,2018-01-01 06:00:00,2018-01-01 19:00:00,13.0,1.0,14.0,62.568523,0.0,0.0,0.0,3.635661,0.338483,3.974144,0.0,0.0,0.0,0.0,0.0,0.0,0.155243,0.014453,11.655930,1.085176,12.741107,142,Asia,030,Eastern Asia,upp_mid_income,0,0,142,Asia,030,Eastern Asia,upp_mid_income,0,0,0.169696,Refrigerated bulk,3786.0,dwt,3881.0,NaN,NaN,NaN,NaN,2,2000-5999,1959.0,Panama,SSD,4,76.1,0.666667,0.03155,0.032676,0.032143,0.031676,0.031218,0.030769,0.03031,0.029878,0.029438,0.031576,0.052178,0.052414,0.05804,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.05942,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,242828.439338,7661.320668,7934.549945,7805.304846,7691.950531,7580.696290,7471.542086,7360.199865,7255.307537,7148.350725,7667.458038,12670.391275,12727.642802,14093.647297,14570.027623,14398.931835,14189.590704,14139.488873,14161.462401,7665.715352,8412.516422,8946.627490,10860.650719,12049.492896,13084.201484,14034.766615,14342.763237,14083.751009,7665.715352,7946.962662,8384.668998,9891.651071,11698.979626,13565.379532,13949.851660,14247.178318,14428.769963,7663.482493,7940.155892,8209.623358,9221.805242,9744.436151,10159.112402,10518.004352,10853.785659,11140.079340,7663.482493,8252.567981,8473.856677,8773.523328,9299.485535,9694.695953,9860.244395,9979.919640,10068.487874,2587.333335,161885.626306
1,1,5034525,413781699,CNNKG,156,CHN,CN,China,Nanjing,CNTOL,156,CHN,CN,China,Tongling,2018-01-01 20:00:00,2018-01-04 17:00:00,69.0,59.0,128.0,134.252308,0.0,0.0,0.0,21.355373,19.491146,40.846519,0.0,0.0,0.0,0.0,0.0,0.0,0.911874,0.832272,68.465325,62.488615,130.953940,142,Asia,030,Eastern Asia,upp_mid_income,0,0,142,Asia,030,Eastern Asia,upp_mid_income,0,0,1.744146,Refrigerated bulk,3786.0,dwt,3881.0,NaN,NaN,NaN,NaN,2,2000-5999,1959.0,Panama,SSD,4,76.1,0.666667,0.03155,0.032676,0.032143,0.031676,0.031218,0.030769,0.03031,0.029878,0.029438,0.031576,0.052178,0.052414,0.05804,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.05942,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,521033.206847,16438.776642,17025.040451,16747.721252,16504.498662,16265.782167,16031.571689,15792.666415,15567.600579,15338.105010,16451.945500,27186.661563,27309.505274,30240.519881,31262.681739,30895.564166,30446.384156,30338.881438,30386.029694,16448.206246,18050.605691,19196.639505,23303.529390,25854.409564,28074.567693,30114.180516,30775.044079,30219.285570,16448.206246,17051.674227,17990.853906,21224.361910,25102.318690,29107.023950,29931.979818,30569.949005,30959.587375,16443.415234,17037.069045,17615.261197,19787.084130,20908.485145,21798.249530,22568.318408,23288.799137,23903.095037,16443.415234,17707.406809,18182.222523,18825.212595,19953.761526,20801.758375,21156.973093,21413.758406,21603.797889,2587.333335,347355.471405

# 2. Let's consider Imports

## 2.1 Read-in Trade dataset

In [4]:
trade_im_d = {
    "reporterCode":"str", "partnerCode":"str", "partner2Code":"str", 
    "cmdCode":"str", "HS2":"str", "HS4":"str", "hs2":"str", "hs4":"str", "hs6":"str",
    "isic":"str", "sitc":"str", "gtap":"str", "cpc":"str"
}
if res_mlc == False:
    trade_im = pd.read_csv(input_dir+"trade/{0}/trade_im_dist_{1}.csv".format(iso_country, version), dtype=trade_im_d)
else:
    trade_im = pd.read_csv(input_dir+"trade/{0}/trade_im_mlc_{1}.csv".format(iso_country, version), dtype=trade_im_d)
trade_im['fac_vessel_types'] = [ast.literal_eval(x) for x in trade_im.fac_vessel_types.values]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(trade_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_im.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(trade_im.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(trade_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_im.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_im.sea_dist_nm.min(), 1),
    round(trade_im.sea_dist_nm.max(), 1),
    round(trade_im.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_im.vol_kg_vtw / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_im.cifvalue / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.cifvalue.sum() / 1000), 1)
))
trade_im.head(2)

Aggregate trade portfolio statistics for 'Indonesia':

Number of trade records present in dataset: 55209
Number of partner countries present in dataset: 194
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$205875.0m
Total weight within the dataset: 231071.1 million kilograms

Distance to market: 645.0 nm (min) to 13150.7 nm (max), 5517.5 nm (observed mean)
Average distance to market (volume-weighted): 4716.0 nm
Average distance to market (value-weighted): 3946.1 nm

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_im_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm
0,0,360,Indonesia,699,India,000,World,Import,Sea,847751 | Machinery; for mould,847751,NaN,0.0,NaN,854.000,NaN,854.000,India | 847751 | Machinery; for mould,84,84 | Machinery and mechan,India | 84 | Machinery and mechan,8477,8477 | Machinery; for worki,India | 8477 | Machinery; for worki,84,8477,847751,Machinery for moulding/retreading pneumatic ty...,Electrical and Machinery,2929,Manufacture of other special purpose machinery,72842,Machinery for working rubber/plastics/for the ...,41,OME - Machinery and equipment n.e.c.,44915,Machinery n.e.c. for working rubber or plastic...,15.0714,0.0664,both,NaN,56.705600,NaN,"[Container, Vehicle]","['Container', 'Vehicle']",5100.0,3168.992100,179.699598
1,1,360,Indonesia,040,Austria,000,World,Import,Sea,340540 | Scouring pastes and,340540,NaN,0.0,NaN,226.541,NaN,226.541,Austria | 340540 | Scouring pastes and,34,"34 | Soap, organic surfac","Austria | 34 | Soap, organic surfac",3405,"3405 | Polishes, creams, sc","Austria | 3405 | Polishes, creams, sc",34,3405,340540,Scouring pastes & powders & other scouring pre...,"Petroleum, Chemical and Non-Metallic Mineral P...",2424,"Manufacture of soap and detergents, cleaning a...",55434,Scouring pastes & powders & other scouring pre...,33,"CRP - Chemical, rubber, plastic products",35334,Scouring pastes and powders and other scouring...,3.8817,0.2576,both,NaN,58.356962,NaN,[Container],['Container'],11576.0,7192.990696,419.761082

## 2.2 Derive Internationally Arriving Voyages

In [5]:
# International Arrivals
int_arr_voys = voys_fem[(voys_fem.dest_country == iso_country) & (voys_fem.source_country != iso_country)].reset_index(drop=True)
int_arr_voys.to_csv(output_dir + "{0}/int_arr_voys_{1}.csv".format(iso_country, version), index=False)
int_dep_voys = voys_fem[(voys_fem.source_country == iso_country) & (voys_fem.dest_country != iso_country)].reset_index(drop=True)
int_dep_voys.to_csv(output_dir + "{0}/int_dep_voys_{1}.csv".format(iso_country, version), index=False)
voyages_analysis(int_arr_voys)
int_arr_voys.head(2)

Number of Voyages found: 17535
Total size of the fleet: 7650 vessels
8 vessel types contained in the dataset: ['General cargo' 'Liquefied gas tanker' 'Bulk carrier' 'Refrigerated bulk'
 'Container' 'Chemical tanker' 'Oil tanker' 'Vehicle']
Total transport work capacity: 3549483.1 million deadweight-tonne nautical miles
Total cargo transported: 613806536.8 tonnes
Total transport work: 1816289.2 million tonne nautical miles
Average build year of the fleet: 2008
Total Energy Demands: 162056.3 EJ
Total CO2 produced: 12416436.6 tonnes

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,5480,7384285,273420050,RUVVO,643,RUS,RU,Russian Federation,Vladivostok,IDPSS,360,IDN,ID,Indonesia,Pulau Sambu,2018-11-03 04:00:00,2018-12-07 05:00:00,817.0,3.0,820.0,1564.300170,0.0000,0.000,0.0000,66.423855,0.1875,66.611355,0.00000,0.000000,0.000000,0.0,0.0,0.0,2.836299,0.008006,212.954879,0.601126,213.556005,150,Europe,151,Eastern Europe,upp_mid_income,0,0,142,Asia,035,South-eastern Asia,upp_mid_income,0,0,2.844305,General cargo,4120.0,dwt,5599.0,119.0,NaN,NaN,NaN,2,5000-9999,1975.0,Faeroe Islands,MSD,4,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.022330,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.018580,0.018382,0.018420,0.013244,0.013910,0.014148,0.014473,0.015050,0.015474,0.015636,0.015745,0.015819,8.758517e+06,116006.085274,118773.478271,117464.423889,116316.318751,115189.484132,114083.919661,112956.193936,111893.795732,110810.487467,115992.737167,1.663409e+05,1.639690e+05,1.756496e+05,1.944819e+05,1.925626e+05,1.865971e+05,1.760739e+05,1.695529e+05,115987.685767,123274.020975,126329.616926,145009.890045,1.596863e+05,1.879204e+05,1.845582e+05,1.811586e+05,1.701297e+05,115987.685767,118610.563520,122721.604420,137173.714610,154255.929919,1.955818e+05,1.891603e+05,1.907080e+05,1.887384e+05,115996.506723,118685.548960,121266.992240,131250.038288,134949.107999,144047.743773,1.627353e+05,1.609991e+05,161328.619994,115996.506723,121827.762355,123917.541462,126764.256846,131818.684787,135529.421912,136949.569082,137905.375393,138547.268943,3581.851853,5.603091e+06
1,5524,7390181,525001084,SGTUA,702,SGP,SG,Singapore,Tuas,IDBXT,360,IDN,ID,Indonesia,Bontang,2018-10-29 02:00:00,2018-11-04 17:00:00,159.0,84.0,243.0,1761.922968,106.7385,46.368,153.1065,0.000000,0.0000,0.000000,255.12524,0.923377,256.048616,0.0,0.0,0.0,16.536899,1.908316,1033.978098,146.929238,1180.907336,142,Asia,035,South-eastern Asia,high_income,0,1,142,Asia,035,South-eastern Asia,upp_mid_income,0,0,18.445215,Liquefied gas tanker,95084.0,cbm,72622.0,NaN,123857.0,NaN,NaN,3,100000-199999,1977.0,Indonesia,Steam turbine,5,10.3,0.648148,0.005701,0.005401,0.005272,0.00523,0.005189,0.005140,0.005059,0.004989,0.004849,0.005698,0.008777,0.008292,0.009103,0.010804,0.010400,0.010146,0.009174,0.008411,0.005698,0.005497,0.005556,0.006401,0.008021,0.009725,0.009608,0.009438,0.008557,0.005698,0.005426,0.005406,0.005910,0.007331,0.009968,0.010426,0.009607,0.009715,0.005700,0.005427,0.005128,0.005373,0.005705,0.005956,0.007944,0.007998,0.007807,0.005768,0.005521,0.005501,0.005801,0.006277,0.006655,0.006785,0.007285,0.007254,1.279544e+08,729490.894251,691062.571858,674527.025517,669185.663713,663909.679230,657673.340646,647262.875943,638304.687616,620407.355946,729088.171620,1.123000e+06,1.060961e+06,1.164779e+06,1.382409e+06,1.330749e+06,1.298163e+06,1.173816e+06,1.076210e+06,729081.225150,703306.058271,710905.286248,819021.686481,1.026262e+06,1.244343e+06,1.229373e+06,1.207697e+06,1.094961e+06,729081.225150,694307.667299,691772.186455,756224.404579,937972.467384,1.275465e+06,1.334050e+06,1.229284e+06,1.243042e+06,729282.392967,694421.385735,656127.044816,687509.358001,729952.533959,762112.720615,1.016462e+06,1.023384e+06,998932.343652,738049.459914,706413.594174,703826.663978,742214.947938,803133.604806,851503.363032,868220.902531,932186.068968,928180.221714,47069.814804,8.293339e+07

## 2.3 Evaluate NZF Costs

In [6]:
years=["26", "29", "32", "35", "38", "41", "44", "47", "50"]
vess_types_not_found_in_inventories, vess_types_not_found_in_global_voys, hs_codes_not_mapped_to_HS, cost_int_match_desc, cost_int_match_desc_bool = [], [], [], [], False

for year in years:

    print("Processing game year 20{0}".format(year))

    # Setup columns for policy costs per bilateral goods trade.
    bau_usd, levy_usd, asis_usd, brazil_usd, liscr_usd, direct_usd = [], [], [], [], [], []
    
    for trade_idx, trade in trade_im.iterrows():

        # initiate selected voyages table as empty dataframe to begin
        int_arr_voys_vess = pd.DataFrame()

        # 3. If no facilitating vessel types were picked up for the HS code, take from full primary int. inv. voyages dataset, otherwise move on...
        if 'all' in trade.fac_vessel_types:
            hs_codes_not_mapped_to_HS.append(trade.HS4_desc)
            int_arr_voys_vess = int_arr_voys
            cost_int_match_desc.append("3. Primary Int. Inv. without Vess Type") if cost_int_match_desc_bool == False else None

        else:
            # 1. If possible, derive subset of voyages associated with the unique vessel type.
            int_arr_voys_vess = int_arr_voys[(int_arr_voys.vessel_type.isin(trade.fac_vessel_types))]    
            
            if int_arr_voys_vess.shape[0] > 0:
                cost_int_match_desc.append("1. Primary Int. Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                
            else:
                # 2. Finally, if no voyages are found as the vessel type doesn't appear in the country's shipping inventories, also take from full voyages dataset filtered for those vessel types instead.
                int_arr_voys_vess = voys_fem[(voys_fem.vessel_type.isin(trade.fac_vessel_types))]

                if int_arr_voys_vess.shape[0] > 0:
                    cost_int_match_desc.append("2. Global Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_inventories.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

                else:
                    # 4. Use full global voyage dataset as a back-up
                    int_arr_voys_vess = voys_fem
                    cost_int_match_desc.append("4. Global Inv. without Vess Type.") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_global_voys.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

        # Add cost intensities associated with the subset of voyages by vessel type, assuming 50% of NZF costs are borne by the importer.
        bau_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "bau35_usd_dwtnm_"+year))
        levy_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "levy35_usd_dwtnm_"+year))
        asis_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "asis35_usd_dwtnm_"+year))
        brazil_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "brazil35_usd_dwtnm_"+year))
        liscr_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "liscr35_usd_dwtnm_"+year))
        direct_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "direct35_usd_dwtnm_"+year))
    
    if cost_int_match_desc_bool == False:
        trade_im["cost_int_match_desc"] = cost_int_match_desc
    cost_int_match_desc_bool = True
    
    trade_im["bau_usd_"+year] = bau_usd
    trade_im["levy_usd_"+year] = levy_usd
    trade_im["asis_usd_"+year] = asis_usd
    trade_im["brazil_usd_"+year] = brazil_usd
    trade_im["liscr_usd_"+year] = liscr_usd
    trade_im["direct_usd_"+year] = direct_usd

print("Inventory voyages table used for the following vessel types: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_inventories).unique()))
print("Global voyages table used for the following vessel types found: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_global_voys).unique()))
print("Global voyages table used for the following commodities as no 'facilitating vessel types' were identified: \n\n{0}\n".format(pd.Series(hs_codes_not_mapped_to_HS).unique()))

print("\nNumber of trade records present in dataset: {0}".format(trade_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_im.partnerCode.unique())))
print("\nTotal value of trade: US${0}m".format(np.round(trade_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_im.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_im.sea_dist_nm.min(), 1),
    round(trade_im.sea_dist_nm.max(), 1),
    round(trade_im.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_im.vol_kg_vtw / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_im.cifvalue / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.cifvalue.sum() / 1000), 1)
))

print("\n\nTotal FEM costs in 2041...\n")
print("BAU: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.bau_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.bau_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Levy: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.levy_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.levy_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("'as-is': US${0}m ({1}% ad-val)".format(
    np.round(trade_im.asis_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.asis_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Brazil: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.brazil_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.brazil_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("LISCR: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.liscr_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.liscr_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Direct: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.direct_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.direct_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))

trade_im_agg = trade_im.groupby(["cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "cifvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_im_agg["vol_kg_vtw_pct"] = round(100 * trade_im_agg.vol_kg_vtw / trade_im_agg.vol_kg_vtw.sum(), 1)
trade_im_agg["cifvalue_pct"] = round(100 * trade_im_agg.cifvalue / trade_im_agg.cifvalue.sum(), 1)
print("Most prominent 'cost intensity match' types...\n\n{0}\n".format(
    trade_im_agg[["cost_int_match_desc", "vol_kg_vtw_pct", "cifvalue_pct"]].head(5)
))
trade_im_agg_2 = trade_im.groupby(["fac_vessel_types_str", "cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "cifvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_im_agg_2["vol_kg_vtw_pct"] = round(100 * trade_im_agg_2.vol_kg_vtw / trade_im_agg_2.vol_kg_vtw.sum(), 1)
trade_im_agg_2["cifvalue_pct"] = round(100 * trade_im_agg_2.cifvalue / trade_im_agg_2.cifvalue.sum(), 1)
print("Most prominent 'facilitating vessel types' and their 'cost intensity match' types...")
display(trade_im_agg_2[["fac_vessel_types_str", "cost_int_match_desc", "vol_kg_vtw_pct", "cifvalue_pct"]].head(5))

trade_im_na = trade_im[(trade_im[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (trade_im.fac_vessel_types.str.len() == 0)]
trade_im = trade_im[(~trade_im[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (~trade_im.fac_vessel_types.str.len() == 0)]
print("Rows with NA: ${0} ({1}%)\n".format(trade_im_na.primaryValue.sum(), round(100 * trade_im_na.primaryValue.sum() / trade_im.primaryValue.sum(), 1)))

trade_im.to_csv(output_dir + "{0}/impact_im_{1}.csv".format(iso_country, version), index=False)
trade_im.head(2)

Processing game year 2026
Processing game year 2029
Processing game year 2032
Processing game year 2035
Processing game year 2038
Processing game year 2041
Processing game year 2044
Processing game year 2047
Processing game year 2050
Inventory voyages table used for the following vessel types:

[]

Global voyages table used for the following vessel types found:

['Ro-Ro' 'Cruise' 'Other liquids tankers']

Global voyages table used for the following commodities as no 'facilitating vessel types' were identified:

['8462 | Machine-tools (inclu' '8428 | Lifting, handling, l'
 "6202 | Coats; women's or gi" '8528 | Monitors and project'
 '8419 | Machinery, plant (no' '8541 | Semiconductor device'
 '8539 | Lamps; electric fila' '4011 | New pneumatic tyres,'
 '8424 | Mechanical appliance' '8421 | Centrifuges, includi'
 '9401 | Seats (not those of ' '8432 | Agricultural, hortic'
 '8525 | Transmission apparat' '8716 | Trailers and semi-tr'
 '6201 | Overcoats, car-coats' '9027 | Instruments and appa'
 '8456 | Machine-tools; for w' '8460 | Machine-tools; for d'
 '8514 | Industrial or labora' '8903 | Yachts and other ves'
 '8414 | Air or vacuum pumps,' '8501 | Electric motors and '
 '9701 | Paintings, drawings ' '9703 | Sculptures and statu'
 '8479 | Machinery and mechan' '8459 | Machine-tools; (incl'
 '8704 | Vehicles; for the tr' '8517 | Telephone sets, incl'
 '9702 | Engravings, prints a' '5704 | Carpets and other te'
 '7104 | Stones; synthetic or' '8215 | Cutlery; spoons, for'
 '7019 | Glass fibres (includ' '3907 | Polyacetals, other p'
 '4823 | Paper, paperboard, c' '8703 | Motor cars and other'
 '8701 | Tractors; (other tha' '9404 | Mattress supports; a'
 '8711 | Motorcycles (includi' '8465 | Machine-tools; (incl'
 '8702 | Vehicles; public tra' '4412 | Plywood, veneered pa'
 '4407 | Wood sawn or chipped' '4403 | Wood in the rough, w'
 '6907 | Ceramic flags and pa' '5703 | Carpets and other te'
 '2202 | Waters, including mi' '2204 | Wine of fresh grapes'
 '7419 | Copper; articles the' '2106 | Food preparations no'
 '9405 | Luminaires and light' '6603 | Trimmings, parts and'
 '2853 | Phosphides, chemical' '7326 | Iron or steel; artic'
 '1509 | Olive oil and its fr' '1704 | Sugar confectionery '
 '4707 | Waste and scrap of p' '9403 | Furniture and parts '
 '9209 | Musical instrument p' '3822 | Reagents; diagnostic'
 '5911 | Textile products and' '3402 | Organic surface-acti'
 '3909 | Amino-resins, phenol' '6117 | Clothing accessories'
 '3812 | Prepared rubber acce' '1510 | Vegetable oils; oils'
 '3105 | Fertilizers; mineral' '6005 | Fabrics; warp knit ('
 '2920 | Esters of other inor' "4418 | Builders' joinery an"
 '3307 | Perfumery, cosmetic ' '3824 | Prepared binders for'
 '2530 | Mineral substances n' '5402 | Synthetic filament y'
 '2309 | Preparations of a ki' '1905 | Bread, pastry, cakes'
 '9508 | Travelling circuses ' '4504 | Agglomerated cork (w'
 '3926 | Articles of plastics' '7616 | Aluminium; articles '
 '3215 | Ink; printing, writi' '6406 | Footwear; parts of f'
 '3507 | Enzymes; prepared en' '1806 | Chocolate and other '
 '2009 | Fruit or nut juices ' '9620 | Monopods, bipods, tr'
 '6815 | Stone or other miner' '7508 | Nickel; articles the'
 '8708 | Motor vehicles; part' '1605 | Crustaceans, mollusc'
 '2931 | Other organo-inorgan' '8311 | Wires, rods, tubes, '
 '1214 | Swedes, mangolds, fo' '8487 | Machinery parts; not'
 '9406 | Buildings; prefabric' '4911 | Printed matter, n.e.'
 '7229 | Wire of other alloy ' '4421 | Wooden articles n.e.'
 '0307 | Molluscs; whether in' '3707 | Chemical preparation'
 '6217 | Clothing accessories' '4419 | Tableware and kitche'
 '2812 | Halides and halide o' '0604 | Foliage, branches an'
 '5802 | Fabrics; terry towel' '2922 | Oxygen-function amin'
 '3808 | Insecticides, rodent' '5007 | Woven fabrics of sil'
 '3901 | Polymers of ethylene' '2932 | Heterocyclic compoun'
 '5501 | Synthetic filament t' '5516 | Woven fabrics of art'
 '4414 | Wooden frames; for p' '5502 | Artificial filament '
 '6006 | Fabrics; knitted or ' '9114 | Clock or watch parts'
 '6704 | Wigs, false beards, ' '0303 | Fish; frozen, exclud'
 '6914 | Ceramic articles; n.' '0805 | Citrus fruit; fresh '
 '3603 | Safety fuses; detona' '0511 | Animal products not '
 '4401 | Fuel wood, in logs, ' '0910 | Ginger, saffron, tum'
 '0403 | Yogurt; buttermilk, ' '1008 | Buckwheat, millet an'
 '3006 | Pharmaceutical goods' '4905 | Maps and hydrographi'
 '8112 | Beryllium, chromium,' '3004 | Medicaments; (not go'
 '1515 | Fixed vegetable or m' '8103 | Tantalum; articles t'
 '3002 | Human blood; animal ' '0210 | Meat and edible meat'
 '3204 | Synthetic organic co' '2926 | Nitrile-function com'
 '2914 | Ketones and quinones' '2403 | Manufactured tobacco'
 '2903 | Halogenated derivati' '9706 | Antiques; of an age '
 '1404 | Vegetable products n' '2935 | Sulphonamides'
 '3606 | Ferro-cerium and oth' '0306 | Crustaceans; in shel'
 '0714 | Manioc, arrowroot, s' '4015 | Articles of apparel '
 '3103 | Fertilizers; mineral' '0802 | Nuts (excluding coco'
 '0308 | Aquatic invertebrate' '2845 | Isotopes other than '
 '4420 | Wood marquetry and i' '4602 | Basketwork, wickerwo'
 '5506 | Synthetic staple fib' '4402 | Wood charcoal (inclu'
 '4409 | Wood (including stri' '6310 | Rags; used or new, s'
 '0304 | Fish fillets and oth' '2923 | Quaternary ammonium '
 '2844 | Radioactive chemical' '8109 | Zirconium; articles '
 '2904 | Sulphonated, nitrate' '8106 | Bismuth; articles th'
 '9705 | Collections and coll' '0709 | Vegetables; n.e.c. i'
 '2933 | Heterocyclic compoun' '3705 | Photographic plates '
 '0712 | Vegetables, dried; w' '6304 | Furnishing articles;'
 '2939 | Alkaloids; natural o' '0410 | Animal products; ins']


Number of trade records present in dataset: 55209
Number of partner countries present in dataset: 194

Total value of trade: US$205875.0m
Total weight within the dataset: 231071.1 million kilograms

Distance to market: 645.0 nm (min) to 13150.7 nm (max), 5517.5 nm (observed mean)
Average distance to market (volume-weighted): 4716.0 nm
Average distance to market (value-weighted): 3946.1 nm


Total FEM costs in 2041...

BAU: US$2954.9m (1.4% ad-val)
Levy: US$6262.5m (3.0% ad-val)
'as-is': US$5941.8m (2.9% ad-val)
Brazil: US$6098.5m (3.0% ad-val)
LISCR: US$4120.1m (2.0% ad-val)
Direct: US$3902.5m (1.9% ad-val)
Most prominent 'cost intensity match' types...

                      cost_int_match_desc  vol_kg_vtw_pct  cifvalue_pct
0     1. Primary Int. Inv. with Vess Type            98.1          92.3
1  3. Primary Int. Inv. without Vess Type             1.9           7.6
2       4. Global Inv. without Vess Type.             0.0           0.1

Most prominent 'facilitating vessel types' and their 'cost intensity match' types...

,fac_vessel_types_str,cost_int_match_desc,vol_kg_vtw_pct,cifvalue_pct
0,['Bulk carrier'],1. Primary Int. Inv. with Vess Type,30.0,8.2
1,['Container'],1. Primary Int. Inv. with Vess Type,22.9,53.6
2,"['Container', 'Bulk carrier']",1. Primary Int. Inv. with Vess Type,13.4,3.2
3,['Oil tanker'],1. Primary Int. Inv. with Vess Type,12.3,7.2
4,['Chemical tanker'],1. Primary Int. Inv. with Vess Type,10.8,7.5

Rows with NA: $0.0 (0.0%)

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_im_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,cost_int_match_desc,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50
0,0,360,Indonesia,699,India,000,World,Import,Sea,847751 | Machinery; for mould,847751,NaN,0.0,NaN,854.000,NaN,854.000,India | 847751 | Machinery; for mould,84,84 | Machinery and mechan,India | 84 | Machinery and mechan,8477,8477 | Machinery; for worki,India | 8477 | Machinery; for worki,84,8477,847751,Machinery for moulding/retreading pneumatic ty...,Electrical and Machinery,2929,Manufacture of other special purpose machinery,72842,Machinery for working rubber/plastics/for the ...,41,OME - Machinery and equipment n.e.c.,44915,Machinery n.e.c. for working rubber or plastic...,15.0714,0.0664,both,NaN,56.705600,NaN,"[Container, Vehicle]","['Container', 'Vehicle']",5100.0,3168.992100,179.699598,1. Primary Int. Inv. with Vess Type,0.684150,0.682021,0.682217,0.682217,0.683399,0.683483,0.717185,1.316016,0.784302,0.729586,0.732716,0.752964,0.701175,1.264807,0.823110,0.758293,0.740804,0.777265,0.687245,1.397364,1.024353,0.900148,0.832202,0.811293,0.673539,1.485918,1.198729,1.117045,0.886055,0.871415,0.660190,1.512969,1.438590,1.464483,0.953857,0.916006,0.646401,1.475128,1.406730,1.515630,1.144290,0.932743,0.633353,1.303609,1.360232,1.446652,1.072589,0.943620,0.620256,1.185556,1.211153,1.427163,1.166314,0.952942
1,1,360,Indonesia,040,Austria,000,World,Import,Sea,340540 | Scouring pastes and,340540,NaN,0.0,NaN,226.541,NaN,226.541,Austria | 340540 | Scouring pastes and,34,"34 | Soap, organic surfac","Austria | 34 | Soap, organic surfac",3405,"3405 | Polishes, creams, sc","Austria | 3405 | Polishes, creams, sc",34,3405,340540,Scouring pastes & powders & other scouring pre...,"Petroleum, Chemical and Non-Metallic Mineral P...",2424,"Manufacture of soap and detergents, cleaning a...",55434,Scouring pastes & powders & other scouring pre...,33,"CRP - Chemical, rubber, plastic products",35334,Scouring pastes and powders and other scouring...,3.8817,0.2576,both,NaN,58.356962,NaN,[Container],['Container'],11576.0,7192.990696,419.761082,1. Primary Int. Inv. with Vess Type,1.496271,1.491800,1.492178,1.492178,1.494740,1.494747,1.571041,2.903862,1.724784,1.602860,1.608585,1.651584,1.535674,2.796832,1.812792,1.665564,1.625565,1.706666,1.504666,3.091136,2.260009,1.978414,1.826309,1.782778,1.474163,3.270035,2.645852,2.461748,1.951883,1.916801,1.444405,3.353815,3.197898,3.233644,2.100150,2.016483,1.413628,3.285397,3.144117,3.375528,2.561271,2.054293,1.384499,2.897368,3.016345,3.193015,2.364522,2.079073,1.355262,2.621947,2.675511,3.153346,2.598836,2.094782

## 2.4 Create Results Tables

### 2.4.1 Total Costs per Scenario

In [7]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        np.round(trade_im["bau_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["levy_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["asis_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["brazil_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["liscr_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["direct_usd_{0}".format(year)].sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% cif)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% fob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_fob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_im["bau_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["levy_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["asis_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["direct_usd_{0}".format(year)].sum() / gdp, 3),
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,BAU,3.163404e+09,3.104524e+09,3.053820e+09,3.004098e+09,2.954851e+09,2.903729e+09,2.855709e+09,2.805284e+09
1,Levy,5.334249e+09,5.171170e+09,5.697409e+09,6.183281e+09,6.262509e+09,6.047995e+09,5.462254e+09,5.026436e+09
2,'as-is',3.384988e+09,3.532190e+09,4.273015e+09,4.975516e+09,5.941826e+09,5.808033e+09,5.627773e+09,5.166241e+09
3,Brazil,3.188606e+09,3.312223e+09,3.865596e+09,4.671182e+09,6.098507e+09,6.176950e+09,6.020392e+09,5.917203e+09
4,LISCR,3.198984e+09,3.247507e+09,3.612083e+09,3.814492e+09,4.120106e+09,4.853904e+09,4.675748e+09,4.920796e+09
5,Direct,3.293871e+09,3.380477e+09,3.507934e+09,3.733581e+09,3.902518e+09,3.964172e+09,4.014989e+09,4.038544e+09

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0      BAU  1.54  1.51  1.48  1.46  1.44  1.41  1.39  1.36
1     Levy  2.59  2.51  2.77  3.00  3.04  2.94  2.65  2.44
2  'as-is'  1.64  1.72  2.08  2.42  2.89  2.82  2.73  2.51
3   Brazil  1.55  1.61  1.88  2.27  2.96  3.00  2.92  2.87
4    LISCR  1.55  1.58  1.75  1.85  2.00  2.36  2.27  2.39
5   Direct  1.60  1.64  1.70  1.81  1.90  1.93  1.95  1.96

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  0.218  0.214  0.211  0.207  0.204  0.200  0.197  0.193
1     Levy  0.368  0.357  0.393  0.426  0.432  0.417  0.377  0.347
2  'as-is'  0.233  0.244  0.295  0.343  0.410  0.401  0.388  0.356
3   Brazil  0.220  0.228  0.267  0.322  0.421  0.426  0.415  0.408
4    LISCR  0.221  0.224  0.249  0.263  0.284  0.335  0.322  0.339
5   Direct  0.227  0.233  0.242  0.257  0.269  0.273  0.277  0.279

### 2.4.2 Costs per Scenario relative to BAU

In [8]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        np.round((trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_usd_bau_{1}.csv".format(iso_country, version), index=False)
display(df)

print("\nTotal change in FEM costs by scenario (% bau)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        round((100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2)
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_bau_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% cif)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2)
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% fob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_fob_{1}.csv".format(iso_country, version), index=False)
    display(df)
    
print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3)
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,Levy,2.170845e+09,2.066646e+09,2.643588e+09,3.179183e+09,3.307658e+09,3.144266e+09,2.606545e+09,2.221152e+09
1,'as-is',2.215838e+08,4.276656e+08,1.219195e+09,1.971418e+09,2.986975e+09,2.904304e+09,2.772064e+09,2.360958e+09
2,Brazil,2.520213e+07,2.076988e+08,8.117755e+08,1.667083e+09,3.143656e+09,3.273221e+09,3.164684e+09,3.111919e+09
3,LISCR,3.558046e+07,1.429827e+08,5.582630e+08,8.103935e+08,1.165255e+09,1.950174e+09,1.820039e+09,2.115512e+09
4,Direct,1.304670e+08,2.759532e+08,4.541136e+08,7.294828e+08,9.476670e+08,1.060443e+09,1.159280e+09,1.233261e+09

Total change in FEM costs by scenario (% bau)...

  Scenario   2029   2032   2035    2038    2041    2044    2047    2050
0     Levy  68.62  66.57  86.57  105.83  111.94  108.28   91.27   79.18
1  'as-is'   4.12   8.89  14.87   24.28   32.07   36.52   40.60   43.96
2   Brazil   7.00  13.78  39.92   65.62  101.09  100.02   97.07   84.16
3    LISCR   0.80   6.69  26.58   55.49  106.39  112.72  110.82  110.93
4   Direct   1.12   4.61  18.28   26.98   39.44   67.16   63.73   75.41

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0     Levy  1.05  1.00  1.28  1.54  1.61  1.53  1.27  1.08
1  'as-is'  0.06  0.13  0.22  0.35  0.46  0.52  0.56  0.60
2   Brazil  0.11  0.21  0.59  0.96  1.45  1.41  1.35  1.15
3    LISCR  0.01  0.10  0.39  0.81  1.53  1.59  1.54  1.51
4   Direct  0.02  0.07  0.27  0.39  0.57  0.95  0.88  1.03

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  0.150  0.143  0.182  0.219  0.228  0.217  0.180  0.153
1  'as-is'  0.009  0.019  0.031  0.050  0.065  0.073  0.080  0.085
2   Brazil  0.015  0.029  0.084  0.136  0.206  0.200  0.191  0.163
3    LISCR  0.002  0.014  0.056  0.115  0.217  0.226  0.218  0.215
4   Direct  0.002  0.010  0.039  0.056  0.080  0.134  0.126  0.146

# 3. Let's consider Exports

## 3.1 Read-in Trade dataset

In [9]:
trade_ex_d = {
    "reporterCode":"str", "partnerCode":"str", "partner2Code":"str", 
    "cmdCode":"str", "HS2":"str", "HS4":"str", "hs2":"str", "hs4":"str", "hs6":"str",
    "isic":"str", "sitc":"str", "gtap":"str", "cpc":"str"
}
if res_mlc == False:
    trade_ex = pd.read_csv(input_dir+"trade/{0}/trade_ex_dist_{1}.csv".format(iso_country, version), dtype=trade_ex_d)
else:
    trade_ex = pd.read_csv(input_dir+"trade/{0}/trade_ex_mlc_{1}.csv".format(iso_country, version), dtype=trade_ex_d)
trade_ex['fac_vessel_types'] = [ast.literal_eval(x) for x in trade_ex.fac_vessel_types.values]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(trade_ex.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_ex.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(trade_ex.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(trade_ex.fobvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_ex.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_ex.sea_dist_nm.min(), 1),
    round(trade_ex.sea_dist_nm.max(), 1),
    round(trade_ex.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_ex.vol_kg_vtw / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_ex.fobvalue / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.fobvalue.sum() / 1000), 1)
))
trade_ex.head(2)

Aggregate trade portfolio statistics for 'Indonesia':

Number of trade records present in dataset: 65271
Number of partner countries present in dataset: 208
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$255223.5m
Total weight within the dataset: 474079.2 million kilograms

Distance to market: 645.0 nm (min) to 13150.1 nm (max), 5566.4 nm (observed mean)
Average distance to market (volume-weighted): 3152.3 nm
Average distance to market (value-weighted): 4369.6 nm

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_ex_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm
0,0,360,Indonesia,368,Iraq,000,World,Export,Sea,"710391 | Stones; rubies, sapp",710391,carat,157700.0,31.54,NaN,988.00,988.00,"Iraq | 710391 | Stones; rubies, sapp",71,"71 | Natural, cultured pe","Iraq | 71 | Natural, cultured pe",7103,7103 | Precious (excluding,Iraq | 7103 | Precious (excluding,71,7103,710391,"Rubies, sapphires & emeralds, worked othw. tha...",Mining and Quarrying,3691,Manufacture of jewellery and related articles,66739,"Precious stones (other than diamonds), worked ...",42,OMF - Manufactures n.e.c.,3822,"Cultured pearls, precious or semi- precious st...",35.1377,0.0285,both,0.031923,28.158000,31.54,[Container],['Container'],7348.0,4565.834108,128.564757
1,1,360,Indonesia,392,Japan,000,World,Export,Sea,710399 | Stones; precious (ot,710399,carat,22132500.0,4426.50,NaN,8287.23,8287.23,Japan | 710399 | Stones; precious (ot,71,"71 | Natural, cultured pe","Japan | 71 | Natural, cultured pe",7103,7103 | Precious (excluding,Japan | 7103 | Precious (excluding,71,7103,710399,"Precious stones (excl. diamonds, rubies, saphi...",Mining and Quarrying,3691,Manufacture of jewellery and related articles,66739,"Precious stones (other than diamonds), worked ...",42,OMF - Manufactures n.e.c.,3822,"Cultured pearls, precious or semi- precious st...",35.1377,0.0285,both,0.534135,236.186055,4426.50,[Container],['Container'],5808.0,3608.922768,852.377231

## 3.2 Derive Internationally Departing Voyages

In [10]:
# International Departures
int_arr_voys = voys_fem[(voys_fem.dest_country == iso_country) & (voys_fem.source_country != iso_country)].reset_index(drop=True)
int_arr_voys.to_csv(output_dir + "{0}/int_arr_voys_{1}.csv".format(iso_country, version), index=False)
int_dep_voys = voys_fem[(voys_fem.source_country == iso_country) & (voys_fem.dest_country != iso_country)].reset_index(drop=True)
int_dep_voys.to_csv(output_dir + "{0}/int_dep_voys_{1}.csv".format(iso_country, version), index=False)
voyages_analysis(int_dep_voys)
int_dep_voys.head(2)

Number of Voyages found: 17529
Total size of the fleet: 7655 vessels
8 vessel types contained in the dataset: ['Refrigerated bulk' 'General cargo' 'Liquefied gas tanker' 'Bulk carrier'
 'Container' 'Chemical tanker' 'Vehicle' 'Oil tanker']
Total transport work capacity: 3534943.3 million deadweight-tonne nautical miles
Total cargo transported: 616092568.4 tonnes
Total transport work: 1807416.2 million tonne nautical miles
Average build year of the fleet: 2008
Total Energy Demands: 155525.1 EJ
Total CO2 produced: 11928012.9 tonnes

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,2890,6908993,567451000,IDAMQ,360,IDN,ID,Indonesia,Ambon,MYLAU,458,MYS,MY,Malaysia,Pulau Indah,2018-02-02 04:00:00,2018-10-08 16:00:00,5964.0,61.0,6025.0,2456.249219,35.107095,0.000008,35.107103,1907.351100,20.642400,1927.993500,0.0,0.0,0.0,0.0,0.0,0.0,82.855197,0.881431,6224.291119,66.179560,6290.470679,142,Asia,035,South-eastern Asia,upp_mid_income,0,0,142,Asia,035,South-eastern Asia,upp_mid_income,0,0,83.736628,Refrigerated bulk,2649.0,dwt,2435.0,NaN,NaN,NaN,NaN,2,2000-5999,1969.0,Thailand,MSD,1,76.1,0.666667,0.031550,0.032676,0.032143,0.031676,0.031218,0.030769,0.030310,0.029878,0.029438,0.031576,0.052178,0.052414,0.058040,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.059420,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,5.980967e+06,188701.558425,195431.310703,192247.949424,189455.984865,186715.746000,184027.231927,181284.826069,178701.283815,176066.892432,188852.724423,312077.079522,313487.208775,347132.475461,358865.923744,354651.762336,349495.602009,348261.572805,348802.790050,188809.801332,207203.826579,220359.207382,267502.406567,296784.090641,322269.399440,345682.219424,353268.306088,346888.725712,188809.801332,195737.041179,206517.932784,243635.536657,288150.801004,334121.017657,343590.728282,350914.009237,355386.688027,188754.805066,195569.387545,202206.484850,227136.951458,240009.571095,250223.222011,259062.882073,267333.317237,274384.851315,188754.805066,203264.229041,208714.662933,216095.578879,229050.249818,238784.44904,242861.976971,245809.628720,247991.101681,1623.333334,3.987311e+06
1,5481,7384285,273420050,IDPSS,360,IDN,ID,Indonesia,Pulau Sambu,MYLAU,458,MYS,MY,Malaysia,Pulau Indah,2018-12-07 08:00:00,2018-12-07 23:00:00,15.0,24.0,39.0,126.729411,0.000000,0.000000,0.000000,2.146349,1.500003,3.646352,0.0,0.0,0.0,0.0,0.0,0.0,0.091649,0.064050,6.881196,4.809008,11.690204,142,Asia,035,South-eastern Asia,upp_mid_income,0,0,142,Asia,035,South-eastern Asia,upp_mid_income,0,0,0.155699,General cargo,4120.0,dwt,5599.0,119.0,NaN,NaN,NaN,2,5000-9999,1975.0,Faeroe Islands,MSD,4,19.1,0.639731,0.013245,0.013561,0.013411,0.013280,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.022330,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.018580,0.018382,0.018420,0.013244,0.013910,0.014148,0.014473,0.015050,0.015474,0.015636,0.015745,0.015819,7.095580e+05,9398.057446,9622.253602,9516.202542,9423.190542,9331.901741,9242.336108,9150.975115,9064.906532,8977.143953,9396.976070,13475.858723,13283.703978,14229.987120,15755.653455,15600.168938,15116.884388,14264.363092,13736.068018,9396.566838,9986.858259,10234.402741,11747.756799,12936.740838,15224.088352,14951.702450,14676.289115,13782.798835,9396.566838,9609.055310,9942.105067,11112.920904,12496.810727,15844.765843,15324.533202,15449.917278,15290.356305,9397.281455,9615.130142,9824.261863,10633.023231,10932.697766,11669.809974,13183.757708,13043.102405,13069.794010,9397.281455,9869.691805,10038.992097,10269.614436,10679.091267,10979.71102,11094.762093,11172.195295,11224.197330,3581.851853,4.539260e+05

## 3.3 Evaluate NZF Costs

In [11]:
years=["26", "29", "32", "35", "38", "41", "44", "47", "50"]
vess_types_not_found_in_inventories, vess_types_not_found_in_global_voys, hs_codes_not_mapped_to_HS, cost_int_match_desc, cost_int_match_desc_bool = [], [], [], [], False

for year in years:

    print("Processing game year 20{0}".format(year))

    # Setup columns for policy costs per bilateral goods trade.
    bau_usd, levy_usd, asis_usd, brazil_usd, liscr_usd, direct_usd = [], [], [], [], [], []
    
    for trade_idx, trade in trade_ex.iterrows():

        # initiate selected voyages table as empty dataframe to begin
        int_dep_voys_vess = pd.DataFrame()

        # 3. If no facilitating vessel types were picked up for the HS code, take from full primary int. inv. voyages dataset, otherwise move on...
        if 'all' in trade.fac_vessel_types:
            hs_codes_not_mapped_to_HS.append(trade.HS4_desc)
            int_dep_voys_vess = int_dep_voys
            cost_int_match_desc.append("3. Primary Int. Inv. without Vess Type") if cost_int_match_desc_bool == False else None

        else:
            # 1. If possible, derive subset of voyages associated with the unique vessel type.
            int_dep_voys_vess = int_dep_voys[(int_dep_voys.vessel_type.isin(trade.fac_vessel_types))]    
            
            if int_dep_voys_vess.shape[0] > 0:
                cost_int_match_desc.append("1. Primary Int. Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                
            else:
                # 2. Finally, if no voyages are found as the vessel type doesn't appear in the country's shipping inventories, also take from full voyages dataset filtered for those vessel types instead.
                int_dep_voys_vess = voys_fem[(voys_fem.vessel_type.isin(trade.fac_vessel_types))]
                
                if int_dep_voys_vess.shape[0] > 0:
                    cost_int_match_desc.append("2. Global Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_inventories.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

                else:
                    # 4. Use full global voyage dataset as a back-up
                    int_dep_voys_vess = voys_fem
                    cost_int_match_desc.append("4. Global Inv. without Vess Type.") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_global_voys.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]
    
        # Add cost intensities associated with the subset of voyages by vessel type, assuming 50% of NZF costs are borne by the exporter.
        bau_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "bau35_usd_dwtnm_"+year))
        levy_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "levy35_usd_dwtnm_"+year))
        asis_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "asis35_usd_dwtnm_"+year))
        brazil_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "brazil35_usd_dwtnm_"+year))
        liscr_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "liscr35_usd_dwtnm_"+year))
        direct_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "direct35_usd_dwtnm_"+year))

    if cost_int_match_desc_bool == False:
        trade_ex["cost_int_match_desc"] = cost_int_match_desc
    cost_int_match_desc_bool = True

    trade_ex["bau_usd_"+year] = bau_usd
    trade_ex["levy_usd_"+year] = levy_usd
    trade_ex["asis_usd_"+year] = asis_usd
    trade_ex["brazil_usd_"+year] = brazil_usd
    trade_ex["liscr_usd_"+year] = liscr_usd
    trade_ex["direct_usd_"+year] = direct_usd
    
print("Inventory voyages table used for the following vessel types: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_inventories).unique()))
print("Global voyages table used for the following vessel types found: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_global_voys).unique()))
print("Global voyages table used for the following commodities as no 'facilitating vessel types' were identified: \n\n{0}\n".format(pd.Series(hs_codes_not_mapped_to_HS).unique()))

print()
print("Number of trade records present in dataset: {0}".format(trade_ex.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_ex.partnerCode.unique())))
print("\nTotal value of trade: US${0}m".format(np.round(trade_ex.fobvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_ex.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_ex.sea_dist_nm.min(), 1),
    round(trade_ex.sea_dist_nm.max(), 1),
    round(trade_ex.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_ex.vol_kg_vtw / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_ex.fobvalue / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.fobvalue.sum() / 1000), 1)
))

print("\n\nTotal FEM costs in 2041...\n")
print("BAU: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.bau_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.bau_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Levy: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.levy_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.levy_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("'as-is': US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.asis_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.asis_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Brazil: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.brazil_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.brazil_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("LISCR: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.liscr_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.liscr_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Direct: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.direct_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.direct_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))

trade_ex_agg = trade_ex.groupby(["cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "fobvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_ex_agg["vol_kg_vtw_pct"] = round(100 * trade_ex_agg.vol_kg_vtw / trade_ex_agg.vol_kg_vtw.sum(), 1)
trade_ex_agg["fobvalue_pct"] = round(100 * trade_ex_agg.fobvalue / trade_ex_agg.fobvalue.sum(), 1)
print("Most prominent 'cost intensity match' types...\n\n{0}\n".format(
    trade_ex_agg[["cost_int_match_desc", "vol_kg_vtw_pct", "fobvalue_pct"]].head(5)
))
trade_ex_agg_2 = trade_ex.groupby(["fac_vessel_types_str", "cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "fobvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_ex_agg_2["vol_kg_vtw_pct"] = round(100 * trade_ex_agg_2.vol_kg_vtw / trade_ex_agg_2.vol_kg_vtw.sum(), 1)
trade_ex_agg_2["fobvalue_pct"] = round(100 * trade_ex_agg_2.fobvalue / trade_ex_agg_2.fobvalue.sum(), 1)
print("Most prominent 'facilitating vessel types' and their 'cost intensity match' types...")
display(trade_ex_agg_2[["fac_vessel_types_str", "cost_int_match_desc", "vol_kg_vtw_pct", "fobvalue_pct"]].head(5))

trade_ex_na = trade_ex[(trade_ex[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (trade_ex.fac_vessel_types.str.len() == 0)]
trade_ex = trade_ex[(~trade_ex[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (~trade_ex.fac_vessel_types.str.len() == 0)]
print("Rows with NA: ${0} ({1}%)\n".format(trade_ex_na.primaryValue.sum(), round(100 * trade_ex_na.primaryValue.sum() / trade_ex.primaryValue.sum(), 1)))

trade_ex.to_csv(output_dir + "{0}/impact_ex_{1}.csv".format(iso_country, version), index=False)
trade_ex.head(2)

Processing game year 2026
Processing game year 2029
Processing game year 2032
Processing game year 2035
Processing game year 2038
Processing game year 2041
Processing game year 2044
Processing game year 2047
Processing game year 2050
Inventory voyages table used for the following vessel types:

[]

Global voyages table used for the following vessel types found:

['Other liquids tankers' 'Cruise' 'Ro-Ro']

Global voyages table used for the following commodities as no 'facilitating vessel types' were identified:

['2202 | Waters, including mi' '2204 | Wine of fresh grapes'
 '4412 | Plywood, veneered pa' '4407 | Wood sawn or chipped'
 '4403 | Wood in the rough, w' '6907 | Ceramic flags and pa'
 '5703 | Carpets and other te' '9401 | Seats (not those of '
 '9404 | Mattress supports; a' '8701 | Tractors; (other tha'
 '8703 | Motor cars and other' '6201 | Overcoats, car-coats'
 '8541 | Semiconductor device' '4011 | New pneumatic tyres,'
 '8517 | Telephone sets, incl' '8711 | Motorcycles (includi'
 '8428 | Lifting, handling, l' '8704 | Vehicles; for the tr'
 '8903 | Yachts and other ves' '8421 | Centrifuges, includi'
 '8419 | Machinery, plant (no' '8528 | Monitors and project'
 '8465 | Machine-tools; (incl' '8460 | Machine-tools; for d'
 '9027 | Instruments and appa' '8462 | Machine-tools (inclu'
 '8432 | Agricultural, hortic' '8702 | Vehicles; public tra'
 '3907 | Polyacetals, other p' '1704 | Sugar confectionery '
 '6815 | Stone or other miner' '4419 | Tableware and kitche'
 '4409 | Wood (including stri' '9405 | Luminaires and light'
 '7419 | Copper; articles the' '1404 | Vegetable products n'
 '9403 | Furniture and parts ' '2403 | Manufactured tobacco'
 '1605 | Crustaceans, mollusc' "4418 | Builders' joinery an"
 '8215 | Cutlery; spoons, for' '6117 | Clothing accessories'
 '9701 | Paintings, drawings ' '3402 | Organic surface-acti'
 '4420 | Wood marquetry and i' '6603 | Trimmings, parts and'
 '6914 | Ceramic articles; n.' '4421 | Wooden articles n.e.'
 '2106 | Food preparations no' '0307 | Molluscs; whether in'
 '0604 | Foliage, branches an' '3215 | Ink; printing, writi'
 '3926 | Articles of plastics' '9114 | Clock or watch parts'
 '4602 | Basketwork, wickerwo' '4911 | Printed matter, n.e.'
 '4823 | Paper, paperboard, c' '7326 | Iron or steel; artic'
 '8487 | Machinery parts; not' '9209 | Musical instrument p'
 '0910 | Ginger, saffron, tum' '2530 | Mineral substances n'
 '2939 | Alkaloids; natural o' '2935 | Sulphonamides'
 '0511 | Animal products not ' '9406 | Buildings; prefabric'
 '4015 | Articles of apparel ' '4414 | Wooden frames; for p'
 '2309 | Preparations of a ki' '3824 | Prepared binders for'
 '6217 | Clothing accessories' '6704 | Wigs, false beards, '
 '4402 | Wood charcoal (inclu' '1905 | Bread, pastry, cakes'
 '3307 | Perfumery, cosmetic ' '7616 | Aluminium; articles '
 '3901 | Polymers of ethylene' '3004 | Medicaments; (not go'
 '0304 | Fish fillets and oth' '3808 | Insecticides, rodent'
 '0403 | Yogurt; buttermilk, ' '3822 | Reagents; diagnostic'
 '0303 | Fish; frozen, exclud' '1806 | Chocolate and other '
 '6005 | Fabrics; warp knit (' '2009 | Fruit or nut juices '
 '4905 | Maps and hydrographi' '0306 | Crustaceans; in shel'
 '0802 | Nuts (excluding coco' '7508 | Nickel; articles the'
 '1008 | Buckwheat, millet an' '6406 | Footwear; parts of f'
 '8311 | Wires, rods, tubes, ' '4504 | Agglomerated cork (w'
 '9508 | Travelling circuses ' '2845 | Isotopes other than '
 '5911 | Textile products and' '9620 | Monopods, bipods, tr'
 '6304 | Furnishing articles;' '8708 | Motor vehicles; part'
 '6006 | Fabrics; knitted or ' '3103 | Fertilizers; mineral'
 '3006 | Pharmaceutical goods' '3707 | Chemical preparation'
 '4401 | Fuel wood, in logs, ' '1509 | Olive oil and its fr'
 '3105 | Fertilizers; mineral' '3507 | Enzymes; prepared en'
 '2853 | Phosphides, chemical' '5007 | Woven fabrics of sil'
 '8716 | Trailers and semi-tr' '3812 | Prepared rubber acce'
 '5516 | Woven fabrics of art' '0305 | Fish, dried, salted '
 '7019 | Glass fibres (includ' '2926 | Nitrile-function com'
 '2904 | Sulphonated, nitrate' '2931 | Other organo-inorgan'
 '1510 | Vegetable oils; oils' '5502 | Artificial filament '
 '0210 | Meat and edible meat' '2920 | Esters of other inor'
 '5802 | Fabrics; terry towel' '1214 | Swedes, mangolds, fo'
 '3909 | Amino-resins, phenol' '2621 | Slag and ash n.e.c. '
 '7229 | Wire of other alloy ' '5402 | Synthetic filament y'
 '0410 | Animal products; ins' '0805 | Citrus fruit; fresh '
 '2844 | Radioactive chemical' '2914 | Ketones and quinones'
 '4707 | Waste and scrap of p' '3002 | Human blood; animal '
 '6310 | Rags; used or new, s' '2932 | Heterocyclic compoun'
 '3603 | Safety fuses; detona' '0302 | Fish; fresh or chill'
 '0714 | Manioc, arrowroot, s' '0308 | Aquatic invertebrate'
 '5501 | Synthetic filament t' '0712 | Vegetables, dried; w'
 '1604 | Prepared or preserve' "6202 | Coats; women's or gi"
 '8539 | Lamps; electric fila' '8424 | Mechanical appliance'
 '9703 | Sculptures and statu' '8525 | Transmission apparat'
 '8514 | Industrial or labora' '8456 | Machine-tools; for w'
 '9702 | Engravings, prints a' '8414 | Air or vacuum pumps,'
 '8459 | Machine-tools; (incl' '0106 | Animals; live, n.e.c']


Number of trade records present in dataset: 65271
Number of partner countries present in dataset: 208

Total value of trade: US$255223.5m
Total weight within the dataset: 474079.2 million kilograms

Distance to market: 645.0 nm (min) to 13150.1 nm (max), 5566.4 nm (observed mean)
Average distance to market (volume-weighted): 3152.3 nm
Average distance to market (value-weighted): 4369.6 nm


Total FEM costs in 2041...

BAU: US$5067.2m (2.0% ad-val)
Levy: US$11102.5m (4.4% ad-val)
'as-is': US$10576.0m (4.1% ad-val)
Brazil: US$10781.6m (4.2% ad-val)
LISCR: US$7178.5m (2.8% ad-val)
Direct: US$6859.5m (2.7% ad-val)
Most prominent 'cost intensity match' types...

                      cost_int_match_desc  vol_kg_vtw_pct  fobvalue_pct
0     1. Primary Int. Inv. with Vess Type            98.7          95.2
1  3. Primary Int. Inv. without Vess Type             1.3           4.8
2       4. Global Inv. without Vess Type.             0.0           0.0

Most prominent 'facilitating vessel types' and their 'cost intensity match' types...

,fac_vessel_types_str,cost_int_match_desc,vol_kg_vtw_pct,fobvalue_pct
0,['Container'],1. Primary Int. Inv. with Vess Type,66.0,58.4
1,"['Container', 'Bulk carrier']",1. Primary Int. Inv. with Vess Type,10.8,3.0
2,['Chemical tanker'],1. Primary Int. Inv. with Vess Type,6.5,10.5
3,['Bulk carrier'],1. Primary Int. Inv. with Vess Type,5.7,5.3
4,['Liquefied gas tanker'],1. Primary Int. Inv. with Vess Type,2.5,2.4

Rows with NA: $0.0 (0.0%)

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_ex_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,cost_int_match_desc,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50
0,0,360,Indonesia,368,Iraq,000,World,Export,Sea,"710391 | Stones; rubies, sapp",710391,carat,157700.0,31.54,NaN,988.00,988.00,"Iraq | 710391 | Stones; rubies, sapp",71,"71 | Natural, cultured pe","Iraq | 71 | Natural, cultured pe",7103,7103 | Precious (excluding,Iraq | 7103 | Precious (excluding,71,7103,710391,"Rubies, sapphires & emeralds, worked othw. tha...",Mining and Quarrying,3691,Manufacture of jewellery and related articles,66739,"Precious stones (other than diamonds), worked ...",42,OMF - Manufactures n.e.c.,3822,"Cultured pearls, precious or semi- precious st...",35.1377,0.0285,both,0.031923,28.158000,31.54,[Container],['Container'],7348.0,4565.834108,128.564757,1. Primary Int. Inv. with Vess Type,0.458637,0.457270,0.457386,0.457386,0.458168,0.458170,0.481547,0.889891,0.528636,0.491311,0.493064,0.506236,0.470710,0.857108,0.555639,0.510527,0.498269,0.523117,0.461209,0.947309,0.692756,0.606419,0.559799,0.546442,0.451863,1.002131,0.810992,0.754521,0.598283,0.587512,0.442745,1.027860,0.979995,0.991079,0.643754,0.618061,0.433314,1.006809,0.963523,1.034428,0.784918,0.629647,0.42439,0.888034,0.924506,0.978597,0.724608,0.637241,0.415431,0.803622,0.820018,0.966495,0.796565,0.642053
1,1,360,Indonesia,392,Japan,000,World,Export,Sea,710399 | Stones; precious (ot,710399,carat,22132500.0,4426.50,NaN,8287.23,8287.23,Japan | 710399 | Stones; precious (ot,71,"71 | Natural, cultured pe","Japan | 71 | Natural, cultured pe",7103,7103 | Precious (excluding,Japan | 7103 | Precious (excluding,71,7103,710399,"Precious stones (excl. diamonds, rubies, saphi...",Mining and Quarrying,3691,Manufacture of jewellery and related articles,66739,"Precious stones (other than diamonds), worked ...",42,OMF - Manufactures n.e.c.,3822,"Cultured pearls, precious or semi- precious st...",35.1377,0.0285,both,0.534135,236.186055,4426.50,[Container],['Container'],5808.0,3608.922768,852.377231,1. Primary Int. Inv. with Vess Type,3.040737,3.031673,3.032441,3.032441,3.037631,3.037644,3.192631,5.899930,3.504829,3.257366,3.268989,3.356320,3.120784,5.682581,3.683853,3.384766,3.303495,3.468238,3.057791,6.280607,4.592933,4.020522,3.711436,3.622881,2.995825,6.644075,5.376830,5.002434,3.966581,3.895175,2.935374,6.814657,6.497312,6.570800,4.268052,4.097712,2.872851,6.675089,6.388101,6.858201,5.203964,4.174526,2.81368,5.887613,6.129425,6.488043,4.804108,4.224875,2.754286,5.327970,5.436676,6.407809,5.281181,4.256773

## 3.4 Create Results Tables

### 3.4.1 Total Costs per Scenario

In [12]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        np.round(trade_ex["bau_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["levy_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["asis_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["brazil_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["liscr_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["direct_usd_{0}".format(year)].sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% cif)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
    display(df)

    
print("\nTotal FEM costs by scenario (% fob)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_fob_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / gdp, 3)
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,BAU,5.463598e+09,5.351953e+09,5.255277e+09,5.160241e+09,5.067192e+09,4.970749e+09,4.879717e+09,4.786708e+09
1,Levy,9.614778e+09,9.278110e+09,1.026216e+10,1.096854e+10,1.110249e+10,1.087775e+10,9.684537e+09,8.843045e+09
2,'as-is',5.918579e+09,6.206190e+09,7.593281e+09,8.883159e+09,1.057595e+10,1.044399e+10,1.003561e+10,9.058753e+09
3,Brazil,5.535283e+09,5.755246e+09,6.775853e+09,8.301827e+09,1.078161e+10,1.112132e+10,1.069786e+10,1.055794e+10
4,LISCR,5.553077e+09,5.631322e+09,6.299021e+09,6.683014e+09,7.178521e+09,8.590593e+09,8.111328e+09,8.720108e+09
5,Direct,5.713982e+09,5.882752e+09,6.122153e+09,6.545369e+09,6.859500e+09,6.977208e+09,7.061777e+09,7.109854e+09

Total FEM costs by scenario (% fob)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0      BAU  2.14  2.10  2.06  2.02  1.99  1.95  1.91  1.88
1     Levy  3.77  3.64  4.02  4.30  4.35  4.26  3.79  3.46
2  'as-is'  2.32  2.43  2.98  3.48  4.14  4.09  3.93  3.55
3   Brazil  2.17  2.25  2.65  3.25  4.22  4.36  4.19  4.14
4    LISCR  2.18  2.21  2.47  2.62  2.81  3.37  3.18  3.42
5   Direct  2.24  2.30  2.40  2.56  2.69  2.73  2.77  2.79

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  0.377  0.369  0.362  0.356  0.349  0.343  0.337  0.330
1     Levy  0.663  0.640  0.708  0.756  0.766  0.750  0.668  0.610
2  'as-is'  0.408  0.428  0.524  0.613  0.729  0.720  0.692  0.625
3   Brazil  0.382  0.397  0.467  0.573  0.744  0.767  0.738  0.728
4    LISCR  0.383  0.388  0.434  0.461  0.495  0.592  0.559  0.601
5   Direct  0.394  0.406  0.422  0.451  0.473  0.481  0.487  0.490

### 3.4.2 Costs per Scenario relative to BAU

In [13]:
print("\nTotal FEM costs by scenario (US$)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:

    d_temp = {"20{0}".format(year): [
        np.round((trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_usd_bau_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal change in FEM costs by scenario (% bau)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        round((100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_bau_{1}.csv".format(iso_country, version), index=False)
display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% cif)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_cif_{1}.csv".format(iso_country, version), index=False)
    display(df)


print("\nTotal FEM costs by scenario (% fob)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_fob_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,Levy,4.151180e+09,3.926158e+09,5.006886e+09,5.808296e+09,6.035301e+09,5.906997e+09,4.804820e+09,4.056337e+09
1,'as-is',4.549807e+08,8.542374e+08,2.338004e+09,3.722918e+09,5.508761e+09,5.473244e+09,5.155897e+09,4.272045e+09
2,Brazil,7.168521e+07,4.032931e+08,1.520576e+09,3.141586e+09,5.714421e+09,6.150569e+09,5.818148e+09,5.771229e+09
3,LISCR,8.947940e+07,2.793693e+08,1.043744e+09,1.522773e+09,2.111328e+09,3.619844e+09,3.231611e+09,3.933400e+09
4,Direct,2.503842e+08,5.307998e+08,8.668756e+08,1.385128e+09,1.792308e+09,2.006460e+09,2.182060e+09,2.323147e+09

Total change in FEM costs by scenario (% bau)...

  Scenario   2029   2032   2035    2038    2041    2044    2047    2050
0     Levy  75.98  73.36  95.27  112.56  119.11  118.84   98.47   84.74
1  'as-is'   8.33  15.96  44.49   72.15  108.71  110.11  105.66   89.25
2   Brazil   1.31   7.54  28.93   60.88  112.77  123.74  119.23  120.57
3    LISCR   1.64   5.22  19.86   29.51   41.67   72.82   66.23   82.17
4   Direct   4.58   9.92  16.50   26.84   35.37   40.37   44.72   48.53

Total FEM costs by scenario (% fob)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0     Levy  1.63  1.54  1.96  2.28  2.36  2.31  1.88  1.59
1  'as-is'  0.18  0.33  0.92  1.46  2.16  2.14  2.02  1.67
2   Brazil  0.03  0.16  0.60  1.23  2.24  2.41  2.28  2.26
3    LISCR  0.04  0.11  0.41  0.60  0.83  1.42  1.27  1.54
4   Direct  0.10  0.21  0.34  0.54  0.70  0.79  0.85  0.91

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  0.286  0.271  0.345  0.401  0.416  0.407  0.331  0.280
1  'as-is'  0.031  0.059  0.161  0.257  0.380  0.377  0.356  0.295
2   Brazil  0.005  0.028  0.105  0.217  0.394  0.424  0.401  0.398
3    LISCR  0.006  0.019  0.072  0.105  0.146  0.250  0.223  0.271
4   Direct  0.017  0.037  0.060  0.096  0.124  0.138  0.150  0.160