<h2>Impact (v0.64) - 'Impact (v0.64).ipynb'</h2>

<u><h4>Context</h4></u>

The aim of the 'Impact' notebooks are to explore economic impacts resulsting from the FEM outputs in the lead-up to Autumn 2026, taking foward outputs from the associated 'Trade' notebooks.

<u><h4>Version Documentation and Future Work</h4></u>

'v0.2' cleaned up the analysis code by introducing the cost intensity estimation functions that were previously in the 'inventories' notebooks. For example, the 'get_usd_per_tnm' function is included here and applied to voyages identified as relevant to each individual trade record. The NZF costs associated with each trade record are now evaluated like this. 'v0.3' introduced the exporter- and importer-side trade portfolios at an HS-digit 4 level of resolution. With this implemented, the matching algorithm is now be being evaluated using the cargo weight field rather than value, and the process will be being conducted at the HS-digit 4 level of resolution. Since we are now confident regarding the use of the Global Shipping Watch dataset for the purposes of matching HS codes with facilitating vessel types, we should then be in good shape to take the analysis forward using the results produced in this notebook. 'v0.3' also subsumed the 'inventories' notebooks. In 'v0.4' sought to include transport costs data from UNCTAD's Trade-and-Transport database. However, there are now concerns regarding this dataset as it is importer-side only, and therefore has odd looking exporter-side portfolios. Instead, it makes sense for us to utilise trade portfolios derived from UN Comtrade, where these are submitted with disaggregation by Transport Mode. Looking at the 16 countries of interest across African and Caribbean economies we're interested in the summer of 2026, 13 of these have a trade portfolio with MoT Breakdown available across at least one year within the last decade. Therefore this approach makes more sense, and 'v0.6' was amended to work with Comtrade import and export trade portfolios downloaded from the platform. 'v0.61' made use of the updated 'trade' notebooks that derive a new weight field using Value-to-Weight and Weight-to-Value ratios observed in the CEPII BACI datasets across 2017-23. In the case of Trinidad and Tobaogo, import volumes were around 65% higher under the WtV approach which corresponded to a 39% greater 2041 BAU impact from FEM costs, but this was slightly less for exports where the weighted WtV was 9% more but 2041 FEM costs under BAU were around 10% less. A new 'composite' weight field has been added in Trade (v0.61) which only introduces the VtW-derived values where 'netWgt' is observed to be zero, however this resulted in only a tiny increase in recorded weight of around 1% for Angola, whereas the full VtW-derived field was ~50% greater. 

'v0.62' makes use of a new 'transport cost' field derived using ad-valorem transport cost rates identified from UNCTAD's Trade-and-Transport database. With these, we can now introduce another results disaggregation that presents NZF costs relative to expected transport costs, which is then fully in-line with how impacts are expressed in UNCTAD's CIA Task 3 work. 'v0.63' includes an assessment of 'Cost Intensity' matching process (similar to CIF-FOB matching), plus metrics on 'fac_vessel_types' and 'average sea-distance' (introduced in Trade v0.63). 'v0.64' has been modified throughout to account for a new scenario, namely the 'Japan' proposal, plus to remove the 'Low-then-High' scenario. In terms of the Impact notebook, this remains the same as 'v0.63'.

In [1]:
# Import packages
import os
import ast
import base64
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 250)
pd.set_option('display.max_rows', 250)
pd.options.mode.chained_assignment = None
from IPython.display import HTML
import matplotlib.pyplot as plt
import matplotlib.style
plt.style.use('seaborn-v0_8')

def voyages_analysis(voys):
    # Define a function to analyses key statistics from a given set of voyages, 'voys'.
    print("Number of Voyages found: {0}".format(voys.shape[0]))
    print("Total size of the fleet: {0} vessels".format(len(voys.imo.unique())))
    print("{0} vessel types contained in the dataset: {1}".format(len(voys.vessel_type.unique()), voys.vessel_type.unique()))
    print("Total transport work capacity: {0} million deadweight-tonne nautical miles".format(np.round(voys.dwtnm.sum() / 1e6, 1)))
    print("Total cargo transported: {0} tonnes".format(np.round(voys.tonnes.sum(), 1)))
    print("Total transport work: {0} million tonne nautical miles".format(np.round(voys.tnm.sum() / 1e6, 1)))
    print("Average build year of the fleet: {0}".format(int(np.round(voys.year_of_built.mean(), 0))))
    print("Total Energy Demands: {0} EJ".format(np.round(voys.energy_tj.sum(), 1)))
    print("Total CO2 produced: {0} tonnes".format(np.round(voys.co2_t.sum(), 1)))

def get_usd_per_dwtnm(voys, field_name):
    # Derive the deadweight-average of the cost intensity (per unit of cargo-carrying capacity) for the field 'field_name' in an input selection of voyages, 'voys'.
    return (voys[field_name].values * voys.deadweight.values).sum() / voys.deadweight.sum()
    
def get_usd_per_tnm(voys, field_name):
    # Derive the deadweight-average of the cost intensity (per unit of cargo-carried) for the field 'field_name' in an input selection of voyages, 'voys'.
    return (voys[field_name].values / voys.class_util.values * voys.tonnes.values).sum() / voys.tonnes.sum()

def download_link(df, title = "Download CSV file", filename = "data.csv"):
    csv = df.to_csv()
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
    html = html.format(payload=payload,title=title,filename=filename)
    return HTML(html)

version = "v0.64"
input_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/"
voys_fem_dir = "/Users/apple/repos/datasets/ucl/fleet evolution model/2026 annex vi amendments (v0.2)/2. NZF Impact Costs for 2018 IMO IV Voyages/voys_fem_v0.2.csv"
output_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/impact/"
res_mlc = True

# 1. Set up the notebook

## 1.1 Let's set the country we're interested in and set up a results folder.

In [2]:
# Select one of our countries to work on...
iso_code = "780"
iso_country = "Trinidad and Tobago"
year = 2025
gdp = 25940e6

# Create output Journey directory folder if necessary
os.makedirs(output_dir+"{0}/".format(iso_country)) if not os.path.exists(output_dir+"{0}/".format(iso_country)) else "Output directory already exists."
os.makedirs(output_dir+"{0}/results/".format(iso_country)) if not os.path.exists(output_dir+"{0}/results/".format(iso_country)) else "Output results folder already exists."

## 1.2 Voyages with FEM Results

In [3]:
voys_fem_d = {
    "source_iso":str, "source_iso_code":str, "source_iso_3":str, "source_iso_2":str, 
    "dest_iso_code":str, "dest_iso_code":str, "dest_iso_3":str, "dest_iso_2":str, 
    "source_region_code":str, "source_sub_region_code":str, "dest_region_code":str, "dest_sub_region_code":str, 
    "source_ldc":str, "source_sids":str, "dest_ldc":str, "dest_sids":str
}

voys_fem = pd.read_csv(voys_fem_dir, dtype=voys_fem_d)
voys_fem["dwtnm"] = voys_fem.deadweight * voys_fem.dist_travelled_ais
voys_fem["tonnes"] = voys_fem.deadweight * voys_fem.class_util
voys_fem["tnm"] = voys_fem.tonnes * voys_fem.dist_travelled_ais
voys_fem.loc[voys_fem.source_country == "Namibia", "source_iso_2"] = "NA"
voys_fem.loc[voys_fem.dest_country == "Namibia", "dest_iso_2"] = "NA"

countries_set = pd.Series(list(set(list(voys_fem.source_country.unique()) + list(voys_fem.dest_country.unique())))).sort_values()
print("Number of countries present in dataset: {0}.".format(len(countries_set)))
print("Number of IMO numbers present in dataset: {0}.".format(len(voys_fem.imo.unique())))
print("Total CO2 contained within the dataset: {0} million tonnes.".format(np.round(voys_fem.co2_t.sum() / 1e6, 1)))
print("Vessel types present in dataset: \n\n{0}\n".format(pd.Series(voys_fem.vessel_type.unique()).sort_values().values))
#print("\nCountries in dataset: \n\n", countries_set.values, "\n")
voys_fem.head(2)

Number of countries present in dataset: 207.
Number of IMO numbers present in dataset: 26132.
Total CO2 contained within the dataset: 544.7 million tonnes.
Vessel types present in dataset:

['Bulk carrier' 'Chemical tanker' 'Container' 'General cargo'
 'Liquefied gas tanker' 'Oil tanker' 'Refrigerated bulk' 'Vehicle']

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,0,5034525,413781699,CNTAX,156,CHN,CN,China,Taixing,CNNKG,156,CHN,CN,China,Nanjing,2018-01-01 06:00:00,2018-01-01 19:00:00,13.0,1.0,14.0,62.568523,0.0,0.0,0.0,3.635661,0.338483,3.974144,0.0,0.0,0.0,0.0,0.0,0.0,0.155243,0.014453,11.655930,1.085176,12.741107,142,Asia,030,Eastern Asia,upp_mid_income,0,0,142,Asia,030,Eastern Asia,upp_mid_income,0,0,0.169696,Refrigerated bulk,3786.0,dwt,3881.0,NaN,NaN,NaN,NaN,2,2000-5999,1959.0,Panama,SSD,4,76.1,0.666667,0.03155,0.032676,0.032143,0.031676,0.031218,0.030769,0.03031,0.029878,0.029438,0.031576,0.052178,0.052414,0.05804,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.05942,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,242828.439338,7661.320668,7934.549945,7805.304846,7691.950531,7580.696290,7471.542086,7360.199865,7255.307537,7148.350725,7667.458038,12670.391275,12727.642802,14093.647297,14570.027623,14398.931835,14189.590704,14139.488873,14161.462401,7665.715352,8412.516422,8946.627490,10860.650719,12049.492896,13084.201484,14034.766615,14342.763237,14083.751009,7665.715352,7946.962662,8384.668998,9891.651071,11698.979626,13565.379532,13949.851660,14247.178318,14428.769963,7663.482493,7940.155892,8209.623358,9221.805242,9744.436151,10159.112402,10518.004352,10853.785659,11140.079340,7663.482493,8252.567981,8473.856677,8773.523328,9299.485535,9694.695953,9860.244395,9979.919640,10068.487874,2587.333335,161885.626306
1,1,5034525,413781699,CNNKG,156,CHN,CN,China,Nanjing,CNTOL,156,CHN,CN,China,Tongling,2018-01-01 20:00:00,2018-01-04 17:00:00,69.0,59.0,128.0,134.252308,0.0,0.0,0.0,21.355373,19.491146,40.846519,0.0,0.0,0.0,0.0,0.0,0.0,0.911874,0.832272,68.465325,62.488615,130.953940,142,Asia,030,Eastern Asia,upp_mid_income,0,0,142,Asia,030,Eastern Asia,upp_mid_income,0,0,1.744146,Refrigerated bulk,3786.0,dwt,3881.0,NaN,NaN,NaN,NaN,2,2000-5999,1959.0,Panama,SSD,4,76.1,0.666667,0.03155,0.032676,0.032143,0.031676,0.031218,0.030769,0.03031,0.029878,0.029438,0.031576,0.052178,0.052414,0.05804,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.05942,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,521033.206847,16438.776642,17025.040451,16747.721252,16504.498662,16265.782167,16031.571689,15792.666415,15567.600579,15338.105010,16451.945500,27186.661563,27309.505274,30240.519881,31262.681739,30895.564166,30446.384156,30338.881438,30386.029694,16448.206246,18050.605691,19196.639505,23303.529390,25854.409564,28074.567693,30114.180516,30775.044079,30219.285570,16448.206246,17051.674227,17990.853906,21224.361910,25102.318690,29107.023950,29931.979818,30569.949005,30959.587375,16443.415234,17037.069045,17615.261197,19787.084130,20908.485145,21798.249530,22568.318408,23288.799137,23903.095037,16443.415234,17707.406809,18182.222523,18825.212595,19953.761526,20801.758375,21156.973093,21413.758406,21603.797889,2587.333335,347355.471405

# 2. Let's consider Imports

## 2.1 Read-in Trade dataset

In [4]:
trade_im_d = {"reporterCode":"str", "partnerCode":"str", "partner2Code":"str", "cmdCode":"str", "HS2":"str", "HS4":"str"}
if res_mlc == False:
    trade_im = pd.read_csv(input_dir+"trade/{0}/trade_im_dist_{1}.csv".format(iso_country, version), dtype=trade_im_d)
else:
    trade_im = pd.read_csv(input_dir+"trade/{0}/trade_im_mlc_{1}.csv".format(iso_country, version), dtype=trade_im_d)
trade_im['fac_vessel_types'] = [ast.literal_eval(x) for x in trade_im.fac_vessel_types.values]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(trade_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_im.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(trade_im.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(trade_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_im.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_im.sea_dist_nm.min(), 1),
    round(trade_im.sea_dist_nm.max(), 1),
    round(trade_im.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_im.vol_kg_vtw / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_im.cifvalue / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.cifvalue.sum() / 1000), 1)
))
trade_im.head(2)

Aggregate trade portfolio statistics for 'Trinidad and Tobago':

Number of trade records present in dataset: 26201
Number of partner countries present in dataset: 165
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$5073.1m
Total weight within the dataset: 6395.2 million kilograms

Distance to market: 102.5 nm (min) to 13625.4 nm (max), 5987.0 nm (observed mean)
Average distance to market (volume-weighted): 3944.3 nm
Average distance to market (value-weighted): 5809.4 nm

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_im_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,TandT_match_desc,TandT_ad_val_pct,TandT_N,TandT_ciffob,TandT_cifvalue,TandT_fobvalue
0,0,780,Trinidad and Tobago,862,Venezuela,000,World,Import,Sea,392390 | Plastics; articles f,392390,kg,1.0,1.0,2.223,NaN,2.223,Venezuela | 392390 | Plastics; articles f,39,39 | Plastics and article,Venezuela | 39 | Plastics and article,3923,3923 | Plastic articles for,Venezuela | 3923 | Plastic articles for,39.0,3923.0,392390.0,"Articles for the conveyance/packing of goods, ...","Petroleum, Chemical and Non-Metallic Mineral P...",2520.0,Manufacture of plastics products,89319.0,"Articles for the conveyance/packing of goods, ...",33.0,"CRP - Chemical, rubber, plastic products",3649.0,Other articles for the conveyance or packing o...,3.7874,0.2640,both,0.449843,0.586872,1.0,[Container],['Container'],631.0,392.085101,0.230104,"1 - Reporter, Partner and HS4 code",16.17,1,0.31,2.22,1.91
1,1,780,Trinidad and Tobago,862,Venezuela,000,World,Import,Sea,"482390 | Paper pulp, paper, p",482390,kg,1.0,1.0,2.075,NaN,2.075,"Venezuela | 482390 | Paper pulp, paper, p",48,48 | Paper and paperboard,Venezuela | 48 | Paper and paperboard,4823,"4823 | Paper, paperboard, c","Venezuela | 4823 | Paper, paperboard, c",48.0,4823.0,482390.0,"Paper, paperboard, cellulose wadding&webs of c...",Wood and Paper,2109.0,Manufacture of other articles of paper and pap...,64299.0,"Other paper, paperboard, cellulose wadding/web...",31.0,"PPP - Paper products, publishing",32199.0,"Other paper, paperboard, cellulose wadding and...",2.7744,0.3604,both,0.481928,0.747830,1.0,[all],['all'],631.0,392.085101,0.293213,"1 - Reporter, Partner and HS4 code",2.82,1,0.06,2.08,2.02

## 2.2 Derive Internationally Arriving Voyages

In [5]:
# International Arrivals
int_arr_voys = voys_fem[(voys_fem.dest_country == iso_country) & (voys_fem.source_country != iso_country)].reset_index(drop=True)
int_arr_voys.to_csv(output_dir + "{0}/int_arr_voys_{1}.csv".format(iso_country, version), index=False)
int_dep_voys = voys_fem[(voys_fem.source_country == iso_country) & (voys_fem.dest_country != iso_country)].reset_index(drop=True)
int_dep_voys.to_csv(output_dir + "{0}/int_dep_voys_{1}.csv".format(iso_country, version), index=False)
voyages_analysis(int_arr_voys)
int_arr_voys.head(2)

Number of Voyages found: 2284
Total size of the fleet: 929 vessels
8 vessel types contained in the dataset: ['General cargo' 'Bulk carrier' 'Chemical tanker' 'Vehicle' 'Container'
 'Oil tanker' 'Refrigerated bulk' 'Liquefied gas tanker']
Total transport work capacity: 241253.0 million deadweight-tonne nautical miles
Total cargo transported: 53448927.5 tonnes
Total transport work: 137094.3 million tonne nautical miles
Average build year of the fleet: 2008
Total Energy Demands: 22245.7 EJ
Total CO2 produced: 1567169.9 tonnes

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,5451,7382859,377995000,AIRBY,660,AIA,AI,Anguilla,Road Bay,TTPOS,780,TTO,TT,Trinidad and Tobago,Port Of Spain,2018-01-16 07:00:00,2018-01-18 21:00:00,62.0,288.0,350.0,522.540893,0.0,0.0,0.0,5.550589,24.651939,30.202528,0.0,0.0,0.0,0.0,0.0,0.0,0.237010,1.052638,17.795189,79.034116,96.829306,019,Americas,419,Latin America and the Caribbean,high_income,0,1,019,Americas,419,Latin America and the Caribbean,high_income,0,1,1.289648,General cargo,413.0,dwt,639.390272,NaN,NaN,NaN,NaN,2,5000-9999,1974.0,St Vincent & The Grenadines,MSD,4,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.02233,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.01858,0.018382,0.01842,0.013244,0.01391,0.014148,0.014473,0.01505,0.015474,0.015636,0.015745,0.015819,334107.563361,4425.236834,4530.803446,4480.867482,4437.071184,4394.086283,4351.912766,4308.893872,4268.367001,4227.042483,4424.727649,6345.339633,6254.860270,6700.433946,7418.820156,7345.607599,7118.044764,6716.620464,6467.863650,4424.534955,4702.483813,4819.044386,5531.633148,6091.486713,7168.523593,7040.266011,6910.582909,6489.867658,4424.534955,4524.588803,4681.411004,5232.709759,5884.338061,7460.780255,7215.819777,7274.859023,7199.726997,4424.871445,4527.449242,4625.922507,5006.741694,5147.848598,5494.930546,6207.798851,6141.568884,6154.137085,4424.871445,4647.313975,4727.031927,4835.624418,5028.43362,5169.985596,5224.159371,5260.620124,5285.106176,409.037548,213738.845338
1,5457,7382859,377995000,VCKTN,670,VCT,VC,Saint Vincent and the Grenadines,Kingstown,TTPOS,780,TTO,TT,Trinidad and Tobago,Port Of Spain,2018-03-12 17:00:00,2018-03-13 16:00:00,23.0,631.0,654.0,172.791231,0.0,0.0,0.0,2.038672,54.013709,56.052381,0.0,0.0,0.0,0.0,0.0,0.0,0.087051,2.306385,6.535983,173.167952,179.703935,019,Americas,419,Latin America and the Caribbean,upp_mid_income,0,1,019,Americas,419,Latin America and the Caribbean,high_income,0,1,2.393437,General cargo,413.0,dwt,639.390272,NaN,NaN,NaN,NaN,2,5000-9999,1974.0,St Vincent & The Grenadines,MSD,4,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.02233,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.01858,0.018382,0.01842,0.013244,0.01391,0.014148,0.014473,0.01505,0.015474,0.015636,0.015745,0.015819,110481.031994,1463.315369,1498.223612,1481.711035,1467.228693,1453.014659,1439.068929,1424.843655,1411.442430,1397.777443,1463.146994,2098.245439,2068.326172,2215.666266,2453.218654,2429.009089,2353.759740,2221.018743,2138.761074,1463.083275,1554.994025,1593.537697,1829.173014,2014.302615,2370.451828,2328.040247,2285.157282,2146.037250,1463.083275,1496.168585,1548.025773,1730.326511,1945.803726,2467.093812,2386.091496,2405.614301,2380.770015,1463.194543,1497.114461,1529.677111,1655.604512,1702.265043,1817.036380,2052.764135,2030.863539,2035.019529,1463.194543,1536.750736,1563.111473,1599.020300,1662.77749,1709.585195,1727.499111,1739.555772,1747.652698,409.037548,70678.101305

## 2.3 Evaluate NZF Costs

In [6]:
years=["26", "29", "32", "35", "38", "41", "44", "47", "50"]
vess_types_not_found_in_inventories, vess_types_not_found_in_global_voys, hs_codes_not_mapped_to_HS, cost_int_match_desc, cost_int_match_desc_bool = [], [], [], [], False

for year in years:

    print("Processing game year 20{0}".format(year))

    # Setup columns for policy costs per bilateral goods trade.
    bau_usd, levy_usd, asis_usd, brazil_usd, liscr_usd, direct_usd = [], [], [], [], [], []
    
    for trade_idx, trade in trade_im.iterrows():

        # initiate selected voyages table as empty dataframe to begin
        int_arr_voys_vess = pd.DataFrame()

        # 3. If no facilitating vessel types were picked up for the HS code, take from full primary int. inv. voyages dataset, otherwise move on...
        if 'all' in trade.fac_vessel_types:
            hs_codes_not_mapped_to_HS.append(trade.HS4_desc)
            int_arr_voys_vess = int_arr_voys
            cost_int_match_desc.append("3. Primary Int. Inv. without Vess Type") if cost_int_match_desc_bool == False else None

        else:
            # 1. If possible, derive subset of voyages associated with the unique vessel type.
            int_arr_voys_vess = int_arr_voys[(int_arr_voys.vessel_type.isin(trade.fac_vessel_types))]    
            
            if int_arr_voys_vess.shape[0] > 0:
                cost_int_match_desc.append("1. Primary Int. Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                
            else:
                # 2. Finally, if no voyages are found as the vessel type doesn't appear in the country's shipping inventories, also take from full voyages dataset filtered for those vessel types instead.
                int_arr_voys_vess = voys_fem[(voys_fem.vessel_type.isin(trade.fac_vessel_types))]

                if int_arr_voys_vess.shape[0] > 0:
                    cost_int_match_desc.append("2. Global Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_inventories.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

                else:
                    # 4. Use full global voyage dataset as a back-up
                    int_arr_voys_vess = voys_fem
                    cost_int_match_desc.append("4. Global Inv. without Vess Type.") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_global_voys.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

        # Add cost intensities associated with the subset of voyages by vessel type, assuming 50% of NZF costs are borne by the importer.
        bau_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "bau35_usd_dwtnm_"+year))
        levy_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "levy35_usd_dwtnm_"+year))
        asis_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "asis35_usd_dwtnm_"+year))
        brazil_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "brazil35_usd_dwtnm_"+year))
        liscr_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "liscr35_usd_dwtnm_"+year))
        direct_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "direct35_usd_dwtnm_"+year))
    
    if cost_int_match_desc_bool == False:
        trade_im["cost_int_match_desc"] = cost_int_match_desc
    cost_int_match_desc_bool = True
    
    trade_im["bau_usd_"+year] = bau_usd
    trade_im["levy_usd_"+year] = levy_usd
    trade_im["asis_usd_"+year] = asis_usd
    trade_im["brazil_usd_"+year] = brazil_usd
    trade_im["liscr_usd_"+year] = liscr_usd
    trade_im["direct_usd_"+year] = direct_usd

print("Inventory voyages table used for the following vessel types: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_inventories).unique()))
print("Global voyages table used for the following vessel types found: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_global_voys).unique()))
print("Global voyages table used for the following commodities as no 'facilitating vessel types' were identified: \n\n{0}\n".format(pd.Series(hs_codes_not_mapped_to_HS).unique()))

print("\nNumber of trade records present in dataset: {0}".format(trade_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_im.partnerCode.unique())))
print("\nTotal value of trade: US${0}m".format(np.round(trade_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_im.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_im.sea_dist_nm.min(), 1),
    round(trade_im.sea_dist_nm.max(), 1),
    round(trade_im.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_im.vol_kg_vtw / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_im.cifvalue / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.cifvalue.sum() / 1000), 1)
))

print("\n\nTotal FEM costs in 2041...\n")
print("BAU: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.bau_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.bau_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Levy: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.levy_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.levy_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("'as-is': US${0}m ({1}% ad-val)".format(
    np.round(trade_im.asis_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.asis_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Brazil: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.brazil_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.brazil_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("LISCR: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.liscr_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.liscr_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Direct: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.direct_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.direct_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))

trade_im_agg = trade_im.groupby(["cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "cifvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_im_agg["vol_kg_vtw_pct"] = round(100 * trade_im_agg.vol_kg_vtw / trade_im_agg.vol_kg_vtw.sum(), 1)
trade_im_agg["cifvalue_pct"] = round(100 * trade_im_agg.cifvalue / trade_im_agg.cifvalue.sum(), 1)
print("Most prominent 'cost intensity match' types...\n\n{0}\n".format(
    trade_im_agg[["cost_int_match_desc", "vol_kg_vtw_pct", "cifvalue_pct"]].head(5)
))
trade_im_agg_2 = trade_im.groupby(["fac_vessel_types_str", "cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "cifvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_im_agg_2["vol_kg_vtw_pct"] = round(100 * trade_im_agg_2.vol_kg_vtw / trade_im_agg_2.vol_kg_vtw.sum(), 1)
trade_im_agg_2["cifvalue_pct"] = round(100 * trade_im_agg_2.cifvalue / trade_im_agg_2.cifvalue.sum(), 1)
print("Most prominent 'facilitating vessel types' and their 'cost intensity match' types...")
display(trade_im_agg_2[["fac_vessel_types_str", "cost_int_match_desc", "vol_kg_vtw_pct", "cifvalue_pct"]].head(5))

trade_im_na = trade_im[(trade_im[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (trade_im.fac_vessel_types.str.len() == 0)]
trade_im = trade_im[(~trade_im[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (~trade_im.fac_vessel_types.str.len() == 0)]
print("Rows with NA: ${0} ({1}%)\n".format(trade_im_na.primaryValue.sum(), round(100 * trade_im_na.primaryValue.sum() / trade_im.primaryValue.sum(), 1)))

trade_im.to_csv(output_dir + "{0}/impact_im_{1}.csv".format(iso_country, version), index=False)
trade_im.head(2)

Processing game year 2026
Processing game year 2029
Processing game year 2032
Processing game year 2035
Processing game year 2038
Processing game year 2041
Processing game year 2044
Processing game year 2047
Processing game year 2050
Inventory voyages table used for the following vessel types:

[]

Global voyages table used for the following vessel types found:

['Cruise' 'Other liquids tankers' 'Ro-Ro']

Global voyages table used for the following commodities as no 'facilitating vessel types' were identified:

['4823 | Paper, paperboard, c' '7419 | Copper; articles the'
 '4905 | Maps and hydrographi' '6704 | Wigs, false beards, '
 '6815 | Stone or other miner' '1806 | Chocolate and other '
 '9620 | Monopods, bipods, tr' '7508 | Nickel; articles the'
 '8517 | Telephone sets, incl' '4420 | Wood marquetry and i'
 '4911 | Printed matter, n.e.' '3307 | Perfumery, cosmetic '
 '4419 | Tableware and kitche' '7616 | Aluminium; articles '
 '6310 | Rags; used or new, s' '8215 | Cutlery; spoons, for'
 '9209 | Musical instrument p' '7326 | Iron or steel; artic'
 '9401 | Seats (not those of ' '8487 | Machinery parts; not'
 '5911 | Textile products and' '2106 | Food preparations no'
 '3402 | Organic surface-acti' '2853 | Phosphides, chemical'
 '4504 | Agglomerated cork (w' '8311 | Wires, rods, tubes, '
 '4421 | Wooden articles n.e.' '3105 | Fertilizers; mineral'
 '4707 | Waste and scrap of p' '1008 | Buckwheat, millet an'
 '3006 | Pharmaceutical goods' '6406 | Footwear; parts of f'
 '0307 | Molluscs; whether in' '3824 | Prepared binders for'
 '3907 | Polyacetals, other p' '0714 | Manioc, arrowroot, s'
 '3603 | Safety fuses; detona' '1605 | Crustaceans, mollusc'
 '7019 | Glass fibres (includ' '0403 | Yogurt; buttermilk, '
 '4414 | Wooden frames; for p' '0306 | Crustaceans; in shel'
 '1905 | Bread, pastry, cakes' '2309 | Preparations of a ki'
 '3507 | Enzymes; prepared en' '3926 | Articles of plastics'
 '0303 | Fish; frozen, exclud' '0910 | Ginger, saffron, tum'
 '1704 | Sugar confectionery ' "4418 | Builders' joinery an"
 '8716 | Trailers and semi-tr' '9406 | Buildings; prefabric'
 '3822 | Reagents; diagnostic' '5502 | Artificial filament '
 '3707 | Chemical preparation' '7229 | Wire of other alloy '
 '9403 | Furniture and parts ' '8708 | Motor vehicles; part'
 '9701 | Paintings, drawings ' '3909 | Amino-resins, phenol'
 '3215 | Ink; printing, writi' '3004 | Medicaments; (not go'
 '2530 | Mineral substances n' '4602 | Basketwork, wickerwo'
 '2621 | Slag and ash n.e.c. ' '6914 | Ceramic articles; n.'
 '3812 | Prepared rubber acce' '8109 | Zirconium; articles '
 '2009 | Fruit or nut juices ' '9405 | Luminaires and light'
 '0511 | Animal products not ' '3606 | Ferro-cerium and oth'
 '0802 | Nuts (excluding coco' '3901 | Polymers of ethylene'
 '2812 | Halides and halide o' '6217 | Clothing accessories'
 '2903 | Halogenated derivati' '0604 | Foliage, branches an'
 '9508 | Travelling circuses ' '2914 | Ketones and quinones'
 '4401 | Fuel wood, in logs, ' '6603 | Trimmings, parts and'
 '3808 | Insecticides, rodent' '2932 | Heterocyclic compoun'
 '6304 | Furnishing articles;' '9114 | Clock or watch parts'
 '8103 | Tantalum; articles t' '1214 | Swedes, mangolds, fo'
 '1404 | Vegetable products n' '2922 | Oxygen-function amin'
 '2935 | Sulphonamides' '0709 | Vegetables; n.e.c. i'
 '3002 | Human blood; animal ' '3003 | Medicaments; (not go'
 '4015 | Articles of apparel ' '4412 | Plywood, veneered pa'
 '6006 | Fabrics; knitted or ' '5007 | Woven fabrics of sil'
 '5516 | Woven fabrics of art' '5802 | Fabrics; terry towel'
 '6005 | Fabrics; warp knit (' '1509 | Olive oil and its fr'
 '1510 | Vegetable oils; oils' '6117 | Clothing accessories'
 '9703 | Sculptures and statu' '8903 | Yachts and other ves'
 '9404 | Mattress supports; a' '9027 | Instruments and appa'
 '8528 | Monitors and project' '6201 | Overcoats, car-coats'
 '8541 | Semiconductor device' '4011 | New pneumatic tyres,'
 '8703 | Motor cars and other' '8525 | Transmission apparat'
 '8539 | Lamps; electric fila' '8424 | Mechanical appliance'
 "6202 | Coats; women's or gi" '8421 | Centrifuges, includi'
 '8701 | Tractors; (other tha' '8514 | Industrial or labora'
 '8456 | Machine-tools; for w' '8711 | Motorcycles (includi'
 '8462 | Machine-tools (inclu' '8419 | Machinery, plant (no'
 '8432 | Agricultural, hortic' '8459 | Machine-tools; (incl'
 '8501 | Electric motors and ' '8704 | Vehicles; for the tr'
 '8414 | Air or vacuum pumps,' '8702 | Vehicles; public tra'
 '9702 | Engravings, prints a' '5703 | Carpets and other te'
 '4407 | Wood sawn or chipped' '6907 | Ceramic flags and pa'
 '4403 | Wood in the rough, w' '2202 | Waters, including mi'
 '2204 | Wine of fresh grapes' '8460 | Machine-tools; for d']


Number of trade records present in dataset: 26201
Number of partner countries present in dataset: 165

Total value of trade: US$5073.1m
Total weight within the dataset: 6395.2 million kilograms

Distance to market: 102.5 nm (min) to 13625.4 nm (max), 5987.0 nm (observed mean)
Average distance to market (volume-weighted): 3944.3 nm
Average distance to market (value-weighted): 5809.4 nm


Total FEM costs in 2041...

BAU: US$83.5m (1.6% ad-val)
Levy: US$173.0m (3.4% ad-val)
'as-is': US$164.6m (3.2% ad-val)
Brazil: US$169.6m (3.3% ad-val)
LISCR: US$117.4m (2.3% ad-val)
Direct: US$109.5m (2.2% ad-val)
Most prominent 'cost intensity match' types...

                      cost_int_match_desc  vol_kg_vtw_pct  cifvalue_pct
0     1. Primary Int. Inv. with Vess Type            96.3          85.7
1  3. Primary Int. Inv. without Vess Type             3.7          14.3
2       4. Global Inv. without Vess Type.             0.0           0.0

Most prominent 'facilitating vessel types' and their 'cost intensity match' types...

,fac_vessel_types_str,cost_int_match_desc,vol_kg_vtw_pct,cifvalue_pct
0,['Bulk carrier'],1. Primary Int. Inv. with Vess Type,59.1,8.4
1,['Container'],1. Primary Int. Inv. with Vess Type,24.0,61.7
2,"['Container', 'Bulk carrier']",1. Primary Int. Inv. with Vess Type,4.2,2.7
3,['all'],3. Primary Int. Inv. without Vess Type,3.7,14.3
4,['Chemical tanker'],1. Primary Int. Inv. with Vess Type,2.4,1.6

Rows with NA: $0.0 (0.0%)

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_im_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,TandT_match_desc,TandT_ad_val_pct,TandT_N,TandT_ciffob,TandT_cifvalue,TandT_fobvalue,cost_int_match_desc,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50
0,0,780,Trinidad and Tobago,862,Venezuela,000,World,Import,Sea,392390 | Plastics; articles f,392390,kg,1.0,1.0,2.223,NaN,2.223,Venezuela | 392390 | Plastics; articles f,39,39 | Plastics and article,Venezuela | 39 | Plastics and article,3923,3923 | Plastic articles for,Venezuela | 3923 | Plastic articles for,39.0,3923.0,392390.0,"Articles for the conveyance/packing of goods, ...","Petroleum, Chemical and Non-Metallic Mineral P...",2520.0,Manufacture of plastics products,89319.0,"Articles for the conveyance/packing of goods, ...",33.0,"CRP - Chemical, rubber, plastic products",3649.0,Other articles for the conveyance or packing o...,3.7874,0.2640,both,0.449843,0.586872,1.0,[Container],['Container'],631.0,392.085101,0.230104,"1 - Reporter, Partner and HS4 code",16.17,1,0.31,2.22,1.91,1. Primary Int. Inv. with Vess Type,0.001105,0.001103,0.001103,0.001103,0.001104,0.001104,0.001157,0.002071,0.001276,0.001183,0.001187,0.001217,0.001132,0.002018,0.001341,0.001229,0.001201,0.001256,0.001111,0.002202,0.001666,0.001456,0.001347,0.00131,0.001090,0.002340,0.001917,0.001795,0.001439,0.001405,0.001069,0.002374,0.002264,0.002286,0.001560,0.001476,0.001048,0.002326,0.002228,0.002428,0.001801,0.001503,0.001028,0.002073,0.002156,0.002258,0.001689,0.001521,0.001008,0.001898,0.001931,0.002378,0.001965,0.001532
1,1,780,Trinidad and Tobago,862,Venezuela,000,World,Import,Sea,"482390 | Paper pulp, paper, p",482390,kg,1.0,1.0,2.075,NaN,2.075,"Venezuela | 482390 | Paper pulp, paper, p",48,48 | Paper and paperboard,Venezuela | 48 | Paper and paperboard,4823,"4823 | Paper, paperboard, c","Venezuela | 4823 | Paper, paperboard, c",48.0,4823.0,482390.0,"Paper, paperboard, cellulose wadding&webs of c...",Wood and Paper,2109.0,Manufacture of other articles of paper and pap...,64299.0,"Other paper, paperboard, cellulose wadding/web...",31.0,"PPP - Paper products, publishing",32199.0,"Other paper, paperboard, cellulose wadding and...",2.7744,0.3604,both,0.481928,0.747830,1.0,[all],['all'],631.0,392.085101,0.293213,"1 - Reporter, Partner and HS4 code",2.82,1,0.06,2.08,2.02,3. Primary Int. Inv. without Vess Type,0.001130,0.001129,0.001129,0.001129,0.001129,0.001133,0.001149,0.001873,0.001214,0.001155,0.001157,0.001190,0.001127,0.001810,0.001263,0.001192,0.001163,0.001213,0.001112,0.001993,0.001497,0.001371,0.001280,0.00126,0.001097,0.002203,0.001758,0.001652,0.001345,0.001341,0.001081,0.002192,0.002070,0.002139,0.001436,0.001403,0.001064,0.002104,0.002036,0.002182,0.001712,0.001425,0.001048,0.001932,0.001982,0.002115,0.001683,0.001458,0.001029,0.001780,0.001824,0.002101,0.001741,0.001466

## 2.4 Create Results Tables

### 2.4.1 Total Costs per Scenario

In [7]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        np.round(trade_im["bau_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["levy_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["asis_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["brazil_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["liscr_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["direct_usd_{0}".format(year)].sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% cif)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% fob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_fob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_im["bau_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["levy_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["asis_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["direct_usd_{0}".format(year)].sum() / gdp, 3),
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,BAU,8.922283e+07,8.760361e+07,8.620564e+07,8.483262e+07,8.348562e+07,8.210636e+07,8.080885e+07,7.947350e+07
1,Levy,1.483688e+08,1.439604e+08,1.578735e+08,1.714371e+08,1.730202e+08,1.663012e+08,1.516712e+08,1.408332e+08
2,'as-is',9.564786e+07,9.965404e+07,1.209778e+08,1.389562e+08,1.646088e+08,1.602403e+08,1.561094e+08,1.441485e+08
3,Brazil,8.982703e+07,9.349578e+07,1.093072e+08,1.310743e+08,1.696039e+08,1.719725e+08,1.668093e+08,1.690122e+08
4,LISCR,9.012914e+07,9.184290e+07,1.023923e+08,1.081206e+08,1.173949e+08,1.342916e+08,1.298661e+08,1.407873e+08
5,Direct,9.292903e+07,9.534760e+07,9.878206e+07,1.049152e+08,1.094540e+08,1.111239e+08,1.122791e+08,1.131236e+08

Total FEM costs by scenario (% ciffob)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  20.28  19.91  19.59  19.28  18.97  18.66  18.36  18.06
1     Levy  33.72  32.72  35.88  38.96  39.32  37.79  34.47  32.01
2  'as-is'  21.74  22.65  27.49  31.58  37.41  36.42  35.48  32.76
3   Brazil  20.41  21.25  24.84  29.79  38.54  39.08  37.91  38.41
4    LISCR  20.48  20.87  23.27  24.57  26.68  30.52  29.51  31.99
5   Direct  21.12  21.67  22.45  23.84  24.87  25.25  25.52  25.71

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0      BAU  1.76  1.73  1.70  1.67  1.65  1.62  1.59  1.57
1     Levy  2.92  2.84  3.11  3.38  3.41  3.28  2.99  2.78
2  'as-is'  1.89  1.96  2.38  2.74  3.24  3.16  3.08  2.84
3   Brazil  1.77  1.84  2.15  2.58  3.34  3.39  3.29  3.33
4    LISCR  1.78  1.81  2.02  2.13  2.31  2.65  2.56  2.78
5   Direct  1.83  1.88  1.95  2.07  2.16  2.19  2.21  2.23

Total FEM costs by scenario (% fob)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0      BAU  1.93  1.89  1.86  1.83  1.80  1.77  1.74  1.72
1     Levy  3.20  3.11  3.41  3.70  3.73  3.59  3.27  3.04
2  'as-is'  2.06  2.15  2.61  3.00  3.55  3.46  3.37  3.11
3   Brazil  1.94  2.02  2.36  2.83  3.66  3.71  3.60  3.65
4    LISCR  1.95  1.98  2.21  2.33  2.53  2.90  2.80  3.04
5   Direct  2.01  2.06  2.13  2.26  2.36  2.40  2.42  2.44

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  0.344  0.338  0.332  0.327  0.322  0.317  0.312  0.306
1     Levy  0.572  0.555  0.609  0.661  0.667  0.641  0.585  0.543
2  'as-is'  0.369  0.384  0.466  0.536  0.635  0.618  0.602  0.556
3   Brazil  0.346  0.360  0.421  0.505  0.654  0.663  0.643  0.652
4    LISCR  0.347  0.354  0.395  0.417  0.453  0.518  0.501  0.543
5   Direct  0.358  0.368  0.381  0.404  0.422  0.428  0.433  0.436

### 2.4.2 Costs per Scenario relative to BAU

In [8]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        np.round((trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_usd_bau_{1}.csv".format(iso_country, version), index=False)
display(df)

print("\nTotal change in FEM costs by scenario (% bau)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        round((100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2)
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_bau_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% cif)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2)
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% fob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_fob_{1}.csv".format(iso_country, version), index=False)
    display(df)
    
print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3)
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,Levy,59145973.53,56356815.22,71667834.03,86604437.06,89534614.08,84194803.46,70862382.56,61359661.39
1,'as-is',6425033.78,12050426.22,34772111.03,54123628.79,81123141.77,78133930.14,75300587.49,64675026.39
2,Brazil,604200.35,5892167.90,23101510.05,46241682.37,86118263.87,89866167.80,86000403.58,89538647.47
3,LISCR,906311.03,4239283.06,16186657.13,23287968.34,33909291.32,52185196.93,49057271.39,61313825.46
4,Direct,3706201.96,7743989.87,12576415.35,20082550.65,25968364.29,29017568.72,31470266.81,33650062.08

Total change in FEM costs by scenario (% bau)...

  Scenario   2029   2032   2035    2038    2041    2044    2047    2050
0     Levy  66.29  64.33  83.14  102.09  107.25  102.54   87.69   77.21
1  'as-is'   4.15   8.84  14.59   23.67   31.11   35.34   38.94   42.34
2   Brazil   7.20  13.76  40.34   63.80   97.17   95.16   93.18   81.38
3    LISCR   0.68   6.73  26.80   54.51  103.15  109.45  106.42  112.66
4   Direct   1.02   4.84  18.78   27.45   40.62   63.56   60.71   77.15

Total FEM costs by scenario (% ciffob)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  13.44  12.81  16.29  19.68  20.35  19.13  16.10  13.94
1  'as-is'   0.84   1.76   2.86   4.56   5.90   6.59   7.15   7.65
2   Brazil   1.46   2.74   7.90  12.30  18.44  17.76  17.11  14.70
3    LISCR   0.14   1.34   5.25  10.51  19.57  20.42  19.54  20.35
4   Direct   0.21   0.96   3.68   5.29   7.71  11.86  11.15  13.93

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0     Levy  1.17  1.11  1.41  1.71  1.76  1.66  1.40  1.21
1  'as-is'  0.07  0.15  0.25  0.40  0.51  0.57  0.62  0.66
2   Brazil  0.13  0.24  0.69  1.07  1.60  1.54  1.48  1.27
3    LISCR  0.01  0.12  0.46  0.91  1.70  1.77  1.70  1.76
4   Direct  0.02  0.08  0.32  0.46  0.67  1.03  0.97  1.21

Total FEM costs by scenario (% fob)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0     Levy  1.28  1.22  1.55  1.87  1.93  1.82  1.53  1.32
1  'as-is'  0.08  0.17  0.27  0.43  0.56  0.63  0.68  0.73
2   Brazil  0.14  0.26  0.75  1.17  1.75  1.69  1.63  1.40
3    LISCR  0.01  0.13  0.50  1.00  1.86  1.94  1.86  1.93
4   Direct  0.02  0.09  0.35  0.50  0.73  1.13  1.06  1.32

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  0.228  0.217  0.276  0.334  0.345  0.325  0.273  0.237
1  'as-is'  0.014  0.030  0.048  0.077  0.100  0.112  0.121  0.130
2   Brazil  0.025  0.046  0.134  0.209  0.313  0.301  0.290  0.249
3    LISCR  0.002  0.023  0.089  0.178  0.332  0.346  0.332  0.345
4   Direct  0.003  0.016  0.062  0.090  0.131  0.201  0.189  0.236

# 3. Let's consider Exports

## 3.1 Read-in Trade dataset

In [9]:
trade_ex_d = {"reporterCode":"str", "partnerCode":"str", "partner2Code":"str", "cmdCode":"str", "HS2":"str", "HS4":"str"}
if res_mlc == False:
    trade_ex = pd.read_csv(input_dir+"trade/{0}/trade_ex_dist_{1}.csv".format(iso_country, version), dtype=trade_ex_d)
else:
    trade_ex = pd.read_csv(input_dir+"trade/{0}/trade_ex_mlc_{1}.csv".format(iso_country, version), dtype=trade_ex_d)
trade_ex['fac_vessel_types'] = [ast.literal_eval(x) for x in trade_ex.fac_vessel_types.values]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(trade_ex.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_ex.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(trade_ex.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(trade_ex.fobvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_ex.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_ex.sea_dist_nm.min(), 1),
    round(trade_ex.sea_dist_nm.max(), 1),
    round(trade_ex.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_ex.vol_kg_vtw / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_ex.fobvalue / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.fobvalue.sum() / 1000), 1)
))
trade_ex.head(2)

Aggregate trade portfolio statistics for 'Trinidad and Tobago':

Number of trade records present in dataset: 7586
Number of partner countries present in dataset: 94
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$7166.1m
Total weight within the dataset: 14542.7 million kilograms

Distance to market: 101.3 nm (min) to 13626.0 nm (max), 966.5 nm (observed mean)
Average distance to market (volume-weighted): 4077.4 nm
Average distance to market (value-weighted): 4133.0 nm

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_ex_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,TandT_match_desc,TandT_ad_val_pct,TandT_N,TandT_ciffob,TandT_cifvalue,TandT_fobvalue
0,0,780,Trinidad and Tobago,308,Grenada,000,World,Domestic Export,Sea,690410 | Ceramic building bri,690410,1000u,11.022,1632.0,NaN,2802.073,2802.073,Grenada | 690410 | Ceramic building bri,69,69 | Ceramic products,Grenada | 69 | Ceramic products,6904,6904 | Ceramic building bri,Grenada | 6904 | Ceramic building bri,69.0,6904.0,690410.0,Ceramic building bricks,Mining and Quarrying,2693.0,Manufacture of structural non-refractory clay ...,66241.0,"Ceramic building bricks, flooring blocks, supp...",34.0,NMM - Mineral products n.e.c.,3735.0,"Non-refractory ceramic building bricks, floori...",0.211,4.7399,both,0.582426,13281.545813,1632.0,[Container],['Container'],163.0,101.283473,1345.201087,"2 - Reporter, Partner and HS2 code",5.57,1,156.08,2958.15,2802.07
1,1,780,Trinidad and Tobago,328,Guyana,000,World,Domestic Export,Sea,690410 | Ceramic building bri,690410,1000u,467.860,956334.0,NaN,118941.563,118941.563,Guyana | 690410 | Ceramic building bri,69,69 | Ceramic products,Guyana | 69 | Ceramic products,6904,6904 | Ceramic building bri,Guyana | 6904 | Ceramic building bri,69.0,6904.0,690410.0,Ceramic building bricks,Mining and Quarrying,2693.0,Manufacture of structural non-refractory clay ...,66241.0,"Ceramic building bricks, flooring blocks, supp...",34.0,NMM - Mineral products n.e.c.,3735.0,"Non-refractory ceramic building bricks, floori...",0.211,4.7399,both,8.040369,563771.114464,956334.0,[Container],['Container'],693.0,430.610103,242765.537668,3 - Reporter and HS4 code,8.17,2,9717.53,128659.09,118941.56

## 3.2 Derive Internationally Departing Voyages

In [10]:
# International Departures
int_arr_voys = voys_fem[(voys_fem.dest_country == iso_country) & (voys_fem.source_country != iso_country)].reset_index(drop=True)
int_arr_voys.to_csv(output_dir + "{0}/int_arr_voys_{1}.csv".format(iso_country, version), index=False)
int_dep_voys = voys_fem[(voys_fem.source_country == iso_country) & (voys_fem.dest_country != iso_country)].reset_index(drop=True)
int_dep_voys.to_csv(output_dir + "{0}/int_dep_voys_{1}.csv".format(iso_country, version), index=False)
voyages_analysis(int_dep_voys)
int_dep_voys.head(2)

Number of Voyages found: 2286
Total size of the fleet: 925 vessels
8 vessel types contained in the dataset: ['General cargo' 'Bulk carrier' 'Chemical tanker' 'Vehicle' 'Container'
 'Oil tanker' 'Refrigerated bulk' 'Liquefied gas tanker']
Total transport work capacity: 327280.1 million deadweight-tonne nautical miles
Total cargo transported: 53269883.4 tonnes
Total transport work: 182669.6 million tonne nautical miles
Average build year of the fleet: 2008
Total Energy Demands: 28083.3 EJ
Total CO2 produced: 1950703.9 tonnes

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,5452,7382859,377995000,TTPOS,780,TTO,TT,Trinidad and Tobago,Port Of Spain,VCKTN,670,VCT,VC,Saint Vincent and the Grenadines,Kingstown,2018-01-30 21:00:00,2018-02-22 19:00:00,550.0,182.0,732.0,190.274847,0.0,0.0,0.0,46.890472,15.556372,62.446844,0.0,0.0,0.0,0.0,0.0,0.0,2.002223,0.664257,150.330853,49.873728,200.204581,019,Americas,419,Latin America and the Caribbean,high_income,0,1,019,Americas,419,Latin America and the Caribbean,upp_mid_income,0,1,2.666480,General cargo,413.0,dwt,639.390272,NaN,NaN,NaN,NaN,2,5000-9999,1974.0,St Vincent & The Grenadines,MSD,4,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.02233,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.01858,0.018382,0.01842,0.013244,0.01391,0.014148,0.014473,0.01505,0.015474,0.015636,0.015745,0.015819,121659.886060,1611.378694,1649.819075,1631.635698,1615.687981,1600.035722,1584.678916,1569.014279,1554.257072,1539.209414,1611.193282,2310.553191,2277.606589,2439.855064,2701.443828,2674.784655,2591.921315,2445.749124,2355.168338,1611.123116,1712.333714,1754.777369,2014.255085,2218.116741,2610.302367,2563.599435,2516.377423,2363.180743,1611.123116,1647.556113,1704.660390,1905.406949,2142.686897,2716.722922,2627.52451,2649.022701,2621.664584,1611.245643,1648.597695,1684.455148,1823.124319,1874.506125,2000.890424,2260.469931,2236.353356,2240.929864,1611.245643,1692.244507,1721.272514,1760.81472,1831.023085,1882.566956,1902.293463,1915.570059,1924.486260,409.037548,77829.556771
1,5458,7382859,377995000,TTPOS,780,TTO,TT,Trinidad and Tobago,Port Of Spain,GDSTG,308,GRD,GD,Grenada,St Georges,2018-04-08 23:00:00,2018-04-09 15:00:00,16.0,40.0,56.0,106.757784,0.0,0.0,0.0,1.417976,3.424000,4.841976,0.0,0.0,0.0,0.0,0.0,0.0,0.060548,0.146205,4.546030,10.977344,15.523374,019,Americas,419,Latin America and the Caribbean,high_income,0,1,019,Americas,419,Latin America and the Caribbean,upp_mid_income,0,1,0.206752,General cargo,413.0,dwt,639.390272,NaN,NaN,NaN,NaN,2,5000-9999,1974.0,St Vincent & The Grenadines,MSD,4,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.02233,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.01858,0.018382,0.01842,0.013244,0.01391,0.014148,0.014473,0.01505,0.015474,0.015636,0.015745,0.015819,68259.888807,904.098582,925.666382,915.464209,906.516400,897.734365,889.118099,880.329118,872.049270,863.606459,903.994553,1296.385432,1277.900034,1368.933021,1515.703008,1500.745308,1454.253053,1372.240010,1321.417717,903.955184,960.741562,984.555485,1130.141023,1244.521978,1464.566137,1438.362455,1411.867532,1325.913249,903.955184,924.396699,956.436279,1069.069442,1202.200446,1524.275672,1474.22899,1486.291011,1470.941152,904.023931,924.981101,945.099694,1022.903007,1051.731871,1122.642494,1268.285144,1254.754023,1257.321771,904.023931,949.470081,965.756867,987.94287,1027.334779,1056.254574,1067.322554,1074.771673,1079.774299,409.037548,43667.942353

## 3.3 Evaluate NZF Costs

In [11]:
years=["26", "29", "32", "35", "38", "41", "44", "47", "50"]
vess_types_not_found_in_inventories, vess_types_not_found_in_global_voys, hs_codes_not_mapped_to_HS, cost_int_match_desc, cost_int_match_desc_bool = [], [], [], [], False

for year in years:

    print("Processing game year 20{0}".format(year))

    # Setup columns for policy costs per bilateral goods trade.
    bau_usd, levy_usd, asis_usd, brazil_usd, liscr_usd, direct_usd = [], [], [], [], [], []
    
    for trade_idx, trade in trade_ex.iterrows():

        # initiate selected voyages table as empty dataframe to begin
        int_dep_voys_vess = pd.DataFrame()

        # 3. If no facilitating vessel types were picked up for the HS code, take from full primary int. inv. voyages dataset, otherwise move on...
        if 'all' in trade.fac_vessel_types:
            hs_codes_not_mapped_to_HS.append(trade.HS4_desc)
            int_dep_voys_vess = int_dep_voys
            cost_int_match_desc.append("3. Primary Int. Inv. without Vess Type") if cost_int_match_desc_bool == False else None

        else:
            # 1. If possible, derive subset of voyages associated with the unique vessel type.
            int_dep_voys_vess = int_dep_voys[(int_dep_voys.vessel_type.isin(trade.fac_vessel_types))]    
            
            if int_dep_voys_vess.shape[0] > 0:
                cost_int_match_desc.append("1. Primary Int. Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                
            else:
                # 2. Finally, if no voyages are found as the vessel type doesn't appear in the country's shipping inventories, also take from full voyages dataset filtered for those vessel types instead.
                int_dep_voys_vess = voys_fem[(voys_fem.vessel_type.isin(trade.fac_vessel_types))]
                
                if int_dep_voys_vess.shape[0] > 0:
                    cost_int_match_desc.append("2. Global Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_inventories.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

                else:
                    # 4. Use full global voyage dataset as a back-up
                    int_dep_voys_vess = voys_fem
                    cost_int_match_desc.append("4. Global Inv. without Vess Type.") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_global_voys.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]
    
        # Add cost intensities associated with the subset of voyages by vessel type, assuming 50% of NZF costs are borne by the exporter.
        bau_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "bau35_usd_dwtnm_"+year))
        levy_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "levy35_usd_dwtnm_"+year))
        asis_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "asis35_usd_dwtnm_"+year))
        brazil_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "brazil35_usd_dwtnm_"+year))
        liscr_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "liscr35_usd_dwtnm_"+year))
        direct_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "direct35_usd_dwtnm_"+year))

    if cost_int_match_desc_bool == False:
        trade_ex["cost_int_match_desc"] = cost_int_match_desc
    cost_int_match_desc_bool = True

    trade_ex["bau_usd_"+year] = bau_usd
    trade_ex["levy_usd_"+year] = levy_usd
    trade_ex["asis_usd_"+year] = asis_usd
    trade_ex["brazil_usd_"+year] = brazil_usd
    trade_ex["liscr_usd_"+year] = liscr_usd
    trade_ex["direct_usd_"+year] = direct_usd
    
print("Inventory voyages table used for the following vessel types: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_inventories).unique()))
print("Global voyages table used for the following vessel types found: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_global_voys).unique()))
print("Global voyages table used for the following commodities as no 'facilitating vessel types' were identified: \n\n{0}\n".format(pd.Series(hs_codes_not_mapped_to_HS).unique()))

print()
print("Number of trade records present in dataset: {0}".format(trade_ex.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_ex.partnerCode.unique())))
print("\nTotal value of trade: US${0}m".format(np.round(trade_ex.fobvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_ex.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_ex.sea_dist_nm.min(), 1),
    round(trade_ex.sea_dist_nm.max(), 1),
    round(trade_ex.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_ex.vol_kg_vtw / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_ex.fobvalue / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.fobvalue.sum() / 1000), 1)
))

print("\n\nTotal FEM costs in 2041...\n")
print("BAU: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.bau_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.bau_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Levy: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.levy_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.levy_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("'as-is': US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.asis_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.asis_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Brazil: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.brazil_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.brazil_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("LISCR: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.liscr_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.liscr_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Direct: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.direct_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.direct_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))

trade_ex_agg = trade_ex.groupby(["cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "fobvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_ex_agg["vol_kg_vtw_pct"] = round(100 * trade_ex_agg.vol_kg_vtw / trade_ex_agg.vol_kg_vtw.sum(), 1)
trade_ex_agg["fobvalue_pct"] = round(100 * trade_ex_agg.fobvalue / trade_ex_agg.fobvalue.sum(), 1)
print("Most prominent 'cost intensity match' types...\n\n{0}\n".format(
    trade_ex_agg[["cost_int_match_desc", "vol_kg_vtw_pct", "fobvalue_pct"]].head(5)
))
trade_ex_agg_2 = trade_ex.groupby(["fac_vessel_types_str", "cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "fobvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_ex_agg_2["vol_kg_vtw_pct"] = round(100 * trade_ex_agg_2.vol_kg_vtw / trade_ex_agg_2.vol_kg_vtw.sum(), 1)
trade_ex_agg_2["fobvalue_pct"] = round(100 * trade_ex_agg_2.fobvalue / trade_ex_agg_2.fobvalue.sum(), 1)
print("Most prominent 'facilitating vessel types' and their 'cost intensity match' types...")
display(trade_ex_agg_2[["fac_vessel_types_str", "cost_int_match_desc", "vol_kg_vtw_pct", "fobvalue_pct"]].head(5))

trade_ex_na = trade_ex[(trade_ex[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (trade_ex.fac_vessel_types.str.len() == 0)]
trade_ex = trade_ex[(~trade_ex[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (~trade_ex.fac_vessel_types.str.len() == 0)]
print("Rows with NA: ${0} ({1}%)\n".format(trade_ex_na.primaryValue.sum(), round(100 * trade_ex_na.primaryValue.sum() / trade_ex.primaryValue.sum(), 1)))

trade_ex.to_csv(output_dir + "{0}/impact_ex_{1}.csv".format(iso_country, version), index=False)
trade_ex.head(2)

Processing game year 2026
Processing game year 2029
Processing game year 2032
Processing game year 2035
Processing game year 2038
Processing game year 2041
Processing game year 2044
Processing game year 2047
Processing game year 2050
Inventory voyages table used for the following vessel types:

[]

Global voyages table used for the following vessel types found:

['Other liquids tankers']

Global voyages table used for the following commodities as no 'facilitating vessel types' were identified:

['6907 | Ceramic flags and pa' '5703 | Carpets and other te'
 '4407 | Wood sawn or chipped' '4412 | Plywood, veneered pa'
 '2202 | Waters, including mi' '9404 | Mattress supports; a'
 '8903 | Yachts and other ves' '9401 | Seats (not those of '
 '8517 | Telephone sets, incl' '8528 | Monitors and project'
 '8716 | Trailers and semi-tr' '8424 | Mechanical appliance'
 '8539 | Lamps; electric fila' '6201 | Overcoats, car-coats'
 "6202 | Coats; women's or gi" '9027 | Instruments and appa'
 '8432 | Agricultural, hortic' '8462 | Machine-tools (inclu'
 '8525 | Transmission apparat' '9701 | Paintings, drawings '
 '2106 | Food preparations no' '9405 | Luminaires and light'
 '4015 | Articles of apparel ' '5007 | Woven fabrics of sil'
 '2009 | Fruit or nut juices ' '1509 | Olive oil and its fr'
 '1510 | Vegetable oils; oils' '6117 | Clothing accessories'
 "4418 | Builders' joinery an" '0910 | Ginger, saffron, tum'
 '3402 | Organic surface-acti' '3926 | Articles of plastics'
 '4419 | Tableware and kitche' '1605 | Crustaceans, mollusc'
 '1704 | Sugar confectionery ' '1905 | Bread, pastry, cakes'
 '4823 | Paper, paperboard, c' '2309 | Preparations of a ki'
 '4911 | Printed matter, n.e.' '7326 | Iron or steel; artic'
 '1806 | Chocolate and other ' '0403 | Yogurt; buttermilk, '
 '3307 | Perfumery, cosmetic ' '0802 | Nuts (excluding coco'
 '3824 | Prepared binders for' '7616 | Aluminium; articles '
 '2853 | Phosphides, chemical' '4707 | Waste and scrap of p'
 '3907 | Polyacetals, other p' '4421 | Wooden articles n.e.'
 '1008 | Buckwheat, millet an' '6914 | Ceramic articles; n.'
 '8215 | Cutlery; spoons, for' '3006 | Pharmaceutical goods'
 '4905 | Maps and hydrographi' '2812 | Halides and halide o'
 '6310 | Rags; used or new, s' '8311 | Wires, rods, tubes, '
 '3215 | Ink; printing, writi' '3507 | Enzymes; prepared en'
 '9406 | Buildings; prefabric' '4414 | Wooden frames; for p'
 '3105 | Fertilizers; mineral' '3808 | Insecticides, rodent'
 '3822 | Reagents; diagnostic' '5911 | Textile products and'
 '6815 | Stone or other miner' '7508 | Nickel; articles the'
 '9403 | Furniture and parts ' '0805 | Citrus fruit; fresh '
 '0307 | Molluscs; whether in' '7019 | Glass fibres (includ'
 '0306 | Crustaceans; in shel' '3002 | Human blood; animal '
 '3606 | Ferro-cerium and oth' '3707 | Chemical preparation'
 '7419 | Copper; articles the' '4420 | Wood marquetry and i'
 '0511 | Animal products not ' '0210 | Meat and edible meat'
 '2530 | Mineral substances n' '0714 | Manioc, arrowroot, s'
 '4401 | Fuel wood, in logs, ' '7229 | Wire of other alloy '
 '3812 | Prepared rubber acce' '1404 | Vegetable products n'
 '2914 | Ketones and quinones']


Number of trade records present in dataset: 7586
Number of partner countries present in dataset: 94

Total value of trade: US$7166.1m
Total weight within the dataset: 14542.7 million kilograms

Distance to market: 101.3 nm (min) to 13626.0 nm (max), 966.5 nm (observed mean)
Average distance to market (volume-weighted): 4077.4 nm
Average distance to market (value-weighted): 4133.0 nm


Total FEM costs in 2041...

BAU: US$233.9m (3.3% ad-val)
Levy: US$468.6m (6.5% ad-val)
'as-is': US$441.8m (6.2% ad-val)
Brazil: US$454.6m (6.3% ad-val)
LISCR: US$292.7m (4.1% ad-val)
Direct: US$302.8m (4.2% ad-val)
Most prominent 'cost intensity match' types...

                      cost_int_match_desc  vol_kg_vtw_pct  fobvalue_pct
0     1. Primary Int. Inv. with Vess Type            99.5          98.5
1  3. Primary Int. Inv. without Vess Type             0.5           1.5
2       4. Global Inv. without Vess Type.             0.0           0.0

Most prominent 'facilitating vessel types' and their 'cost intensity match' types...

,fac_vessel_types_str,cost_int_match_desc,vol_kg_vtw_pct,fobvalue_pct
0,['Liquefied gas tanker'],1. Primary Int. Inv. with Vess Type,43.1,42.1
1,['Chemical tanker'],1. Primary Int. Inv. with Vess Type,13.4,16.6
2,['Bulk carrier'],1. Primary Int. Inv. with Vess Type,12.8,8.8
3,"['General cargo', 'Container']",1. Primary Int. Inv. with Vess Type,8.2,5.5
4,['Oil tanker'],1. Primary Int. Inv. with Vess Type,7.6,7.5

Rows with NA: $0.0 (0.0%)

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_ex_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,TandT_match_desc,TandT_ad_val_pct,TandT_N,TandT_ciffob,TandT_cifvalue,TandT_fobvalue,cost_int_match_desc,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50
0,0,780,Trinidad and Tobago,308,Grenada,000,World,Domestic Export,Sea,690410 | Ceramic building bri,690410,1000u,11.022,1632.0,NaN,2802.073,2802.073,Grenada | 690410 | Ceramic building bri,69,69 | Ceramic products,Grenada | 69 | Ceramic products,6904,6904 | Ceramic building bri,Grenada | 6904 | Ceramic building bri,69.0,6904.0,690410.0,Ceramic building bricks,Mining and Quarrying,2693.0,Manufacture of structural non-refractory clay ...,66241.0,"Ceramic building bricks, flooring blocks, supp...",34.0,NMM - Mineral products n.e.c.,3735.0,"Non-refractory ceramic building bricks, floori...",0.211,4.7399,both,0.582426,13281.545813,1632.0,[Container],['Container'],163.0,101.283473,1345.201087,"2 - Reporter, Partner and HS2 code",5.57,1,156.08,2958.15,2802.07,1. Primary Int. Inv. with Vess Type,6.457967,6.444637,6.445850,6.445850,6.452541,6.452541,6.760307,12.103096,7.455607,6.916535,6.936609,7.114086,6.617186,11.793472,7.836621,7.184285,7.019253,7.343124,6.491684,12.868468,9.739016,8.510711,7.872242,7.657095,6.368406,13.677081,11.206579,10.492964,8.413643,8.211301,6.247444,13.876279,13.231859,13.365795,9.118018,8.627619,6.124074,13.598869,13.024359,14.194063,10.531020,8.786743,6.007928,12.113933,12.605443,13.201004,9.873719,8.891164,5.889501,11.092845,11.286702,13.896278,11.484966,8.951879
1,1,780,Trinidad and Tobago,328,Guyana,000,World,Domestic Export,Sea,690410 | Ceramic building bri,690410,1000u,467.860,956334.0,NaN,118941.563,118941.563,Guyana | 690410 | Ceramic building bri,69,69 | Ceramic products,Guyana | 69 | Ceramic products,6904,6904 | Ceramic building bri,Guyana | 6904 | Ceramic building bri,69.0,6904.0,690410.0,Ceramic building bricks,Mining and Quarrying,2693.0,Manufacture of structural non-refractory clay ...,66241.0,"Ceramic building bricks, flooring blocks, supp...",34.0,NMM - Mineral products n.e.c.,3735.0,"Non-refractory ceramic building bricks, floori...",0.211,4.7399,both,8.040369,563771.114464,956334.0,[Container],['Container'],693.0,430.610103,242765.537668,3 - Reporter and HS4 code,8.17,2,9717.53,128659.09,118941.56,1. Primary Int. Inv. with Vess Type,1165.455332,1163.049797,1163.268631,1163.268631,1164.476164,1164.476164,1220.018065,2184.219667,1345.497273,1248.212112,1251.834771,1283.863711,1194.189307,2128.342464,1414.258092,1296.532360,1266.749434,1325.197786,1171.540238,2322.344602,1757.579120,1535.909737,1420.686453,1381.859348,1149.292566,2468.273298,2022.427134,1893.642524,1518.392063,1481.875850,1127.462661,2504.222096,2387.924968,2412.096269,1645.508987,1557.007824,1105.198371,2454.158479,2350.477912,2561.571998,1900.510491,1585.724593,1084.237765,2186.175378,2274.877182,2382.356761,1781.888723,1604.569094,1062.865600,2001.901813,2036.886731,2507.831371,2072.667043,1615.526300

## 3.4 Create Results Tables

### 3.4.1 Total Costs per Scenario

In [12]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        np.round(trade_ex["bau_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["levy_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["asis_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["brazil_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["liscr_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["direct_usd_{0}".format(year)].sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% cif)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
    display(df)

    
print("\nTotal FEM costs by scenario (% fob)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_fob_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / gdp, 3)
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,BAU,2.471989e+08,2.420951e+08,2.393717e+08,2.366932e+08,2.338567e+08,2.301863e+08,2.268933e+08,2.218475e+08
1,Levy,4.011928e+08,3.846814e+08,4.231607e+08,4.806805e+08,4.685918e+08,4.590031e+08,4.153360e+08,3.832911e+08
2,'as-is',2.574025e+08,2.651614e+08,3.091419e+08,3.733737e+08,4.417960e+08,4.391617e+08,4.264368e+08,3.927138e+08
3,Brazil,2.487541e+08,2.529181e+08,2.845999e+08,3.467078e+08,4.546181e+08,4.710718e+08,4.456433e+08,4.487750e+08
4,LISCR,2.490204e+08,2.439551e+08,2.629779e+08,2.774435e+08,2.927451e+08,3.653599e+08,3.613204e+08,3.659867e+08
5,Direct,2.547772e+08,2.573098e+08,2.688561e+08,2.880128e+08,3.028302e+08,3.081177e+08,3.218034e+08,3.218395e+08

Total FEM costs by scenario (% ciffob)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  50.04  49.00  48.45  47.91  47.34  46.59  45.93  44.91
1     Levy  81.21  77.87  85.65  97.30  94.85  92.91  84.07  77.58
2  'as-is'  52.10  53.67  62.58  75.58  89.43  88.89  86.32  79.49
3   Brazil  50.35  51.19  57.61  70.18  92.02  95.35  90.21  90.84
4    LISCR  50.41  49.38  53.23  56.16  59.26  73.95  73.14  74.08
5   Direct  51.57  52.08  54.42  58.30  61.30  62.37  65.14  65.15

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0      BAU  3.23  3.16  3.12  3.09  3.05  3.00  2.96  2.90
1     Levy  5.24  5.02  5.52  6.28  6.12  5.99  5.42  5.00
2  'as-is'  3.36  3.46  4.04  4.87  5.77  5.73  5.57  5.13
3   Brazil  3.25  3.30  3.72  4.53  5.93  6.15  5.82  5.86
4    LISCR  3.25  3.18  3.43  3.62  3.82  4.77  4.72  4.78
5   Direct  3.33  3.36  3.51  3.76  3.95  4.02  4.20  4.20

Total FEM costs by scenario (% fob)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0      BAU  3.45  3.38  3.34  3.30  3.26  3.21  3.17  3.10
1     Levy  5.60  5.37  5.91  6.71  6.54  6.41  5.80  5.35
2  'as-is'  3.59  3.70  4.31  5.21  6.17  6.13  5.95  5.48
3   Brazil  3.47  3.53  3.97  4.84  6.34  6.57  6.22  6.26
4    LISCR  3.47  3.40  3.67  3.87  4.09  5.10  5.04  5.11
5   Direct  3.56  3.59  3.75  4.02  4.23  4.30  4.49  4.49

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  0.953  0.933  0.923  0.912  0.902  0.887  0.875  0.855
1     Levy  1.547  1.483  1.631  1.853  1.806  1.769  1.601  1.478
2  'as-is'  0.992  1.022  1.192  1.439  1.703  1.693  1.644  1.514
3   Brazil  0.959  0.975  1.097  1.337  1.753  1.816  1.718  1.730
4    LISCR  0.960  0.940  1.014  1.070  1.129  1.408  1.393  1.411
5   Direct  0.982  0.992  1.036  1.110  1.167  1.188  1.241  1.241

### 3.4.2 Costs per Scenario relative to BAU

In [13]:
print("\nTotal FEM costs by scenario (US$)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        np.round((trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_usd_bau_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal change in FEM costs by scenario (% bau)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        round((100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_bau_{1}.csv".format(iso_country, version), index=False)
display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% cif)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_cif_{1}.csv".format(iso_country, version), index=False)
    display(df)


print("\nTotal FEM costs by scenario (% fob)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_fob_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,Levy,1.539939e+08,1.425863e+08,1.837890e+08,2.439874e+08,2.347351e+08,2.288168e+08,1.884427e+08,1.614436e+08
1,'as-is',1.020362e+07,2.306628e+07,6.977023e+07,1.366806e+08,2.079393e+08,2.089754e+08,1.995435e+08,1.708663e+08
2,Brazil,1.555281e+06,1.082298e+07,4.522817e+07,1.100146e+08,2.207614e+08,2.408855e+08,2.187500e+08,2.269275e+08
3,LISCR,1.821546e+06,1.859974e+06,2.360617e+07,4.075033e+07,5.888842e+07,1.351736e+08,1.344271e+08,1.441392e+08
4,Direct,7.578365e+06,1.521473e+07,2.948435e+07,5.131960e+07,6.897352e+07,7.793144e+07,9.491016e+07,9.999202e+07

Total change in FEM costs by scenario (% bau)...

  Scenario   2029   2032   2035    2038    2041    2044   2047    2050
0     Levy  62.30  58.90  76.78  103.08  100.38   99.41  83.05   72.77
1  'as-is'   4.13   9.53  29.15   57.75   88.92   90.79  87.95   77.02
2   Brazil   0.63   4.47  18.89   46.48   94.40  104.65  96.41  102.29
3    LISCR   0.74   0.77   9.86   17.22   25.18   58.72  59.25   64.97
4   Direct   3.07   6.28  12.32   21.68   29.49   33.86  41.83   45.07

Total FEM costs by scenario (% ciffob)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  31.17  28.86  37.20  49.39  47.51  46.32  38.14  32.68
1  'as-is'   2.07   4.67  14.12  27.67  42.09  42.30  40.39  34.59
2   Brazil   0.31   2.19   9.15  22.27  44.69  48.76  44.28  45.93
3    LISCR   0.37   0.38   4.78   8.25  11.92  27.36  27.21  29.18
4   Direct   1.53   3.08   5.97  10.39  13.96  15.77  19.21  20.24

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0     Levy  2.01  1.86  2.40  3.19  3.06  2.99  2.46  2.11
1  'as-is'  0.13  0.30  0.91  1.78  2.71  2.73  2.60  2.23
2   Brazil  0.02  0.14  0.59  1.44  2.88  3.14  2.86  2.96
3    LISCR  0.02  0.02  0.31  0.53  0.77  1.76  1.75  1.88
4   Direct  0.10  0.20  0.38  0.67  0.90  1.02  1.24  1.31

Total FEM costs by scenario (% fob)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0     Levy  2.15  1.99  2.56  3.40  3.28  3.19  2.63  2.25
1  'as-is'  0.14  0.32  0.97  1.91  2.90  2.92  2.78  2.38
2   Brazil  0.02  0.15  0.63  1.54  3.08  3.36  3.05  3.17
3    LISCR  0.03  0.03  0.33  0.57  0.82  1.89  1.88  2.01
4   Direct  0.11  0.21  0.41  0.72  0.96  1.09  1.32  1.40

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  0.594  0.550  0.709  0.941  0.905  0.882  0.726  0.622
1  'as-is'  0.039  0.089  0.269  0.527  0.802  0.806  0.769  0.659
2   Brazil  0.006  0.042  0.174  0.424  0.851  0.929  0.843  0.875
3    LISCR  0.007  0.007  0.091  0.157  0.227  0.521  0.518  0.556
4   Direct  0.029  0.059  0.114  0.198  0.266  0.300  0.366  0.385