<h2>Impact (v0.64) - 'Impact (v0.64).ipynb'</h2>

<u><h4>Context</h4></u>

The aim of the 'Impact' notebooks are to explore economic impacts resulsting from the FEM outputs in the lead-up to Autumn 2026, taking foward outputs from the associated 'Trade' notebooks.

<u><h4>Version Documentation and Future Work</h4></u>

'v0.2' cleaned up the analysis code by introducing the cost intensity estimation functions that were previously in the 'inventories' notebooks. For example, the 'get_usd_per_tnm' function is included here and applied to voyages identified as relevant to each individual trade record. The NZF costs associated with each trade record are now evaluated like this. 'v0.3' introduced the exporter- and importer-side trade portfolios at an HS-digit 4 level of resolution. With this implemented, the matching algorithm is now be being evaluated using the cargo weight field rather than value, and the process will be being conducted at the HS-digit 4 level of resolution. Since we are now confident regarding the use of the Global Shipping Watch dataset for the purposes of matching HS codes with facilitating vessel types, we should then be in good shape to take the analysis forward using the results produced in this notebook. 'v0.3' also subsumed the 'inventories' notebooks. In 'v0.4' sought to include transport costs data from UNCTAD's Trade-and-Transport database. However, there are now concerns regarding this dataset as it is importer-side only, and therefore has odd looking exporter-side portfolios. Instead, it makes sense for us to utilise trade portfolios derived from UN Comtrade, where these are submitted with disaggregation by Transport Mode. Looking at the 16 countries of interest across African and Caribbean economies we're interested in the summer of 2026, 13 of these have a trade portfolio with MoT Breakdown available across at least one year within the last decade. Therefore this approach makes more sense, and 'v0.6' was amended to work with Comtrade import and export trade portfolios downloaded from the platform. 'v0.61' made use of the updated 'trade' notebooks that derive a new weight field using Value-to-Weight and Weight-to-Value ratios observed in the CEPII BACI datasets across 2017-23. In the case of Trinidad and Tobaogo, import volumes were around 65% higher under the WtV approach which corresponded to a 39% greater 2041 BAU impact from FEM costs, but this was slightly less for exports where the weighted WtV was 9% more but 2041 FEM costs under BAU were around 10% less. A new 'composite' weight field has been added in Trade (v0.61) which only introduces the VtW-derived values where 'netWgt' is observed to be zero, however this resulted in only a tiny increase in recorded weight of around 1% for Angola, whereas the full VtW-derived field was ~50% greater. 

'v0.62' makes use of a new 'transport cost' field derived using ad-valorem transport cost rates identified from UNCTAD's Trade-and-Transport database. With these, we can now introduce another results disaggregation that presents NZF costs relative to expected transport costs, which is then fully in-line with how impacts are expressed in UNCTAD's CIA Task 3 work. 'v0.63' includes an assessment of 'Cost Intensity' matching process (similar to CIF-FOB matching), plus metrics on 'fac_vessel_types' and 'average sea-distance' (introduced in Trade v0.63). 'v0.64' has been modified throughout to account for a new scenario, namely the 'Japan' proposal, plus to remove the 'Low-then-High' scenario. In terms of the Impact notebook, this remains the same as 'v0.63'.

In [1]:
# Import packages
import os
import ast
import base64
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 250)
pd.set_option('display.max_rows', 250)
pd.options.mode.chained_assignment = None
from IPython.display import HTML
import matplotlib.pyplot as plt
import matplotlib.style
plt.style.use('seaborn-v0_8')

def voyages_analysis(voys):
    # Define a function to analyses key statistics from a given set of voyages, 'voys'.
    print("Number of Voyages found: {0}".format(voys.shape[0]))
    print("Total size of the fleet: {0} vessels".format(len(voys.imo.unique())))
    print("{0} vessel types contained in the dataset: {1}".format(len(voys.vessel_type.unique()), voys.vessel_type.unique()))
    print("Total transport work capacity: {0} million deadweight-tonne nautical miles".format(np.round(voys.dwtnm.sum() / 1e6, 1)))
    print("Total cargo transported: {0} tonnes".format(np.round(voys.tonnes.sum(), 1)))
    print("Total transport work: {0} million tonne nautical miles".format(np.round(voys.tnm.sum() / 1e6, 1)))
    print("Average build year of the fleet: {0}".format(int(np.round(voys.year_of_built.mean(), 0))))
    print("Total Energy Demands: {0} EJ".format(np.round(voys.energy_tj.sum(), 1)))
    print("Total CO2 produced: {0} tonnes".format(np.round(voys.co2_t.sum(), 1)))

def get_usd_per_dwtnm(voys, field_name):
    # Derive the deadweight-average of the cost intensity (per unit of cargo-carrying capacity) for the field 'field_name' in an input selection of voyages, 'voys'.
    return (voys[field_name].values * voys.deadweight.values).sum() / voys.deadweight.sum()
    
def get_usd_per_tnm(voys, field_name):
    # Derive the deadweight-average of the cost intensity (per unit of cargo-carried) for the field 'field_name' in an input selection of voyages, 'voys'.
    return (voys[field_name].values / voys.class_util.values * voys.tonnes.values).sum() / voys.tonnes.sum()

def download_link(df, title = "Download CSV file", filename = "data.csv"):
    csv = df.to_csv()
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
    html = html.format(payload=payload,title=title,filename=filename)
    return HTML(html)

version = "v0.64"
input_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/"
voys_fem_dir = "/Users/apple/repos/datasets/ucl/fleet evolution model/2026 annex vi amendments (v0.2)/2. NZF Impact Costs for 2018 IMO IV Voyages/voys_fem_v0.2.csv"
output_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/impact/"
res_mlc = False

# 1. Set up the notebook

## 1.1 Let's set the country we're interested in and set up a results folder.

In [2]:
# Select one of our countries to work on...
iso_code = "332"
iso_country = "Haiti"
import_portfolio = "h4_ag6_by_sea_M*.csv" # Imports, '_M' | Foreign Imports, '_FM' | Re-Imports, '_RM'
export_portfolio = "h4_ag6_by_sea_X*.csv" # Exports, '_X' | Domestic Exports, '_DX' | Re-exports, '_RX'
year = 2017
gdp = 15.090*1e9

# Create output Journey directory folder if necessary
os.makedirs(output_dir+"{0}/".format(iso_country)) if not os.path.exists(output_dir+"{0}/".format(iso_country)) else "Output directory already exists."
os.makedirs(output_dir+"{0}/results/".format(iso_country)) if not os.path.exists(output_dir+"{0}/results/".format(iso_country)) else "Output results folder already exists."

## 1.2 Voyages with FEM Results

In [3]:
voys_fem_d = {
    "source_iso":str, "source_iso_code":str, "source_iso_3":str, "source_iso_2":str, 
    "dest_iso_code":str, "dest_iso_code":str, "dest_iso_3":str, "dest_iso_2":str, 
    "source_region_code":str, "source_sub_region_code":str, "dest_region_code":str, "dest_sub_region_code":str, 
    "source_ldc":str, "source_sids":str, "dest_ldc":str, "dest_sids":str
}

voys_fem = pd.read_csv(voys_fem_dir, dtype=voys_fem_d)
voys_fem["dwtnm"] = voys_fem.deadweight * voys_fem.dist_travelled_ais
voys_fem["tonnes"] = voys_fem.deadweight * voys_fem.class_util
voys_fem["tnm"] = voys_fem.tonnes * voys_fem.dist_travelled_ais
voys_fem.loc[voys_fem.source_country == "Namibia", "source_iso_2"] = "NA"
voys_fem.loc[voys_fem.dest_country == "Namibia", "dest_iso_2"] = "NA"

countries_set = pd.Series(list(set(list(voys_fem.source_country.unique()) + list(voys_fem.dest_country.unique())))).sort_values()
print("Number of countries present in dataset: {0}.".format(len(countries_set)))
print("Number of IMO numbers present in dataset: {0}.".format(len(voys_fem.imo.unique())))
print("Total CO2 contained within the dataset: {0} million tonnes.".format(np.round(voys_fem.co2_t.sum() / 1e6, 1)))
print("Vessel types present in dataset: \n\n{0}\n".format(pd.Series(voys_fem.vessel_type.unique()).sort_values().values))
#print("\nCountries in dataset: \n\n", countries_set.values, "\n")
voys_fem.head(2)

Number of countries present in dataset: 207.
Number of IMO numbers present in dataset: 26132.
Total CO2 contained within the dataset: 544.7 million tonnes.
Vessel types present in dataset:

['Bulk carrier' 'Chemical tanker' 'Container' 'General cargo'
 'Liquefied gas tanker' 'Oil tanker' 'Refrigerated bulk' 'Vehicle']

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,0,5034525,413781699,CNTAX,156,CHN,CN,China,Taixing,CNNKG,156,CHN,CN,China,Nanjing,2018-01-01 06:00:00,2018-01-01 19:00:00,13.0,1.0,14.0,62.568523,0.0,0.0,0.0,3.635661,0.338483,3.974144,0.0,0.0,0.0,0.0,0.0,0.0,0.155243,0.014453,11.655930,1.085176,12.741107,142,Asia,030,Eastern Asia,upp_mid_income,0,0,142,Asia,030,Eastern Asia,upp_mid_income,0,0,0.169696,Refrigerated bulk,3786.0,dwt,3881.0,NaN,NaN,NaN,NaN,2,2000-5999,1959.0,Panama,SSD,4,76.1,0.666667,0.03155,0.032676,0.032143,0.031676,0.031218,0.030769,0.03031,0.029878,0.029438,0.031576,0.052178,0.052414,0.05804,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.05942,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,242828.439338,7661.320668,7934.549945,7805.304846,7691.950531,7580.696290,7471.542086,7360.199865,7255.307537,7148.350725,7667.458038,12670.391275,12727.642802,14093.647297,14570.027623,14398.931835,14189.590704,14139.488873,14161.462401,7665.715352,8412.516422,8946.627490,10860.650719,12049.492896,13084.201484,14034.766615,14342.763237,14083.751009,7665.715352,7946.962662,8384.668998,9891.651071,11698.979626,13565.379532,13949.851660,14247.178318,14428.769963,7663.482493,7940.155892,8209.623358,9221.805242,9744.436151,10159.112402,10518.004352,10853.785659,11140.079340,7663.482493,8252.567981,8473.856677,8773.523328,9299.485535,9694.695953,9860.244395,9979.919640,10068.487874,2587.333335,161885.626306
1,1,5034525,413781699,CNNKG,156,CHN,CN,China,Nanjing,CNTOL,156,CHN,CN,China,Tongling,2018-01-01 20:00:00,2018-01-04 17:00:00,69.0,59.0,128.0,134.252308,0.0,0.0,0.0,21.355373,19.491146,40.846519,0.0,0.0,0.0,0.0,0.0,0.0,0.911874,0.832272,68.465325,62.488615,130.953940,142,Asia,030,Eastern Asia,upp_mid_income,0,0,142,Asia,030,Eastern Asia,upp_mid_income,0,0,1.744146,Refrigerated bulk,3786.0,dwt,3881.0,NaN,NaN,NaN,NaN,2,2000-5999,1959.0,Panama,SSD,4,76.1,0.666667,0.03155,0.032676,0.032143,0.031676,0.031218,0.030769,0.03031,0.029878,0.029438,0.031576,0.052178,0.052414,0.05804,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.05942,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,521033.206847,16438.776642,17025.040451,16747.721252,16504.498662,16265.782167,16031.571689,15792.666415,15567.600579,15338.105010,16451.945500,27186.661563,27309.505274,30240.519881,31262.681739,30895.564166,30446.384156,30338.881438,30386.029694,16448.206246,18050.605691,19196.639505,23303.529390,25854.409564,28074.567693,30114.180516,30775.044079,30219.285570,16448.206246,17051.674227,17990.853906,21224.361910,25102.318690,29107.023950,29931.979818,30569.949005,30959.587375,16443.415234,17037.069045,17615.261197,19787.084130,20908.485145,21798.249530,22568.318408,23288.799137,23903.095037,16443.415234,17707.406809,18182.222523,18825.212595,19953.761526,20801.758375,21156.973093,21413.758406,21603.797889,2587.333335,347355.471405

# 2. Let's consider Imports

## 2.1 Read-in Trade dataset

In [4]:
trade_im_d = {
    "reporterCode":"str", "partnerCode":"str", "partner2Code":"str", 
    "cmdCode":"str", "HS2":"str", "HS4":"str", "hs2":"str", "hs4":"str", "hs6":"str",
    "isic":"str", "sitc":"str", "gtap":"str", "cpc":"str"
}
if res_mlc == False:
    trade_im = pd.read_csv(input_dir+"trade/{0}/trade_im_dist_{1}.csv".format(iso_country, version), dtype=trade_im_d)
else:
    trade_im = pd.read_csv(input_dir+"trade/{0}/trade_im_mlc_{1}.csv".format(iso_country, version), dtype=trade_im_d)
trade_im['fac_vessel_types'] = [ast.literal_eval(x) for x in trade_im.fac_vessel_types.values]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(trade_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_im.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(trade_im.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(trade_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_im.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_im.sea_dist_nm.min(), 1),
    round(trade_im.sea_dist_nm.max(), 1),
    round(trade_im.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_im.vol_kg_vtw / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_im.cifvalue / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.cifvalue.sum() / 1000), 1)
))
trade_im.head(2)

Aggregate trade portfolio statistics for 'Haiti':

Number of trade records present in dataset: 18685
Number of partner countries present in dataset: 118
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$1669.5m
Total weight within the dataset: 2489.2 million kilograms

Distance to market: 119.3 nm (min) to 12538.6 nm (max), 4290.8 nm (observed mean)
Average distance to market (volume-weighted): 3397.0 nm
Average distance to market (value-weighted): 4504.5 nm

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_im_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm
0,0,332,Haiti,056,Belgium,000,World,Import,Sea,960400 | Hand sieves and hand,960400,NaN,0.0,408.663016,5425.309770,NaN,5425.309770,Belgium | 960400 | Hand sieves and hand,96,96 | Miscellaneous manufa,Belgium | 96 | Miscellaneous manufa,9604,9604 | Hand sieves and hand,Belgium | 9604 | Hand sieves and hand,96,9604,960400,Hand sieves & hand riddles,Other Manufacturing,3699,Other manufacturing n.e.c.,89981,Hand sieves & hand riddles,42,OMF - Manufactures n.e.c.,38999,"Articles n.e.c. (including candles, tapers, sk...",8.8881,0.1125,both,0.075325,610.347349,408.663016,[Container],['Container'],5855.0,3638.127205,2220.521295
1,1,332,Haiti,070,Bosnia Herzegovina,000,World,Import,Sea,283630 | Carbonates; sodium h,283630,kg,19154.0,19154.000000,8587.831893,NaN,8587.831893,Bosnia Herzegovina | 283630 | Carbonates; sodi...,28,28 | Inorganic chemicals;,Bosnia Herzegovina | 28 | Inorganic chemicals;,2836,2836 | Carbonates; peroxoca,Bosnia Herzegovina | 2836 | Carbonates; peroxoca,28,2836,283630,Sodium hydrogencarbonate (sodium bicarbonate),"Petroleum, Chemical and Non-Metallic Mineral P...",2411,"Manufacture of basic chemicals, except fertili...",52373,Sodium hydrogencarbonate (sodium bicarbonate),33,"CRP - Chemical, rubber, plastic products",3424,Salts and peroxysalts of inorganic acids and m...,0.4353,2.2974,both,2.230365,19729.684992,19154.000000,[Container],['Container'],9081.0,5642.670051,111328.102619

## 2.2 Derive Internationally Arriving Voyages

In [5]:
# International Arrivals
int_arr_voys = voys_fem[(voys_fem.dest_country == iso_country) & (voys_fem.source_country != iso_country)].reset_index(drop=True)
int_arr_voys.to_csv(output_dir + "{0}/int_arr_voys_{1}.csv".format(iso_country, version), index=False)
int_dep_voys = voys_fem[(voys_fem.source_country == iso_country) & (voys_fem.dest_country != iso_country)].reset_index(drop=True)
int_dep_voys.to_csv(output_dir + "{0}/int_dep_voys_{1}.csv".format(iso_country, version), index=False)
voyages_analysis(int_arr_voys)
int_arr_voys.head(2)

Number of Voyages found: 587
Total size of the fleet: 226 vessels
6 vessel types contained in the dataset: ['General cargo' 'Vehicle' 'Chemical tanker' 'Container' 'Bulk carrier'
 'Oil tanker']
Total transport work capacity: 15422.4 million deadweight-tonne nautical miles
Total cargo transported: 7785358.7 tonnes
Total transport work: 9335.9 million tonne nautical miles
Average build year of the fleet: 2007
Total Energy Demands: 1758.1 EJ
Total CO2 produced: 135453.4 tonnes

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,17452,8121379,375401000,DOSPM,214,DOM,DO,Dominican Republic,San Pedro De Macoris,HTACA,332,HTI,HT,Haiti,Les Cayes,2018-05-07 17:00:00,2018-05-15 13:00:00,188.0,251.0,439.0,350.761328,2.295236,0.000431,2.295666,14.2316,21.2315,35.4631,0.0,0.0,0.0,0.0,0.0,0.0,0.699958,0.906602,52.773873,68.06953,120.843403,019,Americas,419,Latin America and the Caribbean,upp_mid_income,0,1,019,Americas,419,Latin America and the Caribbean,low_mid_income,1,1,1.606560,General cargo,3222.0,dwt,5350.0,146.0,NaN,NaN,NaN,2,5000-9999,1983.0,St Vincent & The Grenadines,MSD,1,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.02233,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.01858,0.018382,0.01842,0.013244,0.01391,0.014148,0.014473,0.01505,0.015474,0.015636,0.015745,0.015819,1.876573e+06,24855.110565,25448.043762,25167.569756,24921.580245,24680.148092,24443.273215,24201.650135,23974.023931,23741.917601,24852.250641,35639.701121,35131.508079,37634.149952,41669.090755,41257.879726,39979.733578,37725.064337,36327.878528,24851.168343,26412.316336,27066.999020,31069.377452,34213.892150,40263.256678,39542.875713,38814.488070,36451.467858,24851.168343,25413.138143,26293.957247,29390.422367,33050.405799,41904.766934,40528.903900,40860.508073,40438.516013,24853.058294,25429.204295,25982.296471,28121.233517,28913.784929,30863.230922,34867.179452,34495.187355,34565.778837,24853.058294,26102.445368,26550.195076,27160.123645,28243.069984,29038.121220,29342.397628,29547.185778,29684.715935,3422.558924,1.200501e+06
1,17454,8121379,375401000,DOSPM,214,DOM,DO,Dominican Republic,San Pedro De Macoris,HTACA,332,HTI,HT,Haiti,Les Cayes,2018-06-04 07:00:00,2018-06-08 11:00:00,100.0,204.0,304.0,327.998299,1.816505,0.000212,1.816717,5.2092,17.3469,22.5561,0.0,0.0,0.0,0.0,0.0,0.0,0.295456,0.740721,22.357292,55.61482,77.972113,019,Americas,419,Latin America and the Caribbean,upp_mid_income,0,1,019,Americas,419,Latin America and the Caribbean,low_mid_income,1,1,1.036177,General cargo,3222.0,dwt,5350.0,146.0,NaN,NaN,NaN,2,5000-9999,1983.0,St Vincent & The Grenadines,MSD,1,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.02233,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.01858,0.018382,0.01842,0.013244,0.01391,0.014148,0.014473,0.01505,0.015474,0.015636,0.015745,0.015819,1.754791e+06,23242.111741,23796.565907,23534.293560,23304.267800,23078.503642,22857.001013,22631.058320,22418.204160,22201.160617,23239.437414,33326.824827,32851.611512,35191.841780,38964.930810,38580.405758,37385.206263,35276.856179,33970.342229,23238.425353,24698.260987,25310.457342,29053.097171,31993.545244,37650.329830,36976.698753,36295.580601,34085.911098,23238.425353,23763.925525,24587.582937,27483.099661,30905.564578,39185.312532,37898.737593,38208.821961,37814.215524,23240.192654,23778.949048,24296.147719,26296.276171,27037.394116,28860.328739,32604.436773,32256.585498,32322.595871,23240.192654,24408.499425,24827.191940,25397.538546,26410.205931,27153.661472,27438.191539,27629.689744,27758.294735,3422.558924,1.122594e+06

## 2.3 Evaluate NZF Costs

In [6]:
years=["26", "29", "32", "35", "38", "41", "44", "47", "50"]
vess_types_not_found_in_inventories, vess_types_not_found_in_global_voys, hs_codes_not_mapped_to_HS, cost_int_match_desc, cost_int_match_desc_bool = [], [], [], [], False

for year in years:

    print("Processing game year 20{0}".format(year))

    # Setup columns for policy costs per bilateral goods trade.
    bau_usd, levy_usd, asis_usd, brazil_usd, liscr_usd, direct_usd = [], [], [], [], [], []
    
    for trade_idx, trade in trade_im.iterrows():

        # initiate selected voyages table as empty dataframe to begin
        int_arr_voys_vess = pd.DataFrame()

        # 3. If no facilitating vessel types were picked up for the HS code, take from full primary int. inv. voyages dataset, otherwise move on...
        if 'all' in trade.fac_vessel_types:
            hs_codes_not_mapped_to_HS.append(trade.HS4_desc)
            int_arr_voys_vess = int_arr_voys
            cost_int_match_desc.append("3. Primary Int. Inv. without Vess Type") if cost_int_match_desc_bool == False else None

        else:
            # 1. If possible, derive subset of voyages associated with the unique vessel type.
            int_arr_voys_vess = int_arr_voys[(int_arr_voys.vessel_type.isin(trade.fac_vessel_types))]    
            
            if int_arr_voys_vess.shape[0] > 0:
                cost_int_match_desc.append("1. Primary Int. Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                
            else:
                # 2. Finally, if no voyages are found as the vessel type doesn't appear in the country's shipping inventories, also take from full voyages dataset filtered for those vessel types instead.
                int_arr_voys_vess = voys_fem[(voys_fem.vessel_type.isin(trade.fac_vessel_types))]

                if int_arr_voys_vess.shape[0] > 0:
                    cost_int_match_desc.append("2. Global Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_inventories.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

                else:
                    # 4. Use full global voyage dataset as a back-up
                    int_arr_voys_vess = voys_fem
                    cost_int_match_desc.append("4. Global Inv. without Vess Type.") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_global_voys.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

        # Add cost intensities associated with the subset of voyages by vessel type, assuming 50% of NZF costs are borne by the importer.
        bau_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "bau35_usd_dwtnm_"+year))
        levy_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "levy35_usd_dwtnm_"+year))
        asis_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "asis35_usd_dwtnm_"+year))
        brazil_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "brazil35_usd_dwtnm_"+year))
        liscr_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "liscr35_usd_dwtnm_"+year))
        direct_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "direct35_usd_dwtnm_"+year))
    
    if cost_int_match_desc_bool == False:
        trade_im["cost_int_match_desc"] = cost_int_match_desc
    cost_int_match_desc_bool = True
    
    trade_im["bau_usd_"+year] = bau_usd
    trade_im["levy_usd_"+year] = levy_usd
    trade_im["asis_usd_"+year] = asis_usd
    trade_im["brazil_usd_"+year] = brazil_usd
    trade_im["liscr_usd_"+year] = liscr_usd
    trade_im["direct_usd_"+year] = direct_usd

print("Inventory voyages table used for the following vessel types: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_inventories).unique()))
print("Global voyages table used for the following vessel types found: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_global_voys).unique()))
print("Global voyages table used for the following commodities as no 'facilitating vessel types' were identified: \n\n{0}\n".format(pd.Series(hs_codes_not_mapped_to_HS).unique()))

print("\nNumber of trade records present in dataset: {0}".format(trade_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_im.partnerCode.unique())))
print("\nTotal value of trade: US${0}m".format(np.round(trade_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_im.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_im.sea_dist_nm.min(), 1),
    round(trade_im.sea_dist_nm.max(), 1),
    round(trade_im.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_im.vol_kg_vtw / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_im.cifvalue / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.cifvalue.sum() / 1000), 1)
))

print("\n\nTotal FEM costs in 2041...\n")
print("BAU: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.bau_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.bau_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Levy: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.levy_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.levy_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("'as-is': US${0}m ({1}% ad-val)".format(
    np.round(trade_im.asis_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.asis_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Brazil: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.brazil_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.brazil_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("LISCR: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.liscr_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.liscr_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Direct: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.direct_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.direct_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))

trade_im_agg = trade_im.groupby(["cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "cifvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_im_agg["vol_kg_vtw_pct"] = round(100 * trade_im_agg.vol_kg_vtw / trade_im_agg.vol_kg_vtw.sum(), 1)
trade_im_agg["cifvalue_pct"] = round(100 * trade_im_agg.cifvalue / trade_im_agg.cifvalue.sum(), 1)
print("Most prominent 'cost intensity match' types...\n\n{0}\n".format(
    trade_im_agg[["cost_int_match_desc", "vol_kg_vtw_pct", "cifvalue_pct"]].head(5)
))
trade_im_agg_2 = trade_im.groupby(["fac_vessel_types_str", "cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "cifvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_im_agg_2["vol_kg_vtw_pct"] = round(100 * trade_im_agg_2.vol_kg_vtw / trade_im_agg_2.vol_kg_vtw.sum(), 1)
trade_im_agg_2["cifvalue_pct"] = round(100 * trade_im_agg_2.cifvalue / trade_im_agg_2.cifvalue.sum(), 1)
print("Most prominent 'facilitating vessel types' and their 'cost intensity match' types...")
display(trade_im_agg_2[["fac_vessel_types_str", "cost_int_match_desc", "vol_kg_vtw_pct", "cifvalue_pct"]].head(5))

trade_im_na = trade_im[(trade_im[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (trade_im.fac_vessel_types.str.len() == 0)]
trade_im = trade_im[(~trade_im[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (~trade_im.fac_vessel_types.str.len() == 0)]
print("Rows with NA: ${0} ({1}%)\n".format(trade_im_na.primaryValue.sum(), round(100 * trade_im_na.primaryValue.sum() / trade_im.primaryValue.sum(), 1)))

trade_im.to_csv(output_dir + "{0}/impact_im_{1}.csv".format(iso_country, version), index=False)
trade_im.head(2)

Processing game year 2026
Processing game year 2029
Processing game year 2032
Processing game year 2035
Processing game year 2038
Processing game year 2041
Processing game year 2044
Processing game year 2047
Processing game year 2050
Inventory voyages table used for the following vessel types:

['Liquefied gas tanker']

Global voyages table used for the following vessel types found:

['Other liquids tankers' 'Ro-Ro' 'Cruise']

Global voyages table used for the following commodities as no 'facilitating vessel types' were identified:

['4403 | Wood in the rough, w' '3926 | Articles of plastics'
 '3507 | Enzymes; prepared en' '8517 | Telephone sets, incl'
 '1905 | Bread, pastry, cakes' '3824 | Prepared binders for'
 '4911 | Printed matter, n.e.' '9701 | Paintings, drawings '
 '8487 | Machinery parts; not' '6117 | Clothing accessories'
 '8462 | Machine-tools (inclu' '2009 | Fruit or nut juices '
 '3002 | Human blood; animal ' '3006 | Pharmaceutical goods'
 '3822 | Reagents; diagnostic' '4015 | Articles of apparel '
 '9403 | Furniture and parts ' '9405 | Luminaires and light'
 '4823 | Paper, paperboard, c' '2202 | Waters, including mi'
 '1509 | Olive oil and its fr' '5703 | Carpets and other te'
 '7326 | Iron or steel; artic' '8541 | Semiconductor device'
 '9027 | Instruments and appa' '9401 | Seats (not those of '
 '4414 | Wooden frames; for p' '6201 | Overcoats, car-coats'
 '4905 | Maps and hydrographi' '6406 | Footwear; parts of f'
 '3402 | Organic surface-acti' "4418 | Builders' joinery an"
 '4419 | Tableware and kitche' '7019 | Glass fibres (includ'
 '4420 | Wood marquetry and i' '7616 | Aluminium; articles '
 '0805 | Citrus fruit; fresh ' '9702 | Engravings, prints a'
 '6815 | Stone or other miner' '3812 | Prepared rubber acce'
 '8716 | Trailers and semi-tr' '1704 | Sugar confectionery '
 '6907 | Ceramic flags and pa' '2106 | Food preparations no'
 '2812 | Halides and halide o' "6202 | Coats; women's or gi"
 '8424 | Mechanical appliance' '4407 | Wood sawn or chipped'
 '5502 | Artificial filament ' '6310 | Rags; used or new, s'
 '0403 | Yogurt; buttermilk, ' '4011 | New pneumatic tyres,'
 '4412 | Plywood, veneered pa' '4504 | Agglomerated cork (w'
 '3215 | Ink; printing, writi' '8528 | Monitors and project'
 '1605 | Crustaceans, mollusc' '6812 | Fabricated asbestos '
 '9406 | Buildings; prefabric' '4421 | Wooden articles n.e.'
 '3307 | Perfumery, cosmetic ' '7419 | Copper; articles the'
 '8514 | Industrial or labora' '0910 | Ginger, saffron, tum'
 '3004 | Medicaments; (not go' '3707 | Chemical preparation'
 '8525 | Transmission apparat' '8803 | nan' '8903 | Yachts and other ves'
 '2935 | Sulphonamides' '9508 | Travelling circuses '
 '0714 | Manioc, arrowroot, s' '3907 | Polyacetals, other p'
 '0802 | Nuts (excluding coco' '8311 | Wires, rods, tubes, '
 '6005 | Fabrics; warp knit (' '0307 | Molluscs; whether in'
 '0410 | Animal products; ins' '0604 | Foliage, branches an'
 '9209 | Musical instrument p' '9706 | Antiques; of an age '
 '8432 | Agricultural, hortic' '3909 | Amino-resins, phenol'
 '4406 | Railway or tramway s' '1806 | Chocolate and other '
 '2403 | Manufactured tobacco' '8215 | Cutlery; spoons, for'
 '3705 | Photographic plates ' '8701 | Tractors; (other tha'
 '2903 | Halogenated derivati' '5802 | Fabrics; terry towel'
 '9006 | Cameras, photographi' '0306 | Crustaceans; in shel'
 '2939 | Alkaloids; natural o' '2309 | Preparations of a ki'
 '3105 | Fertilizers; mineral' '6914 | Ceramic articles; n.'
 '4602 | Basketwork, wickerwo' '9114 | Clock or watch parts'
 '0305 | Fish, dried, salted ' '2621 | Slag and ash n.e.c. '
 '7508 | Nickel; articles the' '5501 | Synthetic filament t'
 '8548 | Electrical parts of ' '6006 | Fabrics; knitted or '
 '1008 | Buckwheat, millet an' '3606 | Ferro-cerium and oth'
 '2530 | Mineral substances n' '7229 | Wire of other alloy '
 '1510 | Vegetable oils; oils' '6603 | Trimmings, parts and'
 '9703 | Sculptures and statu' '8460 | Machine-tools; for d'
 '8507 | Electric accumulator' '5911 | Textile products and'
 '2904 | Sulphonated, nitrate' '8456 | Machine-tools; for w'
 '2853 | Phosphides, chemical' '4401 | Fuel wood, in logs, '
 '1404 | Vegetable products n' '2922 | Oxygen-function amin'
 '3808 | Insecticides, rodent' '0308 | Aquatic invertebrate'
 '8473 | Machinery; parts and' '0210 | Meat and edible meat'
 '0303 | Fish; frozen, exclud' '8519 | Sound recording or r'
 '7104 | Stones; synthetic or' '6704 | Wigs, false beards, '
 '6217 | Clothing accessories' '3603 | Safety fuses; detona'
 '4707 | Waste and scrap of p' '9705 | Collections and coll'
 '0106 | Animals; live, n.e.c']


Number of trade records present in dataset: 18685
Number of partner countries present in dataset: 118

Total value of trade: US$1669.5m
Total weight within the dataset: 2489.2 million kilograms

Distance to market: 119.3 nm (min) to 12538.6 nm (max), 4290.8 nm (observed mean)
Average distance to market (volume-weighted): 3397.0 nm
Average distance to market (value-weighted): 4504.5 nm


Total FEM costs in 2041...

BAU: US$37.3m (2.2% ad-val)
Levy: US$78.9m (4.7% ad-val)
'as-is': US$75.6m (4.5% ad-val)
Brazil: US$77.2m (4.6% ad-val)
LISCR: US$53.0m (3.2% ad-val)
Direct: US$49.8m (3.0% ad-val)
Most prominent 'cost intensity match' types...

                      cost_int_match_desc  vol_kg_vtw_pct  cifvalue_pct
0     1. Primary Int. Inv. with Vess Type            96.4          89.4
1  3. Primary Int. Inv. without Vess Type             2.6           9.8
2           2. Global Inv. with Vess Type             1.0           0.7
3       4. Global Inv. without Vess Type.             0.0           0.0

Most prominent 'facilitating vessel types' and their 'cost intensity match' types...

,fac_vessel_types_str,cost_int_match_desc,vol_kg_vtw_pct,cifvalue_pct
0,['Container'],1. Primary Int. Inv. with Vess Type,55.2,54.7
1,['Bulk carrier'],1. Primary Int. Inv. with Vess Type,19.6,7.4
2,"['Container', 'Bulk carrier']",1. Primary Int. Inv. with Vess Type,11.3,9.2
3,['Chemical tanker'],1. Primary Int. Inv. with Vess Type,6.9,7.6
4,['all'],3. Primary Int. Inv. without Vess Type,2.6,9.8

Rows with NA: $0.0 (0.0%)

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_im_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,cost_int_match_desc,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50
0,0,332,Haiti,056,Belgium,000,World,Import,Sea,960400 | Hand sieves and hand,960400,NaN,0.0,408.663016,5425.309770,NaN,5425.309770,Belgium | 960400 | Hand sieves and hand,96,96 | Miscellaneous manufa,Belgium | 96 | Miscellaneous manufa,9604,9604 | Hand sieves and hand,Belgium | 9604 | Hand sieves and hand,96,9604,960400,Hand sieves & hand riddles,Other Manufacturing,3699,Other manufacturing n.e.c.,89981,Hand sieves & hand riddles,42,OMF - Manufactures n.e.c.,38999,"Articles n.e.c. (including candles, tapers, sk...",8.8881,0.1125,both,0.075325,610.347349,408.663016,[Container],['Container'],5855.0,3638.127205,2220.521295,1. Primary Int. Inv. with Vess Type,10.817501,10.797714,10.799694,10.799694,10.808540,10.808540,11.321960,20.144545,12.431538,11.603075,11.635601,11.915358,11.083337,19.695753,13.119421,12.038857,11.756308,12.297614,10.874053,21.520889,16.294823,14.258578,13.181824,12.821792,10.668646,22.850260,18.793340,17.543894,14.105488,13.747076,10.467116,23.229865,22.268585,22.505275,15.233870,14.443075,10.261546,22.746869,21.685752,23.704979,17.747177,14.710043,10.067885,20.209249,21.130133,22.117971,16.406213,14.884029,9.870412,18.571834,18.852698,23.115559,19.183815,14.985059
1,1,332,Haiti,070,Bosnia Herzegovina,000,World,Import,Sea,283630 | Carbonates; sodium h,283630,kg,19154.0,19154.000000,8587.831893,NaN,8587.831893,Bosnia Herzegovina | 283630 | Carbonates; sodi...,28,28 | Inorganic chemicals;,Bosnia Herzegovina | 28 | Inorganic chemicals;,2836,2836 | Carbonates; peroxoca,Bosnia Herzegovina | 2836 | Carbonates; peroxoca,28,2836,283630,Sodium hydrogencarbonate (sodium bicarbonate),"Petroleum, Chemical and Non-Metallic Mineral P...",2411,"Manufacture of basic chemicals, except fertili...",52373,Sodium hydrogencarbonate (sodium bicarbonate),33,"CRP - Chemical, rubber, plastic products",3424,Salts and peroxysalts of inorganic acids and m...,0.4353,2.2974,both,2.230365,19729.684992,19154.000000,[Container],['Container'],9081.0,5642.670051,111328.102619,1. Primary Int. Inv. with Vess Type,542.346464,541.354428,541.453680,541.453680,541.897203,541.897203,567.638039,1009.967327,623.267844,581.732035,583.362744,597.388660,555.674415,987.466703,657.755553,603.580392,589.414505,616.553424,545.181729,1078.971730,816.957578,714.868352,660.884216,642.833615,534.883437,1145.621142,942.223297,879.581017,707.193027,689.223712,524.779535,1164.652993,1116.458239,1128.324925,763.765628,724.118328,514.473099,1140.437514,1087.237345,1188.473320,889.772837,737.503021,504.763700,1013.211325,1059.380806,1108.907049,822.542245,746.226001,494.863200,931.117870,945.199280,1158.922174,961.800138,751.291223

## 2.4 Create Results Tables

### 2.4.1 Total Costs per Scenario

In [7]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        np.round(trade_im["bau_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["levy_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["asis_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["brazil_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["liscr_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["direct_usd_{0}".format(year)].sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% cif)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% fob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_fob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_im["bau_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["levy_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["asis_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["direct_usd_{0}".format(year)].sum() / gdp, 3),
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,BAU,40049531.09,39292562.80,38628911.68,37977550.11,37338500.09,36686527.69,36072370.31,35445971.37
1,Levy,68025564.35,66200323.56,72487021.46,77879356.48,78949765.05,76288803.44,68707753.67,63770984.84
2,'as-is',43309941.87,45522313.09,55406861.39,63779259.99,75648180.87,73248743.85,71398300.88,64636818.60
3,Brazil,40644341.11,42235891.48,49534522.56,59915553.55,77227614.44,79224156.93,75745403.62,77446204.92
4,LISCR,40756722.36,41397241.54,46206269.90,48946437.19,53039702.43,61124020.02,57939075.29,64564901.61
5,Direct,41874909.46,43065665.08,44703895.17,47614761.32,49785379.57,50604563.96,51136489.30,51451696.75

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0      BAU  2.40  2.35  2.31  2.27  2.24  2.20  2.16  2.12
1     Levy  4.07  3.97  4.34  4.66  4.73  4.57  4.12  3.82
2  'as-is'  2.59  2.73  3.32  3.82  4.53  4.39  4.28  3.87
3   Brazil  2.43  2.53  2.97  3.59  4.63  4.75  4.54  4.64
4    LISCR  2.44  2.48  2.77  2.93  3.18  3.66  3.47  3.87
5   Direct  2.51  2.58  2.68  2.85  2.98  3.03  3.06  3.08

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  0.265  0.260  0.256  0.252  0.247  0.243  0.239  0.235
1     Levy  0.451  0.439  0.480  0.516  0.523  0.506  0.455  0.423
2  'as-is'  0.287  0.302  0.367  0.423  0.501  0.485  0.473  0.428
3   Brazil  0.269  0.280  0.328  0.397  0.512  0.525  0.502  0.513
4    LISCR  0.270  0.274  0.306  0.324  0.351  0.405  0.384  0.428
5   Direct  0.278  0.285  0.296  0.316  0.330  0.335  0.339  0.341

### 2.4.2 Costs per Scenario relative to BAU

In [8]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        np.round((trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_usd_bau_{1}.csv".format(iso_country, version), index=False)
display(df)

print("\nTotal change in FEM costs by scenario (% bau)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        round((100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2)
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_bau_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% cif)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2)
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% fob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_fob_{1}.csv".format(iso_country, version), index=False)
    display(df)
    
print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3)
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,Levy,27976033.25,26907760.76,33858109.78,39901806.37,41611264.97,39602275.74,32635383.36,28325013.47
1,'as-is',3260410.78,6229750.29,16777949.71,25801709.88,38309680.78,36562216.16,35325930.57,29190847.23
2,Brazil,594810.02,2943328.68,10905610.88,21938003.44,39889114.35,42537629.24,39673033.31,42000233.56
3,LISCR,707191.27,2104678.74,7577358.22,10968887.08,15701202.34,24437492.32,21866704.98,29118930.24
4,Direct,1825378.36,3773102.28,6074983.50,9637211.22,12446879.49,13918036.27,15064118.99,16005725.38

Total change in FEM costs by scenario (% bau)...

  Scenario   2029   2032   2035    2038    2041    2044    2047    2050
0     Levy  69.85  68.48  87.65  105.07  111.44  107.95   90.47   79.91
1  'as-is'   4.56   9.60  15.73   25.38   33.34   37.94   41.76   45.16
2   Brazil   8.14  15.85  43.43   67.94  102.60   99.66   97.93   82.35
3    LISCR   1.49   7.49  28.23   57.77  106.83  115.95  109.98  118.49
4   Direct   1.77   5.36  19.62   28.88   42.05   66.61   60.62   82.15

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0     Levy  1.68  1.61  2.03  2.39  2.49  2.37  1.95  1.70
1  'as-is'  0.11  0.23  0.36  0.58  0.75  0.83  0.90  0.96
2   Brazil  0.20  0.37  1.00  1.55  2.29  2.19  2.12  1.75
3    LISCR  0.04  0.18  0.65  1.31  2.39  2.55  2.38  2.52
4   Direct  0.04  0.13  0.45  0.66  0.94  1.46  1.31  1.74

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  0.185  0.178  0.224  0.264  0.276  0.262  0.216  0.188
1  'as-is'  0.012  0.025  0.040  0.064  0.082  0.092  0.100  0.106
2   Brazil  0.022  0.041  0.111  0.171  0.254  0.242  0.234  0.193
3    LISCR  0.004  0.020  0.072  0.145  0.264  0.282  0.263  0.278
4   Direct  0.005  0.014  0.050  0.073  0.104  0.162  0.145  0.193

# 3. Let's consider Exports

## 3.1 Read-in Trade dataset

In [9]:
trade_ex_d = {
    "reporterCode":"str", "partnerCode":"str", "partner2Code":"str", 
    "cmdCode":"str", "HS2":"str", "HS4":"str", "hs2":"str", "hs4":"str", "hs6":"str",
    "isic":"str", "sitc":"str", "gtap":"str", "cpc":"str"
}
if res_mlc == False:
    trade_ex = pd.read_csv(input_dir+"trade/{0}/trade_ex_dist_{1}.csv".format(iso_country, version), dtype=trade_ex_d)
else:
    trade_ex = pd.read_csv(input_dir+"trade/{0}/trade_ex_mlc_{1}.csv".format(iso_country, version), dtype=trade_ex_d)
trade_ex['fac_vessel_types'] = [ast.literal_eval(x) for x in trade_ex.fac_vessel_types.values]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(trade_ex.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_ex.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(trade_ex.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(trade_ex.fobvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_ex.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_ex.sea_dist_nm.min(), 1),
    round(trade_ex.sea_dist_nm.max(), 1),
    round(trade_ex.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_ex.vol_kg_vtw / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_ex.fobvalue / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.fobvalue.sum() / 1000), 1)
))
trade_ex.head(2)

Aggregate trade portfolio statistics for 'Haiti':

Number of trade records present in dataset: 2236
Number of partner countries present in dataset: 89
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$131.4m
Total weight within the dataset: 110.2 million kilograms

Distance to market: 118.7 nm (min) to 12538.0 nm (max), 3133.8 nm (observed mean)
Average distance to market (volume-weighted): 4923.7 nm
Average distance to market (value-weighted): 3337.2 nm

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_ex_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm
0,0,332,Haiti,842,USA,000,World,Export,Sea,071140 | Vegetables; cucumber,71140,kg,435.645,435.645,NaN,1470.267855,1470.267855,USA | 071140 | Vegetables; cucumber,07,07 | Vegetables and certa,USA | 07 | Vegetables and certa,0711,0711 | Vegetables provision,USA | 0711 | Vegetables provision,07,0711,071140,"Cucumbers & gherkins, provisionally preserved",Agriculture,1513,Processing and preserving of fruit and vegetables,0547,"Vegetables provisionally preserved (e.g., by s...",25,OFD - Food products n.e.c.,2132,Vegetables provisionally preserved,1.1945,0.8372,both,0.296303,1230.908248,435.645,[Container],['Container'],2148.0,1334.704908,1642.899280
1,1,332,Haiti,842,USA,000,World,Export,Sea,081400 | Peel; of citrus frui,81400,kg,938.477,938.477,NaN,1755.284387,1755.284387,USA | 081400 | Peel; of citrus frui,08,"08 | Fruit and nuts, edib","USA | 08 | Fruit and nuts, edib",0814,0814 | Peel of citrus fruit,USA | 0814 | Peel of citrus fruit,08,0814,081400,"Peel of citrus fruit/melons, incl. watermelons...",Agriculture,1513,Processing and preserving of fruit and vegetables,05822,"Peel of citrus fruit/melons, fresh, frozen, dr...",25,OFD - Food products n.e.c.,2155,Other preserved fruits,1.7499,0.5715,both,0.534658,1003.145027,938.477,[Container],['Container'],2148.0,1334.704908,1338.902591

## 3.2 Derive Internationally Departing Voyages

In [10]:
# International Departures
int_arr_voys = voys_fem[(voys_fem.dest_country == iso_country) & (voys_fem.source_country != iso_country)].reset_index(drop=True)
int_arr_voys.to_csv(output_dir + "{0}/int_arr_voys_{1}.csv".format(iso_country, version), index=False)
int_dep_voys = voys_fem[(voys_fem.source_country == iso_country) & (voys_fem.dest_country != iso_country)].reset_index(drop=True)
int_dep_voys.to_csv(output_dir + "{0}/int_dep_voys_{1}.csv".format(iso_country, version), index=False)
voyages_analysis(int_dep_voys)
int_dep_voys.head(2)

Number of Voyages found: 585
Total size of the fleet: 230 vessels
6 vessel types contained in the dataset: ['General cargo' 'Vehicle' 'Chemical tanker' 'Container' 'Bulk carrier'
 'Oil tanker']
Total transport work capacity: 14759.5 million deadweight-tonne nautical miles
Total cargo transported: 7805003.2 tonnes
Total transport work: 8857.6 million tonne nautical miles
Average build year of the fleet: 2007
Total Energy Demands: 1756.0 EJ
Total CO2 produced: 134955.5 tonnes

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,17453,8121379,375401000,HTACA,332,HTI,HT,Haiti,Les Cayes,DOSPM,214,DOM,DO,Dominican Republic,San Pedro De Macoris,2018-05-26 00:00:00,2018-05-27 23:00:00,47.0,176.0,223.0,320.490201,2.853654,0.000830,2.854484,2.0186,11.0000,13.0186,0.0,0.0,0.0,0.0,0.0,0.0,0.200911,0.469733,15.35791,35.268584,50.626494,019,Americas,419,Latin America and the Caribbean,low_mid_income,1,1,019,Americas,419,Latin America and the Caribbean,upp_mid_income,0,1,0.670644,General cargo,3222.0,dwt,5350.0,146.0,NaN,NaN,NaN,2,5000-9999,1983.0,St Vincent & The Grenadines,MSD,1,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.02233,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.01858,0.018382,0.01842,0.013244,0.01391,0.014148,0.014473,0.01505,0.015474,0.015636,0.015745,0.015819,1.714623e+06,22710.084441,23251.846784,22995.578025,22770.817707,22550.22144,22333.789152,22113.018436,21905.036649,21692.961376,22707.471331,32563.951779,32099.616410,34386.277261,38072.997789,37697.274770,36529.434181,34469.345624,33192.738642,22706.482437,24132.901469,24731.084244,28388.052574,31261.191847,36788.488894,36130.277679,35464.750771,33305.662063,22706.482437,23219.953563,24024.756912,26853.993344,30198.115777,38288.334828,37031.210440,37334.196772,36948.623137,22708.209283,23234.633187,23739.992839,25694.337028,26418.490294,28199.696739,31858.099664,31518.210935,31582.710287,22708.209283,23849.772740,24258.881106,24816.172102,25805.658861,26532.096213,26810.113199,26997.227883,27122.889022,3422.558924,1.096897e+06
1,17456,8121379,375401000,HTJAK,332,HTI,HT,Haiti,Jacmel,DOSPM,214,DOM,DO,Dominican Republic,San Pedro De Macoris,2018-06-18 05:00:00,2018-06-23 11:00:00,126.0,128.0,254.0,330.272249,1.357393,0.345233,1.702625,9.1649,10.0449,19.2098,0.0,0.0,0.0,0.0,0.0,0.0,0.445908,0.442796,33.60959,33.279004,66.888594,019,Americas,419,Latin America and the Caribbean,low_mid_income,1,1,019,Americas,419,Latin America and the Caribbean,upp_mid_income,0,1,0.888704,General cargo,3222.0,dwt,5350.0,146.0,NaN,NaN,NaN,2,5000-9999,1983.0,St Vincent & The Grenadines,MSD,1,19.1,0.639731,0.013245,0.013561,0.013411,0.01328,0.013152,0.013025,0.012897,0.012775,0.012652,0.013243,0.018992,0.018721,0.020055,0.022205,0.021986,0.021305,0.020103,0.019359,0.013243,0.014075,0.014424,0.016556,0.018232,0.021456,0.021072,0.020684,0.019424,0.013243,0.013542,0.014012,0.015662,0.017612,0.02233,0.021597,0.021774,0.021549,0.013244,0.013551,0.013846,0.014985,0.015408,0.016447,0.01858,0.018382,0.01842,0.013244,0.01391,0.014148,0.014473,0.01505,0.015474,0.015636,0.015745,0.015819,1.766957e+06,23403.244913,23961.543005,23697.452373,23465.831888,23238.50255,23015.464285,22787.955174,22573.625336,22355.077072,23400.552045,33557.873411,33079.365531,35435.820175,39235.067318,38847.876426,37644.390839,35521.423962,34205.852198,23399.532968,24869.489367,25485.929964,29254.516808,32215.350453,37911.352457,37233.051224,36547.211008,34322.222284,23399.532968,23928.676334,24758.044007,27673.634801,31119.827021,39456.976905,38161.482385,38473.716509,38076.374340,23401.312521,23943.804011,24464.588323,26478.583288,27224.839264,29060.411949,32830.477176,32480.214314,32546.682325,23401.312521,24577.718943,24999.314174,25573.614885,26593.302902,27341.912680,27628.415340,27821.241166,27950.737751,3422.558924,1.130376e+06

## 3.3 Evaluate NZF Costs

In [11]:
years=["26", "29", "32", "35", "38", "41", "44", "47", "50"]
vess_types_not_found_in_inventories, vess_types_not_found_in_global_voys, hs_codes_not_mapped_to_HS, cost_int_match_desc, cost_int_match_desc_bool = [], [], [], [], False

for year in years:

    print("Processing game year 20{0}".format(year))

    # Setup columns for policy costs per bilateral goods trade.
    bau_usd, levy_usd, asis_usd, brazil_usd, liscr_usd, direct_usd = [], [], [], [], [], []
    
    for trade_idx, trade in trade_ex.iterrows():

        # initiate selected voyages table as empty dataframe to begin
        int_dep_voys_vess = pd.DataFrame()

        # 3. If no facilitating vessel types were picked up for the HS code, take from full primary int. inv. voyages dataset, otherwise move on...
        if 'all' in trade.fac_vessel_types:
            hs_codes_not_mapped_to_HS.append(trade.HS4_desc)
            int_dep_voys_vess = int_dep_voys
            cost_int_match_desc.append("3. Primary Int. Inv. without Vess Type") if cost_int_match_desc_bool == False else None

        else:
            # 1. If possible, derive subset of voyages associated with the unique vessel type.
            int_dep_voys_vess = int_dep_voys[(int_dep_voys.vessel_type.isin(trade.fac_vessel_types))]    
            
            if int_dep_voys_vess.shape[0] > 0:
                cost_int_match_desc.append("1. Primary Int. Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                
            else:
                # 2. Finally, if no voyages are found as the vessel type doesn't appear in the country's shipping inventories, also take from full voyages dataset filtered for those vessel types instead.
                int_dep_voys_vess = voys_fem[(voys_fem.vessel_type.isin(trade.fac_vessel_types))]
                
                if int_dep_voys_vess.shape[0] > 0:
                    cost_int_match_desc.append("2. Global Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_inventories.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

                else:
                    # 4. Use full global voyage dataset as a back-up
                    int_dep_voys_vess = voys_fem
                    cost_int_match_desc.append("4. Global Inv. without Vess Type.") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_global_voys.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]
    
        # Add cost intensities associated with the subset of voyages by vessel type, assuming 50% of NZF costs are borne by the exporter.
        bau_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "bau35_usd_dwtnm_"+year))
        levy_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "levy35_usd_dwtnm_"+year))
        asis_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "asis35_usd_dwtnm_"+year))
        brazil_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "brazil35_usd_dwtnm_"+year))
        liscr_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "liscr35_usd_dwtnm_"+year))
        direct_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "direct35_usd_dwtnm_"+year))

    if cost_int_match_desc_bool == False:
        trade_ex["cost_int_match_desc"] = cost_int_match_desc
    cost_int_match_desc_bool = True

    trade_ex["bau_usd_"+year] = bau_usd
    trade_ex["levy_usd_"+year] = levy_usd
    trade_ex["asis_usd_"+year] = asis_usd
    trade_ex["brazil_usd_"+year] = brazil_usd
    trade_ex["liscr_usd_"+year] = liscr_usd
    trade_ex["direct_usd_"+year] = direct_usd
    
print("Inventory voyages table used for the following vessel types: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_inventories).unique()))
print("Global voyages table used for the following vessel types found: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_global_voys).unique()))
print("Global voyages table used for the following commodities as no 'facilitating vessel types' were identified: \n\n{0}\n".format(pd.Series(hs_codes_not_mapped_to_HS).unique()))

print()
print("Number of trade records present in dataset: {0}".format(trade_ex.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_ex.partnerCode.unique())))
print("\nTotal value of trade: US${0}m".format(np.round(trade_ex.fobvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_ex.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_ex.sea_dist_nm.min(), 1),
    round(trade_ex.sea_dist_nm.max(), 1),
    round(trade_ex.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_ex.vol_kg_vtw / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_ex.fobvalue / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.fobvalue.sum() / 1000), 1)
))

print("\n\nTotal FEM costs in 2041...\n")
print("BAU: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.bau_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.bau_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Levy: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.levy_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.levy_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("'as-is': US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.asis_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.asis_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Brazil: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.brazil_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.brazil_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("LISCR: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.liscr_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.liscr_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Direct: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.direct_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.direct_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))

trade_ex_agg = trade_ex.groupby(["cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "fobvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_ex_agg["vol_kg_vtw_pct"] = round(100 * trade_ex_agg.vol_kg_vtw / trade_ex_agg.vol_kg_vtw.sum(), 1)
trade_ex_agg["fobvalue_pct"] = round(100 * trade_ex_agg.fobvalue / trade_ex_agg.fobvalue.sum(), 1)
print("Most prominent 'cost intensity match' types...\n\n{0}\n".format(
    trade_ex_agg[["cost_int_match_desc", "vol_kg_vtw_pct", "fobvalue_pct"]].head(5)
))
trade_ex_agg_2 = trade_ex.groupby(["fac_vessel_types_str", "cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "fobvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_ex_agg_2["vol_kg_vtw_pct"] = round(100 * trade_ex_agg_2.vol_kg_vtw / trade_ex_agg_2.vol_kg_vtw.sum(), 1)
trade_ex_agg_2["fobvalue_pct"] = round(100 * trade_ex_agg_2.fobvalue / trade_ex_agg_2.fobvalue.sum(), 1)
print("Most prominent 'facilitating vessel types' and their 'cost intensity match' types...")
display(trade_ex_agg_2[["fac_vessel_types_str", "cost_int_match_desc", "vol_kg_vtw_pct", "fobvalue_pct"]].head(5))

trade_ex_na = trade_ex[(trade_ex[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (trade_ex.fac_vessel_types.str.len() == 0)]
trade_ex = trade_ex[(~trade_ex[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (~trade_ex.fac_vessel_types.str.len() == 0)]
print("Rows with NA: ${0} ({1}%)\n".format(trade_ex_na.primaryValue.sum(), round(100 * trade_ex_na.primaryValue.sum() / trade_ex.primaryValue.sum(), 1)))

trade_ex.to_csv(output_dir + "{0}/impact_ex_{1}.csv".format(iso_country, version), index=False)
trade_ex.head(2)

Processing game year 2026
Processing game year 2029
Processing game year 2032
Processing game year 2035
Processing game year 2038
Processing game year 2041
Processing game year 2044
Processing game year 2047
Processing game year 2050
Inventory voyages table used for the following vessel types:

['Liquefied gas tanker']

Global voyages table used for the following vessel types found:

['Other liquids tankers']

Global voyages table used for the following commodities as no 'facilitating vessel types' were identified:

['1008 | Buckwheat, millet an' '2202 | Waters, including mi'
 '9401 | Seats (not those of ' '0403 | Yogurt; buttermilk, '
 '2106 | Food preparations no' '3822 | Reagents; diagnostic'
 '4421 | Wooden articles n.e.' '8456 | Machine-tools; for w'
 '8487 | Machinery parts; not' '4911 | Printed matter, n.e.'
 '8517 | Telephone sets, incl' '4419 | Tableware and kitche'
 '9405 | Luminaires and light' '9701 | Paintings, drawings '
 '2009 | Fruit or nut juices ' '3307 | Perfumery, cosmetic '
 '4420 | Wood marquetry and i' '4823 | Paper, paperboard, c'
 '2530 | Mineral substances n' '4707 | Waste and scrap of p'
 '9703 | Sculptures and statu' '8541 | Semiconductor device'
 '8903 | Yachts and other ves' '1806 | Chocolate and other '
 '3926 | Articles of plastics' '4602 | Basketwork, wickerwo'
 '3006 | Pharmaceutical goods' '3002 | Human blood; animal '
 '0802 | Nuts (excluding coco' '3402 | Organic surface-acti'
 '9403 | Furniture and parts ' '7326 | Iron or steel; artic'
 '9702 | Engravings, prints a' "4418 | Builders' joinery an"
 '8548 | Electrical parts of ' '9406 | Buildings; prefabric'
 '8716 | Trailers and semi-tr' '9705 | Collections and coll'
 '2939 | Alkaloids; natural o' '4015 | Articles of apparel '
 '5703 | Carpets and other te' '1704 | Sugar confectionery '
 '8525 | Transmission apparat' '4407 | Wood sawn or chipped'
 '6201 | Overcoats, car-coats' '6310 | Rags; used or new, s'
 '6907 | Ceramic flags and pa' '7616 | Aluminium; articles ' '8803 | nan'
 '0306 | Crustaceans; in shel' '3215 | Ink; printing, writi'
 '0910 | Ginger, saffron, tum' '6815 | Stone or other miner'
 '0604 | Foliage, branches an' '0210 | Meat and edible meat'
 '0511 | Animal products not ' '8528 | Monitors and project'
 '0106 | Animals; live, n.e.c' '1905 | Bread, pastry, cakes'
 '6117 | Clothing accessories' '6914 | Ceramic articles; n.'
 '5911 | Textile products and' '8459 | Machine-tools; (incl'
 '2309 | Preparations of a ki' '2403 | Manufactured tobacco'
 '2935 | Sulphonamides' '4414 | Wooden frames; for p'
 '5007 | Woven fabrics of sil' '0714 | Manioc, arrowroot, s'
 '9027 | Instruments and appa']


Number of trade records present in dataset: 2236
Number of partner countries present in dataset: 89

Total value of trade: US$131.4m
Total weight within the dataset: 110.2 million kilograms

Distance to market: 118.7 nm (min) to 12538.0 nm (max), 3133.8 nm (observed mean)
Average distance to market (volume-weighted): 4923.7 nm
Average distance to market (value-weighted): 3337.2 nm


Total FEM costs in 2041...

BAU: US$2.5m (1.9% ad-val)
Levy: US$5.3m (4.1% ad-val)
'as-is': US$5.1m (3.9% ad-val)
Brazil: US$5.2m (3.9% ad-val)
LISCR: US$3.5m (2.7% ad-val)
Direct: US$3.3m (2.5% ad-val)
Most prominent 'cost intensity match' types...

                      cost_int_match_desc  vol_kg_vtw_pct  fobvalue_pct
0     1. Primary Int. Inv. with Vess Type            97.8          96.4
1  3. Primary Int. Inv. without Vess Type             2.1           3.5
2       4. Global Inv. without Vess Type.             0.0           0.0
3           2. Global Inv. with Vess Type             0.0           0.0

Most prominent 'facilitating vessel types' and their 'cost intensity match' types...

,fac_vessel_types_str,cost_int_match_desc,vol_kg_vtw_pct,fobvalue_pct
0,['Container'],1. Primary Int. Inv. with Vess Type,67.7,76.4
1,['Bulk carrier'],1. Primary Int. Inv. with Vess Type,20.1,13.0
2,['Chemical tanker'],1. Primary Int. Inv. with Vess Type,5.2,2.8
3,"['Container', 'Bulk carrier']",1. Primary Int. Inv. with Vess Type,3.2,1.1
4,['all'],3. Primary Int. Inv. without Vess Type,2.1,3.5

Rows with NA: $0.0 (0.0%)

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_ex_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,cost_int_match_desc,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50
0,0,332,Haiti,842,USA,000,World,Export,Sea,071140 | Vegetables; cucumber,71140,kg,435.645,435.645,NaN,1470.267855,1470.267855,USA | 071140 | Vegetables; cucumber,07,07 | Vegetables and certa,USA | 07 | Vegetables and certa,0711,0711 | Vegetables provision,USA | 0711 | Vegetables provision,07,0711,071140,"Cucumbers & gherkins, provisionally preserved",Agriculture,1513,Processing and preserving of fruit and vegetables,0547,"Vegetables provisionally preserved (e.g., by s...",25,OFD - Food products n.e.c.,2132,Vegetables provisionally preserved,1.1945,0.8372,both,0.296303,1230.908248,435.645,[Container],['Container'],2148.0,1334.704908,1642.899280,1. Primary Int. Inv. with Vess Type,8.013118,7.998472,7.999937,7.999937,8.006485,8.006485,8.386716,14.921006,9.209374,8.594839,8.618919,8.826297,8.209994,14.589011,9.718513,8.917778,8.708562,9.109422,8.054999,15.939586,12.070425,10.561972,9.764502,9.497653,7.902876,16.924603,13.919873,12.995298,10.448806,10.182982,7.753625,17.204805,16.491890,16.666599,11.285423,10.698506,7.601382,16.847154,16.062705,17.559065,13.143160,10.896229,7.457958,14.968751,15.649976,16.381927,12.153697,11.025105,7.311711,13.755835,13.964203,17.126898,14.212621,11.099909
1,1,332,Haiti,842,USA,000,World,Export,Sea,081400 | Peel; of citrus frui,81400,kg,938.477,938.477,NaN,1755.284387,1755.284387,USA | 081400 | Peel; of citrus frui,08,"08 | Fruit and nuts, edib","USA | 08 | Fruit and nuts, edib",0814,0814 | Peel of citrus fruit,USA | 0814 | Peel of citrus fruit,08,0814,081400,"Peel of citrus fruit/melons, incl. watermelons...",Agriculture,1513,Processing and preserving of fruit and vegetables,05822,"Peel of citrus fruit/melons, fresh, frozen, dr...",25,OFD - Food products n.e.c.,2155,Other preserved fruits,1.7499,0.5715,both,0.534658,1003.145027,938.477,[Container],['Container'],2148.0,1334.704908,1338.902591,1. Primary Int. Inv. with Vess Type,6.530397,6.518461,6.519655,6.519655,6.524991,6.524991,6.834866,12.160072,7.505301,7.004478,7.024102,7.193108,6.690843,11.889508,7.920231,7.267662,7.097158,7.423845,6.564529,12.990177,9.836953,8.607619,7.957711,7.740238,6.440554,13.792930,11.344185,10.590691,8.515394,8.298756,6.318920,14.021285,13.440285,13.582666,9.197205,8.718890,6.194847,13.729812,13.090515,14.309993,10.711193,8.880027,6.077962,12.198983,12.754156,13.350669,9.904817,8.985055,5.958776,11.210501,11.380313,13.957793,11.582765,9.046018

## 3.4 Create Results Tables

### 3.4.1 Total Costs per Scenario

In [12]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        np.round(trade_ex["bau_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["levy_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["asis_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["brazil_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["liscr_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["direct_usd_{0}".format(year)].sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% cif)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
    display(df)

    
print("\nTotal FEM costs by scenario (% fob)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_fob_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / gdp, 3)
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,BAU,2644381.41,2591822.78,2545726.58,2500484.37,2456096.62,2410818.12,2368163.12,2324668.68
1,Levy,4587124.21,4476975.99,4891755.19,5224704.65,5325262.15,5166854.12,4626995.25,4276086.81
2,'as-is',2880262.09,3029756.26,3729780.75,4288411.25,5099105.55,4949751.34,4820388.57,4336201.91
3,Brazil,2696772.22,2799693.80,3297597.29,4017106.20,5175887.71,5381464.91,5077334.15,5255771.66
4,LISCR,2704159.54,2739304.19,3062707.08,3261698.84,3533414.29,4100667.57,3831784.57,4378067.93
5,Direct,2773378.15,2856945.34,2971645.24,3174684.46,3326799.50,3384717.73,3422374.90,3444377.45

Total FEM costs by scenario (% fob)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0      BAU  2.01  1.97  1.94  1.90  1.87  1.84  1.80  1.77
1     Levy  3.49  3.41  3.72  3.98  4.05  3.93  3.52  3.26
2  'as-is'  2.19  2.31  2.84  3.26  3.88  3.77  3.67  3.30
3   Brazil  2.05  2.13  2.51  3.06  3.94  4.10  3.87  4.00
4    LISCR  2.06  2.09  2.33  2.48  2.69  3.12  2.92  3.33
5   Direct  2.11  2.17  2.26  2.42  2.53  2.58  2.61  2.62

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  0.018  0.017  0.017  0.017  0.016  0.016  0.016  0.015
1     Levy  0.030  0.030  0.032  0.035  0.035  0.034  0.031  0.028
2  'as-is'  0.019  0.020  0.025  0.028  0.034  0.033  0.032  0.029
3   Brazil  0.018  0.019  0.022  0.027  0.034  0.036  0.034  0.035
4    LISCR  0.018  0.018  0.020  0.022  0.023  0.027  0.025  0.029
5   Direct  0.018  0.019  0.020  0.021  0.022  0.022  0.023  0.023

### 3.4.2 Costs per Scenario relative to BAU

In [13]:
print("\nTotal FEM costs by scenario (US$)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:

    d_temp = {"20{0}".format(year): [
        np.round((trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_usd_bau_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal change in FEM costs by scenario (% bau)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        round((100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_bau_{1}.csv".format(iso_country, version), index=False)
display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% cif)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_cif_{1}.csv".format(iso_country, version), index=False)
    display(df)


print("\nTotal FEM costs by scenario (% fob)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_fob_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,Levy,1942742.81,1885153.21,2346028.61,2724220.28,2869165.53,2756035.99,2258832.13,1951418.14
1,'as-is',235880.69,437933.48,1184054.17,1787926.88,2643008.93,2538933.22,2452225.45,2011533.24
2,Brazil,52390.81,207871.03,751870.71,1516621.84,2719791.09,2970646.78,2709171.03,2931102.98
3,LISCR,59778.13,147481.42,516980.50,761214.47,1077317.67,1689849.45,1463621.45,2053399.25
4,Direct,128996.74,265122.56,425918.66,674200.09,870702.88,973899.61,1054211.77,1119708.78

Total change in FEM costs by scenario (% bau)...

  Scenario   2029   2032   2035    2038    2041    2044    2047    2050
0     Levy  73.47  72.73  92.16  108.95  116.82  114.32   95.38   83.94
1  'as-is'   8.92  16.90  46.51   71.50  107.61  105.31  103.55   86.53
2   Brazil   1.98   8.02  29.53   60.65  110.74  123.22  114.40  126.09
3    LISCR   2.26   5.69  20.31   30.44   43.86   70.09   61.80   88.33
4   Direct   4.88  10.23  16.73   26.96   35.45   40.40   44.52   48.17

Total FEM costs by scenario (% fob)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0     Levy  1.48  1.44  1.79  2.07  2.18  2.10  1.72  1.49
1  'as-is'  0.18  0.33  0.90  1.36  2.01  1.93  1.87  1.53
2   Brazil  0.04  0.16  0.57  1.15  2.07  2.26  2.06  2.23
3    LISCR  0.05  0.11  0.39  0.58  0.82  1.29  1.11  1.56
4   Direct  0.10  0.20  0.32  0.51  0.66  0.74  0.80  0.85

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  0.013  0.012  0.016  0.018  0.019  0.018  0.015  0.013
1  'as-is'  0.002  0.003  0.008  0.012  0.018  0.017  0.016  0.013
2   Brazil  0.000  0.001  0.005  0.010  0.018  0.020  0.018  0.019
3    LISCR  0.000  0.001  0.003  0.005  0.007  0.011  0.010  0.014
4   Direct  0.001  0.002  0.003  0.004  0.006  0.006  0.007  0.007