<h2>Impact (v0.64) - 'Impact (v0.64).ipynb'</h2>

<u><h4>Context</h4></u>

The aim of the 'Impact' notebooks are to explore economic impacts resulsting from the FEM outputs in the lead-up to Autumn 2026, taking foward outputs from the associated 'Trade' notebooks.

<u><h4>Version Documentation and Future Work</h4></u>

'v0.2' cleaned up the analysis code by introducing the cost intensity estimation functions that were previously in the 'inventories' notebooks. For example, the 'get_usd_per_tnm' function is included here and applied to voyages identified as relevant to each individual trade record. The NZF costs associated with each trade record are now evaluated like this. 'v0.3' introduced the exporter- and importer-side trade portfolios at an HS-digit 4 level of resolution. With this implemented, the matching algorithm is now be being evaluated using the cargo weight field rather than value, and the process will be being conducted at the HS-digit 4 level of resolution. Since we are now confident regarding the use of the Global Shipping Watch dataset for the purposes of matching HS codes with facilitating vessel types, we should then be in good shape to take the analysis forward using the results produced in this notebook. 'v0.3' also subsumed the 'inventories' notebooks. In 'v0.4' sought to include transport costs data from UNCTAD's Trade-and-Transport database. However, there are now concerns regarding this dataset as it is importer-side only, and therefore has odd looking exporter-side portfolios. Instead, it makes sense for us to utilise trade portfolios derived from UN Comtrade, where these are submitted with disaggregation by Transport Mode. Looking at the 16 countries of interest across African and Caribbean economies we're interested in the summer of 2026, 13 of these have a trade portfolio with MoT Breakdown available across at least one year within the last decade. Therefore this approach makes more sense, and 'v0.6' was amended to work with Comtrade import and export trade portfolios downloaded from the platform. 'v0.61' made use of the updated 'trade' notebooks that derive a new weight field using Value-to-Weight and Weight-to-Value ratios observed in the CEPII BACI datasets across 2017-23. In the case of Trinidad and Tobaogo, import volumes were around 65% higher under the WtV approach which corresponded to a 39% greater 2041 BAU impact from FEM costs, but this was slightly less for exports where the weighted WtV was 9% more but 2041 FEM costs under BAU were around 10% less. A new 'composite' weight field has been added in Trade (v0.61) which only introduces the VtW-derived values where 'netWgt' is observed to be zero, however this resulted in only a tiny increase in recorded weight of around 1% for Angola, whereas the full VtW-derived field was ~50% greater. 

'v0.62' makes use of a new 'transport cost' field derived using ad-valorem transport cost rates identified from UNCTAD's Trade-and-Transport database. With these, we can now introduce another results disaggregation that presents NZF costs relative to expected transport costs, which is then fully in-line with how impacts are expressed in UNCTAD's CIA Task 3 work. 'v0.63' includes an assessment of 'Cost Intensity' matching process (similar to CIF-FOB matching), plus metrics on 'fac_vessel_types' and 'average sea-distance' (introduced in Trade v0.63). 'v0.64' has been modified throughout to account for a new scenario, namely the 'Japan' proposal, plus to remove the 'Low-then-High' scenario. In terms of the Impact notebook, this remains the same as 'v0.63'.

In [1]:
# Import packages
import os
import ast
import base64
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 250)
pd.set_option('display.max_rows', 250)
pd.options.mode.chained_assignment = None
from IPython.display import HTML
import matplotlib.pyplot as plt
import matplotlib.style
plt.style.use('seaborn-v0_8')

def voyages_analysis(voys):
    # Define a function to analyses key statistics from a given set of voyages, 'voys'.
    print("Number of Voyages found: {0}".format(voys.shape[0]))
    print("Total size of the fleet: {0} vessels".format(len(voys.imo.unique())))
    print("{0} vessel types contained in the dataset: {1}".format(len(voys.vessel_type.unique()), voys.vessel_type.unique()))
    print("Total transport work capacity: {0} million deadweight-tonne nautical miles".format(np.round(voys.dwtnm.sum() / 1e6, 1)))
    print("Total cargo transported: {0} tonnes".format(np.round(voys.tonnes.sum(), 1)))
    print("Total transport work: {0} million tonne nautical miles".format(np.round(voys.tnm.sum() / 1e6, 1)))
    print("Average build year of the fleet: {0}".format(int(np.round(voys.year_of_built.mean(), 0))))
    print("Total Energy Demands: {0} EJ".format(np.round(voys.energy_tj.sum(), 1)))
    print("Total CO2 produced: {0} tonnes".format(np.round(voys.co2_t.sum(), 1)))

def get_usd_per_dwtnm(voys, field_name):
    # Derive the deadweight-average of the cost intensity (per unit of cargo-carrying capacity) for the field 'field_name' in an input selection of voyages, 'voys'.
    return (voys[field_name].values * voys.deadweight.values).sum() / voys.deadweight.sum()
    
def get_usd_per_tnm(voys, field_name):
    # Derive the deadweight-average of the cost intensity (per unit of cargo-carried) for the field 'field_name' in an input selection of voyages, 'voys'.
    return (voys[field_name].values / voys.class_util.values * voys.tonnes.values).sum() / voys.tonnes.sum()

def download_link(df, title = "Download CSV file", filename = "data.csv"):
    csv = df.to_csv()
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
    html = html.format(payload=payload,title=title,filename=filename)
    return HTML(html)

version = "v0.64"
input_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/"
voys_fem_dir = "/Users/apple/repos/datasets/ucl/fleet evolution model/2026 annex vi amendments (v0.2)/2. NZF Impact Costs for 2018 IMO IV Voyages/voys_fem_v0.2.csv"
output_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/impact/"
res_mlc = False

# 1. Set up the notebook

## 1.1 Let's set the country we're interested in and set up a results folder.

In [2]:
# Select one of our countries to work on...
iso_code = "242"
iso_country = "Fiji"
year = 2025
import_portfolio = "h6_ag6_by_sea_M*.csv" # Imports, '_M' | Foreign Imports, '_FM' | Re-Imports, '_RM'
export_portfolio = "h6_ag6_by_sea_DX*.csv" # Exports, '_X' | Domestic Exports, '_DX' | Re-exports, '_RX'
gdp = 6.200*1e9

# Create output Journey directory folder if necessary
os.makedirs(output_dir+"{0}/".format(iso_country)) if not os.path.exists(output_dir+"{0}/".format(iso_country)) else "Output directory already exists."
os.makedirs(output_dir+"{0}/results/".format(iso_country)) if not os.path.exists(output_dir+"{0}/results/".format(iso_country)) else "Output results folder already exists."

## 1.2 Voyages with FEM Results

In [3]:
voys_fem_d = {
    "source_iso":str, "source_iso_code":str, "source_iso_3":str, "source_iso_2":str, 
    "dest_iso_code":str, "dest_iso_code":str, "dest_iso_3":str, "dest_iso_2":str, 
    "source_region_code":str, "source_sub_region_code":str, "dest_region_code":str, "dest_sub_region_code":str, 
    "source_ldc":str, "source_sids":str, "dest_ldc":str, "dest_sids":str
}

voys_fem = pd.read_csv(voys_fem_dir, dtype=voys_fem_d)
voys_fem["dwtnm"] = voys_fem.deadweight * voys_fem.dist_travelled_ais
voys_fem["tonnes"] = voys_fem.deadweight * voys_fem.class_util
voys_fem["tnm"] = voys_fem.tonnes * voys_fem.dist_travelled_ais
voys_fem.loc[voys_fem.source_country == "Namibia", "source_iso_2"] = "NA"
voys_fem.loc[voys_fem.dest_country == "Namibia", "dest_iso_2"] = "NA"

countries_set = pd.Series(list(set(list(voys_fem.source_country.unique()) + list(voys_fem.dest_country.unique())))).sort_values()
print("Number of countries present in dataset: {0}.".format(len(countries_set)))
print("Number of IMO numbers present in dataset: {0}.".format(len(voys_fem.imo.unique())))
print("Total CO2 contained within the dataset: {0} million tonnes.".format(np.round(voys_fem.co2_t.sum() / 1e6, 1)))
print("Vessel types present in dataset: \n\n{0}\n".format(pd.Series(voys_fem.vessel_type.unique()).sort_values().values))
#print("\nCountries in dataset: \n\n", countries_set.values, "\n")
voys_fem.head(2)

Number of countries present in dataset: 207.
Number of IMO numbers present in dataset: 26132.
Total CO2 contained within the dataset: 544.7 million tonnes.
Vessel types present in dataset:

['Bulk carrier' 'Chemical tanker' 'Container' 'General cargo'
 'Liquefied gas tanker' 'Oil tanker' 'Refrigerated bulk' 'Vehicle']

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,0,5034525,413781699,CNTAX,156,CHN,CN,China,Taixing,CNNKG,156,CHN,CN,China,Nanjing,2018-01-01 06:00:00,2018-01-01 19:00:00,13.0,1.0,14.0,62.568523,0.0,0.0,0.0,3.635661,0.338483,3.974144,0.0,0.0,0.0,0.0,0.0,0.0,0.155243,0.014453,11.655930,1.085176,12.741107,142,Asia,030,Eastern Asia,upp_mid_income,0,0,142,Asia,030,Eastern Asia,upp_mid_income,0,0,0.169696,Refrigerated bulk,3786.0,dwt,3881.0,NaN,NaN,NaN,NaN,2,2000-5999,1959.0,Panama,SSD,4,76.1,0.666667,0.03155,0.032676,0.032143,0.031676,0.031218,0.030769,0.03031,0.029878,0.029438,0.031576,0.052178,0.052414,0.05804,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.05942,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,242828.439338,7661.320668,7934.549945,7805.304846,7691.950531,7580.696290,7471.542086,7360.199865,7255.307537,7148.350725,7667.458038,12670.391275,12727.642802,14093.647297,14570.027623,14398.931835,14189.590704,14139.488873,14161.462401,7665.715352,8412.516422,8946.627490,10860.650719,12049.492896,13084.201484,14034.766615,14342.763237,14083.751009,7665.715352,7946.962662,8384.668998,9891.651071,11698.979626,13565.379532,13949.851660,14247.178318,14428.769963,7663.482493,7940.155892,8209.623358,9221.805242,9744.436151,10159.112402,10518.004352,10853.785659,11140.079340,7663.482493,8252.567981,8473.856677,8773.523328,9299.485535,9694.695953,9860.244395,9979.919640,10068.487874,2587.333335,161885.626306
1,1,5034525,413781699,CNNKG,156,CHN,CN,China,Nanjing,CNTOL,156,CHN,CN,China,Tongling,2018-01-01 20:00:00,2018-01-04 17:00:00,69.0,59.0,128.0,134.252308,0.0,0.0,0.0,21.355373,19.491146,40.846519,0.0,0.0,0.0,0.0,0.0,0.0,0.911874,0.832272,68.465325,62.488615,130.953940,142,Asia,030,Eastern Asia,upp_mid_income,0,0,142,Asia,030,Eastern Asia,upp_mid_income,0,0,1.744146,Refrigerated bulk,3786.0,dwt,3881.0,NaN,NaN,NaN,NaN,2,2000-5999,1959.0,Panama,SSD,4,76.1,0.666667,0.03155,0.032676,0.032143,0.031676,0.031218,0.030769,0.03031,0.029878,0.029438,0.031576,0.052178,0.052414,0.05804,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.05942,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,521033.206847,16438.776642,17025.040451,16747.721252,16504.498662,16265.782167,16031.571689,15792.666415,15567.600579,15338.105010,16451.945500,27186.661563,27309.505274,30240.519881,31262.681739,30895.564166,30446.384156,30338.881438,30386.029694,16448.206246,18050.605691,19196.639505,23303.529390,25854.409564,28074.567693,30114.180516,30775.044079,30219.285570,16448.206246,17051.674227,17990.853906,21224.361910,25102.318690,29107.023950,29931.979818,30569.949005,30959.587375,16443.415234,17037.069045,17615.261197,19787.084130,20908.485145,21798.249530,22568.318408,23288.799137,23903.095037,16443.415234,17707.406809,18182.222523,18825.212595,19953.761526,20801.758375,21156.973093,21413.758406,21603.797889,2587.333335,347355.471405

# 2. Let's consider Imports

## 2.1 Read-in Trade dataset

In [4]:
trade_im_d = {
    "reporterCode":"str", "partnerCode":"str", "partner2Code":"str", 
    "cmdCode":"str", "HS2":"str", "HS4":"str", "hs2":"str", "hs4":"str", "hs6":"str",
    "isic":"str", "sitc":"str", "gtap":"str", "cpc":"str"
}
if res_mlc == False:
    trade_im = pd.read_csv(input_dir+"trade/{0}/trade_im_dist_{1}.csv".format(iso_country, version), dtype=trade_im_d)
else:
    trade_im = pd.read_csv(input_dir+"trade/{0}/trade_im_mlc_{1}.csv".format(iso_country, version), dtype=trade_im_d)
trade_im['fac_vessel_types'] = [ast.literal_eval(x) for x in trade_im.fac_vessel_types.values]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(trade_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_im.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(trade_im.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(trade_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_im.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_im.sea_dist_nm.min(), 1),
    round(trade_im.sea_dist_nm.max(), 1),
    round(trade_im.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_im.vol_kg_vtw / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_im.cifvalue / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.cifvalue.sum() / 1000), 1)
))
trade_im.head(2)

Aggregate trade portfolio statistics for 'Fiji':

Number of trade records present in dataset: 25663
Number of partner countries present in dataset: 150
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$2630.1m
Total weight within the dataset: 2171.1 million kilograms

Distance to market: 459.2 nm (min) to 13119.0 nm (max), 5611.4 nm (observed mean)
Average distance to market (volume-weighted): 4543.5 nm
Average distance to market (value-weighted): 4550.3 nm

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_im_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm
0,0,242,Fiji,528,Netherlands,000,World,Import,Sea,"901380 | Optical devices, app",901380,u,5.75,NaN,2600.342625,NaN,2600.342625,"Netherlands | 901380 | Optical devices, app",90,"90 | Optical, photographi","Netherlands | 90 | Optical, photographi",9013,"9013 | Lasers, other than l","Netherlands | 9013 | Lasers, other than l",90,9013,901380,Liquid crystal devices not constituting articl...,Other Manufacturing,3320,Manufacture of optical instruments and photogr...,87193,"Other optical devices, appliances & instruments",41,OME - Machinery and equipment n.e.c.,48315,"Liquid crystal devices n.e.c.; lasers, except ...",80.1834,0.0125,both,NaN,32.504283,NaN,[Container],['Container'],18430.0,11451.86753,372.234741
1,1,242,Fiji,528,Netherlands,000,World,Import,Sea,901910 | Mechano-therapy appl,901910,kg,1.47,1.47,15.984780,NaN,15.984780,Netherlands | 901910 | Mechano-therapy appl,90,"90 | Optical, photographi","Netherlands | 90 | Optical, photographi",9019,"9019 | Mechano-therapy, mas","Netherlands | 9019 | Mechano-therapy, mas",90,9019,901910,Mechano-therapy appliances; massage apparatus;...,Other Manufacturing,3311,Manufacture of medical and surgical equipment ...,87231,Mechanotherapy appliances; massage apparatus; ...,41,OME - Machinery and equipment n.e.c.,4816,Mechano-therapy appliances; massage apparatus;...,28.4774,0.0351,both,0.091962,0.561066,1.47,[Container],['Container'],18430.0,11451.86753,6.425251

## 2.2 Derive Internationally Arriving Voyages

In [5]:
# International Arrivals
int_arr_voys = voys_fem[(voys_fem.dest_country == iso_country) & (voys_fem.source_country != iso_country)].reset_index(drop=True)
int_arr_voys.to_csv(output_dir + "{0}/int_arr_voys_{1}.csv".format(iso_country, version), index=False)
int_dep_voys = voys_fem[(voys_fem.source_country == iso_country) & (voys_fem.dest_country != iso_country)].reset_index(drop=True)
int_dep_voys.to_csv(output_dir + "{0}/int_dep_voys_{1}.csv".format(iso_country, version), index=False)
voyages_analysis(int_arr_voys)
int_arr_voys.head(2)

Number of Voyages found: 274
Total size of the fleet: 112 vessels
6 vessel types contained in the dataset: ['Refrigerated bulk' 'Bulk carrier' 'General cargo' 'Container' 'Vehicle'
 'Chemical tanker']
Total transport work capacity: 15645.1 million deadweight-tonne nautical miles
Total cargo transported: 4315062.1 tonnes
Total transport work: 9289.3 million tonne nautical miles
Average build year of the fleet: 2007
Total Energy Demands: 1678.0 EJ
Total CO2 produced: 129607.3 tonnes

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,31613,8604967,372768000,TWKHH,158,TWN,TW,"Taiwan, Province of China",Kaohsiung,FJLEV,242,FJI,FJ,Fiji,Levuka,2018-05-21 22:00:00,2018-08-04 22:00:00,1800.0,165.0,1965.0,9149.579308,118.561155,0.000203,118.561358,490.7425,48.76,539.5025,0.0,0.0,0.0,0.0,0.0,0.0,25.720863,2.082060,1942.519891,156.325192,2098.845083,142,Asia,030,Eastern Asia,upp_mid_income,0,0,009,Oceania,054,Melanesia,upp_mid_income,0,1,27.802923,Refrigerated bulk,2525.0,dwt,2800.0,NaN,NaN,NaN,NaN,2,2000-5999,1986.0,Panama,SSD,1,76.1,0.666667,0.031550,0.032676,0.032143,0.031676,0.031218,0.030769,0.030310,0.029878,0.029438,0.031576,0.052178,0.052414,0.058040,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.059420,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,2.561882e+07,808282.635640,837108.798785,823473.216404,811514.139379,799776.623746,788260.665641,776513.867928,765447.545214,754163.415776,808930.138777,1.336748e+06,1.342788e+06,1.486904e+06,1.537163e+06,1.519112e+06,1.497026e+06,1.491741e+06,1.494059e+06,808746.282379,887535.092237,943884.737449,1.145818e+06,1.271242e+06,1.380406e+06,1.480692e+06,1.513186e+06,1.485860e+06,808746.282379,838418.362081,884597.140644,1.043586e+06,1.234263e+06,1.431171e+06,1.471734e+06,1.503102e+06,1.522260e+06,808510.711846,837700.235945,866129.521569,972916.468248,1.028055e+06,1.071804e+06,1.109668e+06,1.145093e+06,1.175298e+06,808510.711846,870660.253959,894006.595708,925621.947716,981111.874022,1.022807e+06,1.040273e+06,1.052899e+06,1.062243e+06,1866.666668,1.707921e+07
1,40462,8806503,373264000,CNLKU,156,CHN,CN,China,Longkou,FJVAT,242,FJI,FJ,Fiji,Vatia Wharf,2018-01-07 06:00:00,2018-01-25 11:00:00,437.0,3.0,440.0,4657.789974,210.147129,0.511217,210.658347,0.0000,0.00,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,8.447915,0.020551,654.398161,1.591931,655.990092,142,Asia,030,Eastern Asia,upp_mid_income,0,0,009,Oceania,054,Melanesia,upp_mid_income,0,1,8.468466,Bulk carrier,38337.0,dwt,70424.0,NaN,NaN,NaN,NaN,4,60000-99999,1990.0,Panama,SSD,1,4.1,0.526316,0.002221,0.002300,0.002262,0.002230,0.002198,0.002167,0.002135,0.002105,0.002074,0.002217,0.003631,0.003523,0.003915,0.004274,0.004276,0.004123,0.003866,0.003574,0.002217,0.002414,0.002495,0.003009,0.003449,0.004105,0.003936,0.003844,0.003749,0.002217,0.002282,0.002388,0.002784,0.003264,0.004337,0.004165,0.004176,0.004096,0.002219,0.002290,0.002358,0.002635,0.002787,0.003024,0.003409,0.003302,0.003461,0.002219,0.002379,0.002433,0.002509,0.002646,0.002745,0.002780,0.002801,0.002813,3.280202e+08,728578.640096,754309.257213,742137.954787,731463.123369,720986.060600,710706.763031,700221.414955,690343.467924,680271.103711,727176.351531,1.191140e+06,1.155465e+06,1.284361e+06,1.402095e+06,1.402535e+06,1.352583e+06,1.268107e+06,1.172397e+06,727342.848209,791731.191188,818254.118226,9.871492e+05,1.131391e+06,1.346656e+06,1.291053e+06,1.260994e+06,1.229745e+06,727342.848209,748448.852188,783198.037111,9.133012e+05,1.070808e+06,1.422675e+06,1.366224e+06,1.369785e+06,1.343730e+06,727957.701418,751326.464880,773597.844481,864351.266340,9.142397e+05,9.920753e+05,1.118211e+06,1.083128e+06,1.135361e+06,727957.701418,780505.072096,798228.400425,822918.176556,867983.641015,9.005136e+05,9.117963e+05,9.187525e+05,9.227823e+05,37065.263125,1.726422e+08

## 2.3 Evaluate NZF Costs

In [6]:
years=["26", "29", "32", "35", "38", "41", "44", "47", "50"]
vess_types_not_found_in_inventories, vess_types_not_found_in_global_voys, hs_codes_not_mapped_to_HS, cost_int_match_desc, cost_int_match_desc_bool = [], [], [], [], False

for year in years:

    print("Processing game year 20{0}".format(year))

    # Setup columns for policy costs per bilateral goods trade.
    bau_usd, levy_usd, asis_usd, brazil_usd, liscr_usd, direct_usd = [], [], [], [], [], []
    
    for trade_idx, trade in trade_im.iterrows():

        # initiate selected voyages table as empty dataframe to begin
        int_arr_voys_vess = pd.DataFrame()

        # 3. If no facilitating vessel types were picked up for the HS code, take from full primary int. inv. voyages dataset, otherwise move on...
        if 'all' in trade.fac_vessel_types:
            hs_codes_not_mapped_to_HS.append(trade.HS4_desc)
            int_arr_voys_vess = int_arr_voys
            cost_int_match_desc.append("3. Primary Int. Inv. without Vess Type") if cost_int_match_desc_bool == False else None

        else:
            # 1. If possible, derive subset of voyages associated with the unique vessel type.
            int_arr_voys_vess = int_arr_voys[(int_arr_voys.vessel_type.isin(trade.fac_vessel_types))]    
            
            if int_arr_voys_vess.shape[0] > 0:
                cost_int_match_desc.append("1. Primary Int. Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                
            else:
                # 2. Finally, if no voyages are found as the vessel type doesn't appear in the country's shipping inventories, also take from full voyages dataset filtered for those vessel types instead.
                int_arr_voys_vess = voys_fem[(voys_fem.vessel_type.isin(trade.fac_vessel_types))]

                if int_arr_voys_vess.shape[0] > 0:
                    cost_int_match_desc.append("2. Global Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_inventories.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

                else:
                    # 4. Use full global voyage dataset as a back-up
                    int_arr_voys_vess = voys_fem
                    cost_int_match_desc.append("4. Global Inv. without Vess Type.") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_global_voys.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

        # Add cost intensities associated with the subset of voyages by vessel type, assuming 50% of NZF costs are borne by the importer.
        bau_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "bau35_usd_dwtnm_"+year))
        levy_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "levy35_usd_dwtnm_"+year))
        asis_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "asis35_usd_dwtnm_"+year))
        brazil_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "brazil35_usd_dwtnm_"+year))
        liscr_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "liscr35_usd_dwtnm_"+year))
        direct_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "direct35_usd_dwtnm_"+year))
    
    if cost_int_match_desc_bool == False:
        trade_im["cost_int_match_desc"] = cost_int_match_desc
    cost_int_match_desc_bool = True
    
    trade_im["bau_usd_"+year] = bau_usd
    trade_im["levy_usd_"+year] = levy_usd
    trade_im["asis_usd_"+year] = asis_usd
    trade_im["brazil_usd_"+year] = brazil_usd
    trade_im["liscr_usd_"+year] = liscr_usd
    trade_im["direct_usd_"+year] = direct_usd

print("Inventory voyages table used for the following vessel types: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_inventories).unique()))
print("Global voyages table used for the following vessel types found: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_global_voys).unique()))
print("Global voyages table used for the following commodities as no 'facilitating vessel types' were identified: \n\n{0}\n".format(pd.Series(hs_codes_not_mapped_to_HS).unique()))

print("\nNumber of trade records present in dataset: {0}".format(trade_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_im.partnerCode.unique())))
print("\nTotal value of trade: US${0}m".format(np.round(trade_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_im.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_im.sea_dist_nm.min(), 1),
    round(trade_im.sea_dist_nm.max(), 1),
    round(trade_im.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_im.vol_kg_vtw / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_im.cifvalue / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.cifvalue.sum() / 1000), 1)
))

print("\n\nTotal FEM costs in 2041...\n")
print("BAU: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.bau_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.bau_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Levy: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.levy_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.levy_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("'as-is': US${0}m ({1}% ad-val)".format(
    np.round(trade_im.asis_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.asis_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Brazil: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.brazil_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.brazil_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("LISCR: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.liscr_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.liscr_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Direct: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.direct_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.direct_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))

trade_im_agg = trade_im.groupby(["cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "cifvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_im_agg["vol_kg_vtw_pct"] = round(100 * trade_im_agg.vol_kg_vtw / trade_im_agg.vol_kg_vtw.sum(), 1)
trade_im_agg["cifvalue_pct"] = round(100 * trade_im_agg.cifvalue / trade_im_agg.cifvalue.sum(), 1)
print("Most prominent 'cost intensity match' types...\n\n{0}\n".format(
    trade_im_agg[["cost_int_match_desc", "vol_kg_vtw_pct", "cifvalue_pct"]].head(5)
))
trade_im_agg_2 = trade_im.groupby(["fac_vessel_types_str", "cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "cifvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_im_agg_2["vol_kg_vtw_pct"] = round(100 * trade_im_agg_2.vol_kg_vtw / trade_im_agg_2.vol_kg_vtw.sum(), 1)
trade_im_agg_2["cifvalue_pct"] = round(100 * trade_im_agg_2.cifvalue / trade_im_agg_2.cifvalue.sum(), 1)
print("Most prominent 'facilitating vessel types' and their 'cost intensity match' types...")
display(trade_im_agg_2[["fac_vessel_types_str", "cost_int_match_desc", "vol_kg_vtw_pct", "cifvalue_pct"]].head(5))

trade_im_na = trade_im[(trade_im[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (trade_im.fac_vessel_types.str.len() == 0)]
trade_im = trade_im[(~trade_im[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (~trade_im.fac_vessel_types.str.len() == 0)]
print("Rows with NA: ${0} ({1}%)\n".format(trade_im_na.primaryValue.sum(), round(100 * trade_im_na.primaryValue.sum() / trade_im.primaryValue.sum(), 1)))

trade_im.to_csv(output_dir + "{0}/impact_im_{1}.csv".format(iso_country, version), index=False)
trade_im.head(2)

Processing game year 2026
Processing game year 2029
Processing game year 2032
Processing game year 2035
Processing game year 2038
Processing game year 2041
Processing game year 2044
Processing game year 2047
Processing game year 2050
Inventory voyages table used for the following vessel types:

['Oil tanker' 'Liquefied gas tanker']

Global voyages table used for the following vessel types found:

['Ro-Ro' 'Other liquids tankers' 'Cruise']

Global voyages table used for the following commodities as no 'facilitating vessel types' were identified:

['2309 | Preparations of a ki' '0106 | Animals; live, n.e.c'
 '0307 | Molluscs; whether in' '1704 | Sugar confectionery '
 '3006 | Pharmaceutical goods' '3402 | Organic surface-acti'
 '3808 | Insecticides, rodent' '4011 | New pneumatic tyres,'
 "4418 | Builders' joinery an" '4823 | Paper, paperboard, c'
 '6310 | Rags; used or new, s' '8716 | Trailers and semi-tr'
 '8903 | Yachts and other ves' '9405 | Luminaires and light'
 '4412 | Plywood, veneered pa' '1509 | Olive oil and its fr'
 '8528 | Monitors and project' '9705 | Collections and coll'
 '3307 | Perfumery, cosmetic ' '3824 | Prepared binders for'
 '4911 | Printed matter, n.e.' '6815 | Stone or other miner'
 '6907 | Ceramic flags and pa' '6914 | Ceramic articles; n.'
 '7326 | Iron or steel; artic' '7616 | Aluminium; articles '
 '8215 | Cutlery; spoons, for' '8424 | Mechanical appliance'
 '8456 | Machine-tools; for w' '8462 | Machine-tools (inclu'
 '8514 | Industrial or labora' "6202 | Coats; women's or gi"
 '9701 | Paintings, drawings ' '8525 | Transmission apparat'
 '8708 | Motor vehicles; part' '9403 | Furniture and parts '
 '1806 | Chocolate and other ' '2009 | Fruit or nut juices '
 '3215 | Ink; printing, writi' '8541 | Semiconductor device'
 '2530 | Mineral substances n' '3822 | Reagents; diagnostic'
 '6406 | Footwear; parts of f' '8701 | Tractors; (other tha'
 '4602 | Basketwork, wickerwo' '5703 | Carpets and other te'
 '0910 | Ginger, saffron, tum' '4407 | Wood sawn or chipped'
 '4414 | Wooden frames; for p' '4905 | Maps and hydrographi'
 '6201 | Overcoats, car-coats' '9620 | Monopods, bipods, tr'
 '4419 | Tableware and kitche' '6117 | Clothing accessories'
 '3002 | Human blood; animal ' '9508 | Travelling circuses '
 '0303 | Fish; frozen, exclud' '2202 | Waters, including mi'
 '2621 | Slag and ash n.e.c. ' '3907 | Polyacetals, other p'
 '9703 | Sculptures and statu' '6217 | Clothing accessories'
 '7419 | Copper; articles the' '1404 | Vegetable products n'
 '9401 | Seats (not those of ' '8419 | Machinery, plant (no'
 '8432 | Agricultural, hortic' '8465 | Machine-tools; (incl'
 '8517 | Telephone sets, incl' '8703 | Motor cars and other'
 '4420 | Wood marquetry and i' '4504 | Agglomerated cork (w'
 '5007 | Woven fabrics of sil' '6006 | Fabrics; knitted or '
 '9209 | Musical instrument p' '9702 | Engravings, prints a'
 '0511 | Animal products not ' '8539 | Lamps; electric fila'
 '2106 | Food preparations no' '1905 | Bread, pastry, cakes'
 '3606 | Ferro-cerium and oth' '3926 | Articles of plastics'
 '4421 | Wooden articles n.e.' '5516 | Woven fabrics of art'
 '8311 | Wires, rods, tubes, ' '8487 | Machinery parts; not'
 '1605 | Crustaceans, mollusc' '3707 | Chemical preparation'
 '7019 | Glass fibres (includ' '7229 | Wire of other alloy '
 '9114 | Clock or watch parts' '9406 | Buildings; prefabric'
 '0210 | Meat and edible meat' '0306 | Crustaceans; in shel'
 '0403 | Yogurt; buttermilk, ' '0709 | Vegetables; n.e.c. i'
 '0802 | Nuts (excluding coco' '1510 | Vegetable oils; oils'
 '2204 | Wine of fresh grapes' '2845 | Isotopes other than '
 '2922 | Oxygen-function amin' '3004 | Medicaments; (not go'
 '3105 | Fertilizers; mineral' '3507 | Enzymes; prepared en'
 '5911 | Textile products and' '6304 | Furnishing articles;'
 '9404 | Mattress supports; a' '8501 | Electric motors and '
 '8702 | Vehicles; public tra' '9706 | Antiques; of an age '
 '0604 | Foliage, branches an' '8704 | Vehicles; for the tr'
 '3003 | Medicaments; (not go' '0714 | Manioc, arrowroot, s'
 '3705 | Photographic plates ' '9027 | Instruments and appa'
 '0805 | Citrus fruit; fresh ' '4707 | Waste and scrap of p'
 '2923 | Quaternary ammonium ' '6704 | Wigs, false beards, '
 '4015 | Articles of apparel ' '4401 | Fuel wood, in logs, '
 '4403 | Wood in the rough, w' '6603 | Trimmings, parts and'
 '2910 | Epoxides, epoxyalcoh' '3909 | Amino-resins, phenol'
 '1008 | Buckwheat, millet an' '2853 | Phosphides, chemical'
 '3103 | Fertilizers; mineral' '0712 | Vegetables, dried; w'
 '3812 | Prepared rubber acce' '8421 | Centrifuges, includi'
 '8112 | Beryllium, chromium,' '2914 | Ketones and quinones'
 '6005 | Fabrics; warp knit (' '7508 | Nickel; articles the'
 '2403 | Manufactured tobacco' '5704 | Carpets and other te'
 '8711 | Motorcycles (includi' '2904 | Sulphonated, nitrate'
 '2921 | Amine-function compo' '1214 | Swedes, mangolds, fo'
 '2935 | Sulphonamides' '8103 | Tantalum; articles t'
 '0302 | Fish; fresh or chill' '8414 | Air or vacuum pumps,'
 '8428 | Lifting, handling, l' '8459 | Machine-tools; (incl']


Number of trade records present in dataset: 25663
Number of partner countries present in dataset: 150

Total value of trade: US$2630.1m
Total weight within the dataset: 2171.1 million kilograms

Distance to market: 459.2 nm (min) to 13119.0 nm (max), 5611.4 nm (observed mean)
Average distance to market (volume-weighted): 4543.5 nm
Average distance to market (value-weighted): 4550.3 nm


Total FEM costs in 2041...

BAU: US$37.0m (1.4% ad-val)
Levy: US$74.4m (2.8% ad-val)
'as-is': US$72.1m (2.7% ad-val)
Brazil: US$74.3m (2.8% ad-val)
LISCR: US$50.8m (1.9% ad-val)
Direct: US$48.2m (1.8% ad-val)
Most prominent 'cost intensity match' types...

                      cost_int_match_desc  vol_kg_vtw_pct  cifvalue_pct
0     1. Primary Int. Inv. with Vess Type            92.9          90.5
1           2. Global Inv. with Vess Type             4.1           1.7
2  3. Primary Int. Inv. without Vess Type             3.0           7.8
3       4. Global Inv. without Vess Type.             0.0           0.0

Most prominent 'facilitating vessel types' and their 'cost intensity match' types...

,fac_vessel_types_str,cost_int_match_desc,vol_kg_vtw_pct,cifvalue_pct
0,['Chemical tanker'],1. Primary Int. Inv. with Vess Type,44.4,23.9
1,['Container'],1. Primary Int. Inv. with Vess Type,30.8,52.4
2,['Bulk carrier'],1. Primary Int. Inv. with Vess Type,12.1,2.0
3,['all'],3. Primary Int. Inv. without Vess Type,3.0,7.8
4,['Oil tanker'],2. Global Inv. with Vess Type,2.2,0.9

Rows with NA: $0.0 (0.0%)

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_im_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,cost_int_match_desc,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50
0,0,242,Fiji,528,Netherlands,000,World,Import,Sea,"901380 | Optical devices, app",901380,u,5.75,NaN,2600.342625,NaN,2600.342625,"Netherlands | 901380 | Optical devices, app",90,"90 | Optical, photographi","Netherlands | 90 | Optical, photographi",9013,"9013 | Lasers, other than l","Netherlands | 9013 | Lasers, other than l",90,9013,901380,Liquid crystal devices not constituting articl...,Other Manufacturing,3320,Manufacture of optical instruments and photogr...,87193,"Other optical devices, appliances & instruments",41,OME - Machinery and equipment n.e.c.,48315,"Liquid crystal devices n.e.c.; lasers, except ...",80.1834,0.0125,both,NaN,32.504283,NaN,[Container],['Container'],18430.0,11451.86753,372.234741,1. Primary Int. Inv. with Vess Type,1.696938,1.693692,1.694024,1.694024,1.695472,1.695472,1.777071,3.174268,1.942213,1.822568,1.827838,1.869940,1.739166,3.098387,2.055160,1.889326,1.843989,1.930298,1.705921,3.401786,2.556729,2.238453,2.067821,2.013214,1.673293,3.606933,2.965002,2.757317,2.211551,2.159340,1.641280,3.678554,3.538020,3.582697,2.379284,2.269016,1.608625,3.601201,3.415519,3.724880,2.822344,2.311312,1.577862,3.186662,3.342383,3.494838,2.564950,2.338678,1.546494,2.929716,2.969918,3.578251,2.983602,2.354942
1,1,242,Fiji,528,Netherlands,000,World,Import,Sea,901910 | Mechano-therapy appl,901910,kg,1.47,1.47,15.984780,NaN,15.984780,Netherlands | 901910 | Mechano-therapy appl,90,"90 | Optical, photographi","Netherlands | 90 | Optical, photographi",9019,"9019 | Mechano-therapy, mas","Netherlands | 9019 | Mechano-therapy, mas",90,9019,901910,Mechano-therapy appliances; massage apparatus;...,Other Manufacturing,3311,Manufacture of medical and surgical equipment ...,87231,Mechanotherapy appliances; massage apparatus; ...,41,OME - Machinery and equipment n.e.c.,4816,Mechano-therapy appliances; massage apparatus;...,28.4774,0.0351,both,0.091962,0.561066,1.47,[Container],['Container'],18430.0,11451.86753,6.425251,1. Primary Int. Inv. with Vess Type,0.029291,0.029235,0.029241,0.029241,0.029266,0.029266,0.030675,0.054792,0.033525,0.031460,0.031551,0.032278,0.030020,0.053482,0.035475,0.032612,0.031830,0.033319,0.029446,0.058719,0.044132,0.038639,0.035693,0.034751,0.028883,0.062260,0.051180,0.047595,0.038174,0.037273,0.028331,0.063497,0.061071,0.061842,0.041070,0.039166,0.027767,0.062161,0.058956,0.064296,0.048717,0.039896,0.027236,0.055006,0.057694,0.060325,0.044274,0.040369,0.026694,0.050571,0.051265,0.061765,0.051501,0.040649

## 2.4 Create Results Tables

### 2.4.1 Total Costs per Scenario

In [7]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        np.round(trade_im["bau_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["levy_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["asis_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["brazil_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["liscr_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["direct_usd_{0}".format(year)].sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% cif)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% fob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_fob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_im["bau_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["levy_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["asis_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["direct_usd_{0}".format(year)].sum() / gdp, 3),
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,BAU,39453348.36,38758931.03,38160657.07,37573553.11,36996206.56,36402987.53,35845312.53,35266731.43
1,Levy,64943211.55,62910190.35,69271477.50,76052219.46,74354984.47,72781674.53,64981370.60,61127768.39
2,'as-is',42195622.22,44858407.23,52056022.10,61365677.57,72094783.33,70123200.39,67497049.41,61781116.66
3,Brazil,39737838.63,41332984.64,47978064.18,57854925.64,74345271.84,74658941.39,72771826.90,71938298.05
4,LISCR,39848557.06,40566758.80,45130756.48,47360110.13,50796518.84,58605332.71,56701142.97,60470386.95
5,Direct,41031028.79,42068955.68,43555463.76,46206292.73,48171858.50,48905076.57,49440710.79,49768730.03

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0      BAU  1.50  1.47  1.45  1.43  1.41  1.38  1.36  1.34
1     Levy  2.47  2.39  2.63  2.89  2.83  2.77  2.47  2.32
2  'as-is'  1.60  1.71  1.98  2.33  2.74  2.67  2.57  2.35
3   Brazil  1.51  1.57  1.82  2.20  2.83  2.84  2.77  2.74
4    LISCR  1.52  1.54  1.72  1.80  1.93  2.23  2.16  2.30
5   Direct  1.56  1.60  1.66  1.76  1.83  1.86  1.88  1.89

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  0.636  0.625  0.615  0.606  0.597  0.587  0.578  0.569
1     Levy  1.047  1.015  1.117  1.227  1.199  1.174  1.048  0.986
2  'as-is'  0.681  0.724  0.840  0.990  1.163  1.131  1.089  0.996
3   Brazil  0.641  0.667  0.774  0.933  1.199  1.204  1.174  1.160
4    LISCR  0.643  0.654  0.728  0.764  0.819  0.945  0.915  0.975
5   Direct  0.662  0.679  0.703  0.745  0.777  0.789  0.797  0.803

### 2.4.2 Costs per Scenario relative to BAU

In [8]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        np.round((trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_usd_bau_{1}.csv".format(iso_country, version), index=False)
display(df)

print("\nTotal change in FEM costs by scenario (% bau)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        round((100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2)
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_bau_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% cif)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2)
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% fob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_fob_{1}.csv".format(iso_country, version), index=False)
    display(df)
    
print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3)
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,Levy,25489863.20,24151259.33,31110820.43,38478666.36,37358777.91,36378687.00,29136058.07,25861036.97
1,'as-is',2742273.86,6099476.21,13895365.02,23792124.46,35098576.78,33720212.86,31651736.89,26514385.23
2,Brazil,284490.27,2574053.62,9817407.11,20281372.54,37349065.28,38255953.86,36926514.37,36671566.62
3,LISCR,395208.70,1807827.77,6970099.41,9786557.03,13800312.29,22202345.18,20855830.44,25203655.52
4,Direct,1577680.43,3310024.65,5394806.68,8632739.62,11175651.94,12502089.04,13595398.27,14501998.61

Total change in FEM costs by scenario (% bau)...

  Scenario   2029   2032   2035    2038    2041    2044    2047    2050
0     Levy  64.61  62.31  81.53  102.41  100.98   99.93   81.28   73.33
1  'as-is'   4.00   8.54  14.14   22.98   30.21   34.34   37.93   41.12
2   Brazil   6.95  15.74  36.41   63.32   94.87   92.63   88.30   75.18
3    LISCR   0.72   6.64  25.73   53.98  100.95  105.09  103.02  103.98
4   Direct   1.00   4.66  18.27   26.05   37.30   60.99   58.18   71.47

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0     Levy  0.97  0.92  1.18  1.46  1.42  1.38  1.11  0.98
1  'as-is'  0.06  0.13  0.21  0.33  0.42  0.48  0.52  0.55
2   Brazil  0.10  0.23  0.53  0.90  1.33  1.28  1.20  1.01
3    LISCR  0.01  0.10  0.37  0.77  1.42  1.45  1.40  1.39
4   Direct  0.02  0.07  0.27  0.37  0.52  0.84  0.79  0.96

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  0.411  0.390  0.502  0.621  0.603  0.587  0.470  0.417
1  'as-is'  0.025  0.053  0.087  0.139  0.180  0.202  0.219  0.234
2   Brazil  0.044  0.098  0.224  0.384  0.566  0.544  0.511  0.428
3    LISCR  0.005  0.042  0.158  0.327  0.602  0.617  0.596  0.591
4   Direct  0.006  0.029  0.112  0.158  0.223  0.358  0.336  0.407

# 3. Let's consider Exports

## 3.1 Read-in Trade dataset

In [9]:
trade_ex_d = {
    "reporterCode":"str", "partnerCode":"str", "partner2Code":"str", 
    "cmdCode":"str", "HS2":"str", "HS4":"str", "hs2":"str", "hs4":"str", "hs6":"str",
    "isic":"str", "sitc":"str", "gtap":"str", "cpc":"str"
}
if res_mlc == False:
    trade_ex = pd.read_csv(input_dir+"trade/{0}/trade_ex_dist_{1}.csv".format(iso_country, version), dtype=trade_ex_d)
else:
    trade_ex = pd.read_csv(input_dir+"trade/{0}/trade_ex_mlc_{1}.csv".format(iso_country, version), dtype=trade_ex_d)
trade_ex['fac_vessel_types'] = [ast.literal_eval(x) for x in trade_ex.fac_vessel_types.values]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(trade_ex.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_ex.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(trade_ex.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(trade_ex.fobvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_ex.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_ex.sea_dist_nm.min(), 1),
    round(trade_ex.sea_dist_nm.max(), 1),
    round(trade_ex.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_ex.vol_kg_vtw / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_ex.fobvalue / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.fobvalue.sum() / 1000), 1)
))
trade_ex.head(2)

Aggregate trade portfolio statistics for 'Fiji':

Number of trade records present in dataset: 4019
Number of partner countries present in dataset: 84
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$455.4m
Total weight within the dataset: 8194.3 million kilograms

Distance to market: 459.8 nm (min) to 12699.6 nm (max), 2099.2 nm (observed mean)
Average distance to market (volume-weighted): 5415.1 nm
Average distance to market (value-weighted): 4136.8 nm

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_ex_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm
0,0,242,Fiji,548,Vanuatu,000,World,Domestic Export,Sea,"081050 | Fruit, edible; kiwif",81050,kg,2.97783,2.97783,NaN,48.08913,48.08913,"Vanuatu | 081050 | Fruit, edible; kiwif",08,"08 | Fruit and nuts, edib","Vanuatu | 08 | Fruit and nuts, edib",0810,"0810 | Fruit, fresh; n.e.c.","Vanuatu | 0810 | Fruit, fresh; n.e.c.",08,0810,081050,"Kiwifruit, fresh",Agriculture,0113,"Growing of fruit, nuts, beverage and spice crops",05798,Fresh fruit other than headings 057.91- 057.97,04,"V_F - Vegetables, fruit, nuts",0134,"Other fruit, fresh",2.6569,0.3764,both,0.061923,18.100749,2.97783,[Container],['Container'],992.0,616.400032,11.157302
1,1,242,Fiji,548,Vanuatu,000,World,Domestic Export,Sea,"081090 | Fruit, edible; fruit",81090,kg,15.43791,15.43791,NaN,250.27491,250.27491,"Vanuatu | 081090 | Fruit, edible; fruit",08,"08 | Fruit and nuts, edib","Vanuatu | 08 | Fruit and nuts, edib",0810,"0810 | Fruit, fresh; n.e.c.","Vanuatu | 0810 | Fruit, fresh; n.e.c.",08,0810,081090,"Fresh fruit, n.e.s. in Ch. 8",Agriculture,0113,"Growing of fruit, nuts, beverage and spice crops",05798,Fresh fruit other than headings 057.91- 057.97,04,"V_F - Vegetables, fruit, nuts",0134,"Other fruit, fresh",2.6569,0.3764,both,0.061684,94.203476,15.43791,[Container],['Container'],992.0,616.400032,58.067026

## 3.2 Derive Internationally Departing Voyages

In [10]:
# International Departures
int_arr_voys = voys_fem[(voys_fem.dest_country == iso_country) & (voys_fem.source_country != iso_country)].reset_index(drop=True)
int_arr_voys.to_csv(output_dir + "{0}/int_arr_voys_{1}.csv".format(iso_country, version), index=False)
int_dep_voys = voys_fem[(voys_fem.source_country == iso_country) & (voys_fem.dest_country != iso_country)].reset_index(drop=True)
int_dep_voys.to_csv(output_dir + "{0}/int_dep_voys_{1}.csv".format(iso_country, version), index=False)
voyages_analysis(int_dep_voys)
int_dep_voys.head(2)

Number of Voyages found: 274
Total size of the fleet: 112 vessels
6 vessel types contained in the dataset: ['Refrigerated bulk' 'Bulk carrier' 'General cargo' 'Container' 'Vehicle'
 'Chemical tanker']
Total transport work capacity: 15780.8 million deadweight-tonne nautical miles
Total cargo transported: 4332581.7 tonnes
Total transport work: 9377.5 million tonne nautical miles
Average build year of the fleet: 2007
Total Energy Demands: 1791.8 EJ
Total CO2 produced: 138395.4 tonnes

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,31614,8604967,372768000,FJLEV,242,FJI,FJ,Fiji,Levuka,TWKHH,158,TWN,TW,"Taiwan, Province of China",Kaohsiung,2018-08-11 19:00:00,2018-11-17 11:00:00,2344.0,498.0,2842.0,17905.602861,233.600280,0.003982,233.604262,583.2195,156.5712,739.7907,0.0,0.0,0.0,0.0,0.0,0.0,34.294204,6.685750,2597.232988,501.979668,3099.212655,009,Oceania,054,Melanesia,upp_mid_income,0,1,142,Asia,030,Eastern Asia,upp_mid_income,0,0,40.979954,Refrigerated bulk,2525.0,dwt,2800.0,NaN,NaN,NaN,NaN,2,2000-5999,1986.0,Panama,SSD,1,76.1,0.666667,0.031550,0.032676,0.032143,0.031676,0.031218,0.030769,0.030310,0.029878,0.029438,0.031576,0.052178,0.052414,0.058040,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.059420,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,5.013569e+07,1.581798e+06,1.638211e+06,1.611526e+06,1.588122e+06,1.565152e+06,1.542615e+06,1.519627e+06,1.497970e+06,1.475888e+06,1.583065e+06,2.615998e+06,2.627819e+06,2.909852e+06,3.008208e+06,2.972882e+06,2.929661e+06,2.919316e+06,2.923853e+06,1.582706e+06,1.736894e+06,1.847170e+06,2.242349e+06,2.487804e+06,2.701436e+06,2.897695e+06,2.961285e+06,2.907808e+06,1.582706e+06,1.640773e+06,1.731145e+06,2.042284e+06,2.415435e+06,2.800782e+06,2.880163e+06,2.941550e+06,2.979043e+06,1.582245e+06,1.639368e+06,1.695004e+06,1.903984e+06,2.011890e+06,2.097506e+06,2.171605e+06,2.240932e+06,2.300042e+06,1.582245e+06,1.703870e+06,1.749559e+06,1.811430e+06,1.920023e+06,2.001620e+06,2.035800e+06,2.060509e+06,2.078795e+06,1866.666668,3.342379e+07
1,40464,8806503,373264000,FJELL,242,FJI,FJ,Fiji,Ellington Wharf,CNLKU,156,CHN,CN,China,Longkou,2018-02-16 03:00:00,2018-03-07 08:00:00,461.0,86.0,547.0,4736.559213,272.245964,11.981635,284.227599,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,10.944288,0.481662,847.773933,37.310810,885.084744,009,Oceania,054,Melanesia,upp_mid_income,0,1,142,Asia,030,Eastern Asia,upp_mid_income,0,0,11.425949,Bulk carrier,38337.0,dwt,70424.0,NaN,NaN,NaN,NaN,4,60000-99999,1990.0,Panama,SSD,1,4.1,0.526316,0.002221,0.002300,0.002262,0.002230,0.002198,0.002167,0.002135,0.002105,0.002074,0.002217,0.003631,0.003523,0.003915,0.004274,0.004276,0.004123,0.003866,0.003574,0.002217,0.002414,0.002495,0.003009,0.003449,0.004105,0.003936,0.003844,0.003749,0.002217,0.002282,0.002388,0.002784,0.003264,0.004337,0.004165,0.004176,0.004096,0.002219,0.002290,0.002358,0.002635,0.002787,0.003024,0.003409,0.003302,0.003461,0.002219,0.002379,0.002433,0.002509,0.002646,0.002745,0.002780,0.002801,0.002813,3.335674e+08,7.408998e+05,7.670656e+05,7.546885e+05,7.438331e+05,7.331789e+05,7.227257e+05,7.120631e+05,7.020181e+05,6.917754e+05,7.394738e+05,1.211283e+06,1.175005e+06,1.306081e+06,1.425806e+06,1.426254e+06,1.375457e+06,1.289552e+06,1.192223e+06,7.396432e+05,8.051204e+05,8.320919e+05,1.003843e+06,1.150525e+06,1.369430e+06,1.312886e+06,1.282319e+06,1.250542e+06,7.396432e+05,7.611061e+05,7.964429e+05,9.287463e+05,1.088917e+06,1.446734e+06,1.389329e+06,1.392950e+06,1.366454e+06,7.402684e+05,7.640324e+05,7.866804e+05,8.789686e+05,9.297007e+05,1.008853e+06,1.137121e+06,1.101445e+06,1.154561e+06,7.402684e+05,7.937044e+05,8.117275e+05,8.368348e+05,8.826624e+05,9.157425e+05,9.272160e+05,9.342898e+05,9.383878e+05,37065.263125,1.755618e+08

## 3.3 Evaluate NZF Costs

In [11]:
years=["26", "29", "32", "35", "38", "41", "44", "47", "50"]
vess_types_not_found_in_inventories, vess_types_not_found_in_global_voys, hs_codes_not_mapped_to_HS, cost_int_match_desc, cost_int_match_desc_bool = [], [], [], [], False

for year in years:

    print("Processing game year 20{0}".format(year))

    # Setup columns for policy costs per bilateral goods trade.
    bau_usd, levy_usd, asis_usd, brazil_usd, liscr_usd, direct_usd = [], [], [], [], [], []
    
    for trade_idx, trade in trade_ex.iterrows():

        # initiate selected voyages table as empty dataframe to begin
        int_dep_voys_vess = pd.DataFrame()

        # 3. If no facilitating vessel types were picked up for the HS code, take from full primary int. inv. voyages dataset, otherwise move on...
        if 'all' in trade.fac_vessel_types:
            hs_codes_not_mapped_to_HS.append(trade.HS4_desc)
            int_dep_voys_vess = int_dep_voys
            cost_int_match_desc.append("3. Primary Int. Inv. without Vess Type") if cost_int_match_desc_bool == False else None

        else:
            # 1. If possible, derive subset of voyages associated with the unique vessel type.
            int_dep_voys_vess = int_dep_voys[(int_dep_voys.vessel_type.isin(trade.fac_vessel_types))]    
            
            if int_dep_voys_vess.shape[0] > 0:
                cost_int_match_desc.append("1. Primary Int. Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                
            else:
                # 2. Finally, if no voyages are found as the vessel type doesn't appear in the country's shipping inventories, also take from full voyages dataset filtered for those vessel types instead.
                int_dep_voys_vess = voys_fem[(voys_fem.vessel_type.isin(trade.fac_vessel_types))]
                
                if int_dep_voys_vess.shape[0] > 0:
                    cost_int_match_desc.append("2. Global Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_inventories.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

                else:
                    # 4. Use full global voyage dataset as a back-up
                    int_dep_voys_vess = voys_fem
                    cost_int_match_desc.append("4. Global Inv. without Vess Type.") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_global_voys.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]
    
        # Add cost intensities associated with the subset of voyages by vessel type, assuming 50% of NZF costs are borne by the exporter.
        bau_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "bau35_usd_dwtnm_"+year))
        levy_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "levy35_usd_dwtnm_"+year))
        asis_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "asis35_usd_dwtnm_"+year))
        brazil_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "brazil35_usd_dwtnm_"+year))
        liscr_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "liscr35_usd_dwtnm_"+year))
        direct_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "direct35_usd_dwtnm_"+year))

    if cost_int_match_desc_bool == False:
        trade_ex["cost_int_match_desc"] = cost_int_match_desc
    cost_int_match_desc_bool = True

    trade_ex["bau_usd_"+year] = bau_usd
    trade_ex["levy_usd_"+year] = levy_usd
    trade_ex["asis_usd_"+year] = asis_usd
    trade_ex["brazil_usd_"+year] = brazil_usd
    trade_ex["liscr_usd_"+year] = liscr_usd
    trade_ex["direct_usd_"+year] = direct_usd
    
print("Inventory voyages table used for the following vessel types: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_inventories).unique()))
print("Global voyages table used for the following vessel types found: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_global_voys).unique()))
print("Global voyages table used for the following commodities as no 'facilitating vessel types' were identified: \n\n{0}\n".format(pd.Series(hs_codes_not_mapped_to_HS).unique()))

print()
print("Number of trade records present in dataset: {0}".format(trade_ex.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_ex.partnerCode.unique())))
print("\nTotal value of trade: US${0}m".format(np.round(trade_ex.fobvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_ex.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_ex.sea_dist_nm.min(), 1),
    round(trade_ex.sea_dist_nm.max(), 1),
    round(trade_ex.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_ex.vol_kg_vtw / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_ex.fobvalue / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.fobvalue.sum() / 1000), 1)
))

print("\n\nTotal FEM costs in 2041...\n")
print("BAU: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.bau_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.bau_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Levy: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.levy_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.levy_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("'as-is': US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.asis_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.asis_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Brazil: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.brazil_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.brazil_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("LISCR: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.liscr_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.liscr_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Direct: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.direct_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.direct_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))

trade_ex_agg = trade_ex.groupby(["cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "fobvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_ex_agg["vol_kg_vtw_pct"] = round(100 * trade_ex_agg.vol_kg_vtw / trade_ex_agg.vol_kg_vtw.sum(), 1)
trade_ex_agg["fobvalue_pct"] = round(100 * trade_ex_agg.fobvalue / trade_ex_agg.fobvalue.sum(), 1)
print("Most prominent 'cost intensity match' types...\n\n{0}\n".format(
    trade_ex_agg[["cost_int_match_desc", "vol_kg_vtw_pct", "fobvalue_pct"]].head(5)
))
trade_ex_agg_2 = trade_ex.groupby(["fac_vessel_types_str", "cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "fobvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_ex_agg_2["vol_kg_vtw_pct"] = round(100 * trade_ex_agg_2.vol_kg_vtw / trade_ex_agg_2.vol_kg_vtw.sum(), 1)
trade_ex_agg_2["fobvalue_pct"] = round(100 * trade_ex_agg_2.fobvalue / trade_ex_agg_2.fobvalue.sum(), 1)
print("Most prominent 'facilitating vessel types' and their 'cost intensity match' types...")
display(trade_ex_agg_2[["fac_vessel_types_str", "cost_int_match_desc", "vol_kg_vtw_pct", "fobvalue_pct"]].head(5))

trade_ex_na = trade_ex[(trade_ex[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (trade_ex.fac_vessel_types.str.len() == 0)]
trade_ex = trade_ex[(~trade_ex[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (~trade_ex.fac_vessel_types.str.len() == 0)]
print("Rows with NA: ${0} ({1}%)\n".format(trade_ex_na.primaryValue.sum(), round(100 * trade_ex_na.primaryValue.sum() / trade_ex.primaryValue.sum(), 1)))

trade_ex.to_csv(output_dir + "{0}/impact_ex_{1}.csv".format(iso_country, version), index=False)
trade_ex.head(2)

Processing game year 2026
Processing game year 2029
Processing game year 2032
Processing game year 2035
Processing game year 2038
Processing game year 2041
Processing game year 2044
Processing game year 2047
Processing game year 2050
Inventory voyages table used for the following vessel types:

['Oil tanker' 'Liquefied gas tanker']

Global voyages table used for the following vessel types found:

['Other liquids tankers']

Global voyages table used for the following commodities as no 'facilitating vessel types' were identified:

['3307 | Perfumery, cosmetic ' '3824 | Prepared binders for'
 '4602 | Basketwork, wickerwo' '0910 | Ginger, saffron, tum'
 '2530 | Mineral substances n' '3402 | Organic surface-acti'
 '4823 | Paper, paperboard, c' '5516 | Woven fabrics of art'
 '7326 | Iron or steel; artic' '8525 | Transmission apparat'
 '0303 | Fish; frozen, exclud' '3004 | Medicaments; (not go'
 '2009 | Fruit or nut juices ' '4911 | Printed matter, n.e.'
 '9403 | Furniture and parts ' '1806 | Chocolate and other '
 '3006 | Pharmaceutical goods' '8903 | Yachts and other ves'
 '0714 | Manioc, arrowroot, s' '4419 | Tableware and kitche'
 '6006 | Fabrics; knitted or ' '0306 | Crustaceans; in shel'
 '0403 | Yogurt; buttermilk, ' '4407 | Wood sawn or chipped'
 '9405 | Luminaires and light' '1605 | Crustaceans, mollusc'
 '6201 | Overcoats, car-coats' '6406 | Footwear; parts of f'
 '4905 | Maps and hydrographi' "6202 | Coats; women's or gi"
 '1905 | Bread, pastry, cakes' '2106 | Food preparations no'
 '3926 | Articles of plastics' '6907 | Ceramic flags and pa'
 '3707 | Chemical preparation' '7229 | Wire of other alloy '
 '8716 | Trailers and semi-tr' '0308 | Aquatic invertebrate'
 '5007 | Woven fabrics of sil' '8708 | Motor vehicles; part'
 '4403 | Wood in the rough, w' '2202 | Waters, including mi'
 '3822 | Reagents; diagnostic' '6117 | Clothing accessories'
 '8517 | Telephone sets, incl' '7419 | Copper; articles the'
 '4412 | Plywood, veneered pa' "4418 | Builders' joinery an"
 '0805 | Citrus fruit; fresh ' '1704 | Sugar confectionery '
 '2309 | Preparations of a ki' '8701 | Tractors; (other tha'
 '9406 | Buildings; prefabric' '4421 | Wooden articles n.e.'
 '9701 | Paintings, drawings ' '3215 | Ink; printing, writi'
 '9401 | Seats (not those of ' '0604 | Foliage, branches an'
 '4707 | Waste and scrap of p' '1509 | Olive oil and its fr'
 '1404 | Vegetable products n' '4011 | New pneumatic tyres,'
 '6217 | Clothing accessories' '3808 | Insecticides, rodent'
 '5703 | Carpets and other te' '7616 | Aluminium; articles '
 '0106 | Animals; live, n.e.c' '3105 | Fertilizers; mineral'
 '9404 | Mattress supports; a' '0709 | Vegetables; n.e.c. i'
 '8424 | Mechanical appliance' '9705 | Collections and coll'
 '4402 | Wood charcoal (inclu']


Number of trade records present in dataset: 4019
Number of partner countries present in dataset: 84

Total value of trade: US$455.4m
Total weight within the dataset: 8194.3 million kilograms

Distance to market: 459.8 nm (min) to 12699.6 nm (max), 2099.2 nm (observed mean)
Average distance to market (volume-weighted): 5415.1 nm
Average distance to market (value-weighted): 4136.8 nm


Total FEM costs in 2041...

BAU: US$193.7m (42.5% ad-val)
Levy: US$432.5m (95.0% ad-val)
'as-is': US$416.0m (91.3% ad-val)
Brazil: US$421.5m (92.6% ad-val)
LISCR: US$280.2m (61.5% ad-val)
Direct: US$267.0m (58.6% ad-val)
Most prominent 'cost intensity match' types...

                      cost_int_match_desc  vol_kg_vtw_pct  fobvalue_pct
0     1. Primary Int. Inv. with Vess Type            99.8          94.2
1  3. Primary Int. Inv. without Vess Type             0.1           5.8
2           2. Global Inv. with Vess Type             0.0           0.1
3       4. Global Inv. without Vess Type.             0.0           0.0

Most prominent 'facilitating vessel types' and their 'cost intensity match' types...

,fac_vessel_types_str,cost_int_match_desc,vol_kg_vtw_pct,fobvalue_pct
0,['Container'],1. Primary Int. Inv. with Vess Type,94.7,75.7
1,['Bulk carrier'],1. Primary Int. Inv. with Vess Type,2.6,9.6
2,"['Container', 'General cargo']",1. Primary Int. Inv. with Vess Type,1.3,0.4
3,['Chemical tanker'],1. Primary Int. Inv. with Vess Type,0.8,2.8
4,"['Container', 'Bulk carrier']",1. Primary Int. Inv. with Vess Type,0.5,4.5

Rows with NA: $0.0 (0.0%)

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_ex_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,cost_int_match_desc,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50
0,0,242,Fiji,548,Vanuatu,000,World,Domestic Export,Sea,"081050 | Fruit, edible; kiwif",81050,kg,2.97783,2.97783,NaN,48.08913,48.08913,"Vanuatu | 081050 | Fruit, edible; kiwif",08,"08 | Fruit and nuts, edib","Vanuatu | 08 | Fruit and nuts, edib",0810,"0810 | Fruit, fresh; n.e.c.","Vanuatu | 0810 | Fruit, fresh; n.e.c.",08,0810,081050,"Kiwifruit, fresh",Agriculture,0113,"Growing of fruit, nuts, beverage and spice crops",05798,Fresh fruit other than headings 057.91- 057.97,04,"V_F - Vegetables, fruit, nuts",0134,"Other fruit, fresh",2.6569,0.3764,both,0.061923,18.100749,2.97783,[Container],['Container'],992.0,616.400032,11.157302,1. Primary Int. Inv. with Vess Type,0.050684,0.050587,0.050596,0.050596,0.05064,0.05064,0.053079,0.094832,0.057996,0.054440,0.054598,0.055852,0.051946,0.092556,0.061378,0.056431,0.055075,0.057656,0.050952,0.101646,0.076365,0.066860,0.061761,0.060133,0.049977,0.107768,0.088586,0.082364,0.066052,0.064499,0.049020,0.109927,0.105747,0.107094,0.071047,0.067776,0.048044,0.107614,0.102037,0.111264,0.084360,0.069040,0.047125,0.095206,0.099875,0.104425,0.076595,0.069857,0.046187,0.087531,0.088725,0.106795,0.089071,0.070344
1,1,242,Fiji,548,Vanuatu,000,World,Domestic Export,Sea,"081090 | Fruit, edible; fruit",81090,kg,15.43791,15.43791,NaN,250.27491,250.27491,"Vanuatu | 081090 | Fruit, edible; fruit",08,"08 | Fruit and nuts, edib","Vanuatu | 08 | Fruit and nuts, edib",0810,"0810 | Fruit, fresh; n.e.c.","Vanuatu | 0810 | Fruit, fresh; n.e.c.",08,0810,081090,"Fresh fruit, n.e.s. in Ch. 8",Agriculture,0113,"Growing of fruit, nuts, beverage and spice crops",05798,Fresh fruit other than headings 057.91- 057.97,04,"V_F - Vegetables, fruit, nuts",0134,"Other fruit, fresh",2.6569,0.3764,both,0.061684,94.203476,15.43791,[Container],['Container'],992.0,616.400032,58.067026,1. Primary Int. Inv. with Vess Type,0.263778,0.263272,0.263324,0.263324,0.26355,0.26355,0.276243,0.493542,0.301837,0.283327,0.284148,0.290677,0.270347,0.481700,0.319437,0.293691,0.286635,0.300063,0.265176,0.529008,0.397432,0.347968,0.321430,0.312957,0.260100,0.560868,0.461036,0.428652,0.343762,0.335680,0.255121,0.572104,0.550348,0.557357,0.369755,0.352733,0.250041,0.560067,0.531039,0.579063,0.439045,0.359311,0.245256,0.495488,0.519791,0.543467,0.398631,0.363566,0.240377,0.455546,0.461763,0.555805,0.463561,0.366097

## 3.4 Create Results Tables

### 3.4.1 Total Costs per Scenario

In [12]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        np.round(trade_ex["bau_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["levy_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["asis_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["brazil_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["liscr_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["direct_usd_{0}".format(year)].sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% cif)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
    display(df)

    
print("\nTotal FEM costs by scenario (% fob)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_fob_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / gdp, 3)
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,BAU,2.095323e+08,2.051018e+08,2.012160e+08,1.974023e+08,1.936605e+08,1.898437e+08,1.862481e+08,1.825816e+08
1,Levy,3.728221e+08,3.637828e+08,3.994770e+08,4.240137e+08,4.324622e+08,4.229011e+08,3.745578e+08,3.446884e+08
2,'as-is',2.286812e+08,2.419061e+08,3.004412e+08,3.483804e+08,4.159784e+08,4.013257e+08,3.927118e+08,3.493378e+08
3,Brazil,2.147296e+08,2.226135e+08,2.635171e+08,3.241205e+08,4.215422e+08,4.372286e+08,4.110174e+08,4.198645e+08
4,LISCR,2.153471e+08,2.173353e+08,2.436119e+08,2.603336e+08,2.801656e+08,3.323195e+08,3.023940e+08,3.503759e+08
5,Direct,2.203582e+08,2.274033e+08,2.370836e+08,2.541501e+08,2.669503e+08,2.718823e+08,2.750715e+08,2.769709e+08

Total FEM costs by scenario (% fob)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  46.01  45.04  44.18  43.34  42.52  41.68  40.90  40.09
1     Levy  81.86  79.88  87.71  93.10  94.96  92.86  82.24  75.68
2  'as-is'  50.21  53.12  65.97  76.50  91.34  88.12  86.23  76.71
3   Brazil  47.15  48.88  57.86  71.17  92.56  96.00  90.25  92.19
4    LISCR  47.28  47.72  53.49  57.16  61.52  72.97  66.40  76.93
5   Direct  48.38  49.93  52.06  55.80  58.62  59.70  60.40  60.82

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  3.380  3.308  3.245  3.184  3.124  3.062  3.004  2.945
1     Levy  6.013  5.867  6.443  6.839  6.975  6.821  6.041  5.559
2  'as-is'  3.688  3.902  4.846  5.619  6.709  6.473  6.334  5.634
3   Brazil  3.463  3.591  4.250  5.228  6.799  7.052  6.629  6.772
4    LISCR  3.473  3.505  3.929  4.199  4.519  5.360  4.877  5.651
5   Direct  3.554  3.668  3.824  4.099  4.306  4.385  4.437  4.467

### 3.4.2 Costs per Scenario relative to BAU

In [13]:
print("\nTotal FEM costs by scenario (US$)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:

    d_temp = {"20{0}".format(year): [
        np.round((trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_usd_bau_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal change in FEM costs by scenario (% bau)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        round((100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_bau_{1}.csv".format(iso_country, version), index=False)
display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% cif)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_cif_{1}.csv".format(iso_country, version), index=False)
    display(df)


print("\nTotal FEM costs by scenario (% fob)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_fob_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,Levy,1.632899e+08,1.586810e+08,1.982610e+08,2.266114e+08,2.388018e+08,2.330574e+08,1.883097e+08,1.621068e+08
1,'as-is',1.914899e+07,3.680430e+07,9.922522e+07,1.509781e+08,2.223179e+08,2.114819e+08,2.064637e+08,1.667561e+08
2,Brazil,5.197357e+06,1.751171e+07,6.230110e+07,1.267183e+08,2.278817e+08,2.473849e+08,2.247694e+08,2.372829e+08
3,LISCR,5.814867e+06,1.223350e+07,4.239593e+07,6.293134e+07,8.650509e+07,1.424757e+08,1.161460e+08,1.677943e+08
4,Direct,1.082596e+07,2.230150e+07,3.586755e+07,5.674783e+07,7.328985e+07,8.203861e+07,8.882341e+07,9.438931e+07

Total change in FEM costs by scenario (% bau)...

  Scenario   2029   2032   2035    2038    2041    2044    2047    2050
0     Levy  77.93  77.37  98.53  114.80  123.31  122.76  101.11   88.79
1  'as-is'   9.14  17.94  49.31   76.48  114.80  111.40  110.85   91.33
2   Brazil   2.48   8.54  30.96   64.19  117.67  130.31  120.68  129.96
3    LISCR   2.78   5.96  21.07   31.88   44.67   75.05   62.36   91.90
4   Direct   5.17  10.87  17.83   28.75   37.84   43.21   47.69   51.70

Total FEM costs by scenario (% fob)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  35.85  34.84  43.53  49.76  52.43  51.17  41.35  35.59
1  'as-is'   4.20   8.08  21.79  33.15  48.82  46.44  45.33  36.62
2   Brazil   1.14   3.85  13.68  27.82  50.04  54.32  49.35  52.10
3    LISCR   1.28   2.69   9.31  13.82  18.99  31.28  25.50  36.84
4   Direct   2.38   4.90   7.88  12.46  16.09  18.01  19.50  20.73

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  2.634  2.559  3.198  3.655  3.852  3.759  3.037  2.615
1  'as-is'  0.309  0.594  1.600  2.435  3.586  3.411  3.330  2.690
2   Brazil  0.084  0.282  1.005  2.044  3.676  3.990  3.625  3.827
3    LISCR  0.094  0.197  0.684  1.015  1.395  2.298  1.873  2.706
4   Direct  0.175  0.360  0.579  0.915  1.182  1.323  1.433  1.522